### ISSUE TITLE
Rollback date display bug

### ISSUE THREAD

**Issue by BlackRockCity** [ronivay/XenOrchestraInstallerUpdater#103]
**OS Version**:
Debian 10
**Node.js version**: node -v
14.18.2
**Yarn version**: yarn -v
1.22.5

**Server specs**
amount of vCPUs and RAM on the machine where you attempt to install

**Issue**
roll back shows a bug in how it displays dates. Note 3 and 4 were snapshots that are hours apart on Dec 29, 2021. One is  displayed as 1229 and the other is 2912. Month and day are swapped in the latest snapshot. 

Which installation to roll back?

1) /opt/xo/xo-builds/xen-orchestra-202130040415	 3) /opt/xo/xo-builds/xen-orchestra-202129122111
2) /opt/xo/xo-builds/xen-orchestra-202130040504	 4) /opt/xo/xo-builds/xen-orchestra-202112292220

**Comment by ronivay** [comment]
Can you verify that directories are named correctly under /opt/xo/xo-builds to confirm this actually applies to just rollback listing.

**Comment by BlackRockCity** [comment]
Unfortunately, I had to restore from a XCP-NG snapshot (not to be confused with an xo-install.sh snapshot) so its too late for me to answer that question.

**Comment by ronivay** [comment]
> Unfortunately, I had to restore from a XCP-NG snapshot (not to be confused with an xo-install.sh snapshot) so its too late for me to answer that question.

Hmm okay. I'll look into this if i'm able to reproduce but can't think why the listing would show anything but actual directory names it finds. If they're wrong, that would be the date command acting up during install/update for some reason as the format is statically set to YYYYMMDD.

**Comment by BlackRockCity** [comment]
I updated to the latest script and successfully installed the latest xo-server and xo-web.

Notice that the date format changed! 
First two snapshots are YYYY**DDMM**HHMM
Latest snapshot is YYYY**MMDD**HHMM

root@debianXOA:/opt/xo/xo-builds# ls -l
total 12
drwxr-xr-x 10 root root 4096 Dec 30 02:16 xen-orchestra-202112300215
drwxr-xr-x  8 root root 4096 Apr 30  2021 xen-orchestra-202130040415
drwxr-xr-x  9 root root 4096 Apr 30  2021 xen-orchestra-202130040504

**Comment by ronivay** [comment]
Yeah, format the script uses was changed a ~year ago. Sorry, i know it's confusing if you have older installations or installations done with older script version in place. YYYYDDMM format was a remnant from the early days and it's much more difficult to read when there's a lot of logfiles etc which are all formatted in same way so it was changed to YYYYMMDD. This could be the culprit of this issue if you had differing script versions between those couple installations.

**Comment by BlackRockCity** [comment]
As for my original post (regarding snapshots that were hours apart), it probably had to do with switching between two older scripts. When I posted this issue, I thought that the scripts were automatically up to date. I also thought that the scripts were the exact same version, but maybe they were not.

**Comment by ronivay** [comment]
Yeah sounds like that was the case. Unfortunately the autoupgrade feature implemented quite recently can't find it's way to older versions so those obviously stay as is. As you're now running latest version, it should autoupgrade just fine.

I'll close this issue for now.
