### ISSUE TITLE
Default web account recovery

### ISSUE THREAD

**Issue by vipex225** [ronivay/XenOrchestraInstallerUpdater#106]
Hi,
I am trying to figure out if it's possible to recover the default admin@admin.net account for XO with it's default password, directly from cli in the host operating system (centos 8 in my case).
Thanks!

**Comment by ronivay** [comment]
Hi,

Yeah it is. Run `/opt/xo/xo-server/dist/recover-account-cli-mjs admin@admin.net` and enter password you wish to use. This will either reset the password if user exists or create it with admin permissions if it doesn't.

Change path accordingly if you used some other `INSTALLDIR` variable in `xo-install.cfg` than default `/opt/xo`

**Comment by vipex225** [comment]
Works like a charm, thank you very much!
