### ISSUE TITLE
Issue with Continuous Replication to Multiple Destinations

### ISSUE THREAD

**Issue by digivenue** [ronivay/XenOrchestraInstallerUpdater#107]
**OS Version**: Ubuntu Server 20.04.3 LTS
**Node.js version**: v14.18.3
**Yarn version**: 1.22.17

**Server specs**
2 vCPUs 8GB RAM

**Issue**
The Xen Orchestra support page says to start with the script provider when using 3rd party scripts to install XOA so here goes, I know you may not have a solution. 
The issue I have found is related to Continuous Replication tasks when you have multiple destinations selected. It runs fine on the initial copy and anytime it does a full copy. But when doing deltas while multiple locations are selected the delta replications all end up on the same destination not individually on all the destinations like it should. I have replicated this by reinstalling XOA using this script fresh on a new machine. Selecting one destination for Continuous Replication works fine. Selecting multiple locations and forcing it to do a full copy each time works fine. But selecting multiple destinations and allowing it to do delta copies results in this issue of them all going to one of the destinations.

**Installation logfile**
I apologize for not attaching any logs, not sure which logs would be useful for this.

**Comment by ronivay** [comment]
Hello,

Yeah that is to filter out any obvious 3rd party script issues and not burden XO team with those.

I can only test with multiple SR's in my lab and can't reproduce the issue you described. Initial full copy and following deltas end up to all SR's chosen in the continuous replication job.

Anyway, as you suspected, shouldn't be related to install procedure done by this script. XO forum would be the next place to ask if you don't find any obvious cause for it. Just remember to update to latest master branch commit and mention that along with the fact that you're running XO from sources :)

**Comment by digivenue** [comment]
Thanks for checking. Yeah what I end up with is three copies of the replicated vm but there is only one base copy and all three of the delta on one host. You can see base copies on all repositories?
![image](https://user-images.githubusercontent.com/98611083/151615567-3a9eba59-4b66-4b7a-9379-c7c8d26e6f7a.png)

**Comment by ronivay** [comment]
Hmm i think you're right. Not sure if i missed it on the first test, but managed to reproduce it now. It indeed looks like it somehow merges things only to one of the SR's. The base copy that ends up to both SR's on full backup is then also lost from others. Seems like a bug to me. I'd suggest to open a thread in XO forum with as much details as you can provide and continue from there.

**Comment by digivenue** [comment]
Sorry for leaving this open so long, closing it now.
