### ISSUE TITLE
Backup proxy deploys and connection is working but can't backup

### ISSUE THREAD

**Issue by bogdantomasciuc** [ronivay/XenOrchestraInstallerUpdater#111]
Hello!

This is not related to the install. It works spectacularly, the proxy installs and I am able to import the config inside the main XO vm. I can also add NFS remotes trom the remote site to the imported proxy and the remotes seem to work fine (the test completes ok). I can also see the remote mounted on the proxy.
The problem appears whenever I try to make a backup. Every time it instantly fails with the message bellow.

{
  "code": -32000,
  "message": "unknown error from the peer"
}

I tried to debug the message but can't track down the reason. Any help is greatly appreciated!

**Comment by bogdantomasciuc** [comment]
The install is pure. Nothing is touched except i added in the config toml hostname = '0.0.0.0' fot ipv4 traffic. My router blocks ipv6.

**Comment by ronivay** [comment]
Hi,

Sorry for delay on this. Looks like bypassing the license check isn't anymore possible without modifying the code (which i don't want to do). It fails because it attempts to connect to updater, which does the license check. Something that runs only in official XOA. I've been trying to figure out why this change was done and if there's any proper way around it. Will get back to this once i have more information.

**Comment by ronivay** [comment]
Yeah got a confirmation that it isn't possible to run proxy without license check anymore without touching the code. Hopefully there will soon be a real documented procedure how to use proxy with "from sources" XO installations but until then this is were we're at.

Let's see if i can implement the minor source code change. Even though i'm against editing the source code with this script, but it's the only way to get this working currently.

**Comment by ronivay** [comment]
There's a workaround now in place. Just run proxy update with xo-install.sh against your existing proxy installation and it should work again. Let me know how it goes.

**Comment by bogdantomasciuc** [comment]
Works splendid! Great job! Thank you!
