### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by young-chap** [ronivay/XenOrchestraInstallerUpdater#114]
OS Version: ubuntu server 20
Node.js version: 14.19.1
Yarn version 1.22.18

Server specs
2 vCPUs
4GB RAM

Issue
Clean installs work, but the update of existing install fails with an error "line 703: CONFIGUPDATE: unbound variable"

**Comment by young-chap** [comment]
Hello, 

I downloaded a new version a few minutes ago and still get an error, this time on line 733.

1. Install
2. Update
3. Rollback
4. Install proxy
5. Update proxy
6. Exit

: 2

[info] Checking current node.js version

[ok] node.js version already on 14, checking updates

[info] Fetching Xen Orchestra source code

[info] Creating install directory: /opt/xo/xo-builds/xen-orchestra-202204020007

[info] Updating Xen Orchestra from '68c4fac3a' to 'f5b7c5920'

[ok] Shutting down xo-server

[info] No 3rd party plugins to install

[info] xo-server and xo-web build takes quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[info] No plugins to install

[info] Fixing binary path in systemd service configuration file
[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Replacing systemd service configuration file
[info] Reloading systemd configuration
./xo-install2.sh: line 773: CONFIGUPDATE: unbound variable

**Comment by ronivay** [comment]
Hi,

Thanks. `CONFIGUPDATE` was missing a default value. This is fixed now. 
You probably have a bit older `xo-install.cfg` so this was missing, hence the unbound variable error.
