### ISSUE TITLE
Continous Replication Error

### ISSUE THREAD

**Issue by zafarasyed** [ronivay/XenOrchestraInstallerUpdater#115]
**OS Version**:
Debian 11
**Node.js version**: node -v
v14.19.1
**Yarn version**: yarn -v
1.22.18

**Server specs**
4 core 4gb RAM

**Issue**
describe the issue and what task you were running (update, install)
The installation work fine. Everything works as expected except when you try to do continous replication to either SR or Local device.
Continuous replication fails
VDI_IO_ERROR(Device I/O errors)

I have done some research online wasn't able to find a solution oliverlambert one of the developer suggested at one of the forum that if a script was used then the issue should be open here.

Please assist. Thanks in advance.

**Comment by ronivay** [comment]
Hi,

Yes, it's a best practice you should follow when using 3rd party script to report issue here first so we can determine if issue is related to installation method or XO itself.

I don't see this being an issue related to this installation script but something else. What XCP-ng/XenServer version are you running? I can see some old reports about same issue which was fixed by adding `guessVhdSizeOnImport = true` to xo-server configuration, but that has been the default for quite some time in XOA and from sources installations.

**Comment by zafarasyed** [comment]
Hi, 
Thanks for getting back so quickly. Yes I came accross that forum post also where guessVhdSizeOnImport is set to true. In my case it is set to true.

I am running 
XCP-ng 8.2.1
xen orchestra (xo-server 5.90.2) (xo-web 5.95.0) commit ef819. I actually just upgraded too using the script

Also just to let you know I installed the xo-server using the official manual instruction to install the full opensource version and I had no issues with Continous replication to a SR. This tells me there is some configuration or something using the script that might have issues. 

[2022-04-08T07_52_53.166Z - backup NG.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8456776/2022-04-08T07_52_53.166Z.-.backup.NG.log)

let me know how to proceed.
Thanks.

**Comment by ronivay** [comment]
Okay, thank you. That indeed indicates there's something wrong if manual installation worked out fine. Just to double check, you did that installation to another VM with same OS etc, right? Did you have node version 16 (the latest LTS) with that? Not much i can think that would be different when doing manual installation but `xo-install.sh` doesn't yet default to node 16 (which it probably should already). Could you test if upgrade makes any difference? You can do it either manually or edit `xo-install.sh` and change line:

`NODEVERSION="14"` -> `NODEVERSION="16"`

Run update with xo-install.sh (it will upgrade your node version). Might be best to also run forced update for XO and see if it makes any difference.

**Comment by zafarasyed** [comment]
Hi,
Yes I created a new vm with the same os version. I have nodejs version 16.14.2 and yarn version of 1.22.18. 
Upon checking the xo-install.sh i discovered that the script had node version 14 installed. So I change it to 16 and run the script again to update. After update and reboot the result is still the same. The error is still present. 

Anything else you can think of that I can try. Thank you.

**Comment by ronivay** [comment]
Hi,

Okay, thanks for testing that out. Can't really think of anything else, the core installation procedure that script does is essentially the same as how it's described in official documentation. The default configuration file is edited slightly depending on options you have in `xo-install.cfg` but that's about it. You can always get the same `config.toml` file from your manually built XO VM and replace the one script created (most likely in `/root/.config/xo-server/config.toml`) to rule that out as well. As said, i'm still unable to reproduce this so little bit guessing what might be different with your environment.

**Comment by ronivay** [comment]
Have you had a change to do any further testing/debugging with this?
