### ISSUE TITLE
Add option to serve over HTTPS

### ISSUE THREAD

**Issue by tymcauley** [ronivay/XenOrchestraInstallerUpdater#12]
I recently started serving my own Xen Orchestra web interface over HTTPS, and figured that other people would probably like that option too. I did all the configuration using `xo-install.sh`, and this is basically what my changes look like:

```
diff --git a/xo-install.sh b/xo-install.sh
index 716c2a7..1579c3e 100755
--- a/xo-install.sh
+++ b/xo-install.sh
@@ -12,7 +12,14 @@
 #XOUSER="node"

 # Port number where xen-orchestra service is bound
-PORT="80"
+PORT="443"
+
+# Protocol to use for webserver.
+PROTOCOL="https"
+
+# HTTPS setup.
+PATH_TO_HTTPS_CERT="PATH_TO_X509_CERTIFICATE"
+PATH_TO_HTTPS_KEY="PATH_TO_X509_PRIVATE_KEY"

 # Base dir for installation and future updates
 INSTALLDIR="/etc/xo"
@@ -320,6 +327,14 @@ function InstallXO {
                sleep 2
        fi

+       if [[ "$PROTOCOL" == "https" ]]; then
+               echo "Enabling HTTPS in xo-server configuration file"
+               sed -i "s%#   cert: '.\/certificate.pem'%  cert: '$PATH_TO_HTTPS_CERT'%" $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-server/sample.config.yaml
+               sed -i "s%#   key: '.\/key.pem'%  key: '$PATH_TO_HTTPS_KEY'%" $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-server/sample.config.yaml
+               sed -i "s/#redirectToHttps/redirectToHttps/" $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-server/sample.config.yaml
+               sleep 2
+       fi
+
        echo "Activating modified configuration file"
        mv $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-server/sample.config.yaml $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-server/.xo-server.yaml

@@ -363,13 +378,13 @@ function InstallXO {
        set +x

        timeout 60 bash <<-"EOF"
-               while [[ -z $(journalctl -u xo-server | sed -n 'H; /Starting XO Server/h; ${g;p;}' | grep "http:\/\/\[::\]:$PORT") ]]; do
+               while [[ -z $(journalctl -u xo-server | sed -n 'H; /Starting XO Server/h; ${g;p;}' | grep "$PROTOCOL:\/\/\[::\]:$PORT") ]]; do
                        echo "waiting port to be open"
                        sleep 10
                done
        EOF

-       if [[ $(journalctl -u xo-server | sed -n 'H; /Starting XO Server/h; ${g;p;}' | grep "http:\/\/\[::\]:$PORT") ]]; then
+       if [[ $(journalctl -u xo-server | sed -n 'H; /Starting XO Server/h; ${g;p;}' | grep "$PROTOCOL:\/\/\[::\]:$PORT") ]]; then
                echo
                echo "WebUI started in port $PORT"
                echo "Default username: admin@admin.net password: admin"
```

This could certainly go for some improvements. The main one I can think of is not having to separately set the `PROTOCOL` variable. The basic issue is figuring out how to tell if the user wants to serve the page over HTTPS, since they're allowed to set the `PORT` to whatever they want. I'm open to suggestions on how to tackle that one.

One other issue: After I made these changes, the `xo-server` log now says this upon startup:

```
Web server listening on https://[::]:443
```

So we can't use `grep "http:\/\/\[::\]:$PORT"` to check if the server is running. I used the `PROTOCOL` variable in my implementation, but that doesn't seem necessary. Perhaps a better solution would be `grep "https\{0,1\}:\/\/\[::\]:$PORT"`, which will match both `http` and `https`?

Anyway, feedback is welcome, and I can put together a PR once this is figured out.

PS: For those of you using Let's Encrypt certificates, you should set the HTTPS configuration variables in the above script as follows:

```
PATH_TO_HTTPS_CERT="/etc/letsencrypt/live/YOUR_DOMAIN_NAME/fullchain.pem"
PATH_TO_HTTPS_KEY="/etc/letsencrypt/live/YOUR_DOMAIN_NAME/privkey.pem"
```

**Comment by ronivay** [comment]
Hi,

Thanks for suggestion. I intenionally never implemented any option for HTTPS support. Reverse proxy is the way to go IMO.  If you think this is useful, i can take a look at it at some point for sure.

**Comment by tymcauley** [comment]
Interesting, I'm not familiar with using a reverse proxy. Well, this feature is definitely useful for me, not sure how many others are interested though. I would guess it has reasonable traction since there's a [section of the XO documentation on setting it up](https://xen-orchestra.com/docs/configuration.html#https). Hard to know though.

Anyway, if this looks interesting to you, let me know and I can put together a PR for it.

**Comment by ronivay** [comment]
fixed in PR https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/13
