### ISSUE TITLE
./xo-install.sh --update fails

### ISSUE THREAD

**Issue by osuno1** [ronivay/XenOrchestraInstallerUpdater#120]
**Issue**
Using --update, the attached reported in the log (The engine "node" is incompatible with this module.  Expected version ">=14.18". Got "14.17.2".  I'm not sure it is really a bug or not, or something that is wrong with my install.  Please let me know your thoughts and if there is something else I need to do.

**Installation logfile**
Attach complete log as a file. 
[xo-install-202204301457.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8597174/xo-install-202204301457.log)

**Comment by ronivay** [comment]
Hi,

You could start by upgrading your xo-install.sh to newest version and retry update. Your version is from july 2021. Just `git pull` inside XenOrchestraInstallerUpdater directory, assuming you used git clone to get it in the first place. Newer version of script will also autoupdate itself in the future for you.

**Comment by osuno1** [comment]
Excellent.  Thanks for the response!  Obviously wasn't an issue.

**Comment by ronivay** [comment]
Awesome 👍

**Comment by osuno1** [comment]
Of course it worked just like you said and I appreciate the help very
much.  Thanks for even creating this and continuing to help newbies like
me!  And thanks for closing out the "issue".  I didn't know how else to
communicate to you the help needed because I knew it wasn't really an
"issue".

Thanks again!
