### ISSUE TITLE
using latest version of script, installing proxy succeeds, proxy running but not visible and cannot use it

### ISSUE THREAD

**Issue by damjankumin** [ronivay/XenOrchestraInstallerUpdater#121]
**OS Version**: Ubuntu 20.04
**Node.js version**: 16.14.2
**Yarn version**: 1.22.18

**Server specs**
Single CPU with 20 cores, 256GB RAM

**Issue**
Using the script with option 4 - install proxy, no fails, script succeeds, showing that it is installed, checking service showing running but in the XOC there is no proxy shown to be selected or be usable. The only thing I noticed it is listening on ipv6 which is not used in the environment - perhaps I can change that config?

**Installation logfile**
I attached SC as I have no SSH access currently
<img width="1009" alt="Screenshot 2022-05-02 at 16 05 17" src="https://user-images.githubusercontent.com/21099756/166247659-72d95db3-f43e-4c94-b485-077a82e5c992.png">
<img width="1018" alt="Screenshot 2022-05-02 at 16 07 13" src="https://user-images.githubusercontent.com/21099756/166247857-0c992eff-df03-4020-b564-5934b533d5e6.png">

**Comment by ronivay** [comment]
Based on script output, it looks like you've already ran proxy installation at some point, correct? Script will output a piece of json when it creates proxy configuration for the first time, this json needs to be imported into XO (as explained in readme) for the proxy to appear. If config already exists, this information is not printed again (as seen in your screenshot). If you need to recreate that config, remove existing from `/root/.config/xo-proxy/config.toml` and run proxy install with xo-install.sh again.

Also note that it doesnt give much benefit to run proxy on a same server with XO. The whole idea is to offload backup jobs away from XO server.

**Comment by damjankumin** [comment]
you are correct, it is running on the same server - it is proofing at this stage if the backup solution will work with storage, but that currently does not matter, I just wanted to make it work. Also, I forgot the JSON the second time around, will import the config right now. Also, I am concerned about this listening only on ipv6... will keep updates here directly as it unfolds, currently working on import...

**Comment by damjankumin** [comment]
success, it is working now - I deleted cached config from the root folder and now it is up. Thank you for reminding me of that!

**Comment by ronivay** [comment]
Great 👍

It should listen to IPv4 as well even though log output could be interpreted otherwise.
