### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ccict** [ronivay/XenOrchestraInstallerUpdater#122]
Ubuntu 20.04.3 LTS (Fresh Install)

**Server specs**
4x CPU 8GB RAM

**Issue**
running xo-install.sh as root, selecting option 1

**Installation logfile**
+ node -v 2>/dev/null| grep -Eo '[0-9.]+' | cut -d'.' -f1
16
+ command -v yarn
/usr/bin/yarn
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
**+ cd "/opt/xo/xo-src/xen-orchestra" && git pull --ff-only**
fatal: not a git repository (or any of the parent directories): .git

**Comment by ronivay** [comment]
Was this the very first attempt or did you have some earlier run that failed or have you possibly cancelled script execution by hand before? Can't think of any other situations where that directory could be empty/missing .git directory.

Anyway you should be able to fix this by removing `/opt/xo/xo-src` and run install again.

**Comment by ccict** [comment]
1st attempt, (not my 1st use of your script - keep it up!!)

I didn't end it, I have deleted the directory and just " Running Installation" now - will update.

**Comment by ccict** [comment]
All working now, I guess was me, thanks for your support and continued dev.

**Comment by ronivay** [comment]
Great. Yeah hard to say what happened but somehow that XO sources directory was left empty or missed some data. Haven't seen this before so let's assume it was a one time fail. I shall debug more if it happens again for someone.
