### ISSUE TITLE
What is the Debian VM user name and password?

### ISSUE THREAD

**Issue by tiagopascal** [ronivay/XenOrchestraInstallerUpdater#123]
**OS Version**: Debian 11
**Node.js version**: node -v
**Yarn version**: yarn -v

**Server specs**
amount of vCPUs and RAM on the machine where you attempt to install

**Issue**
After imported Debian VM on XCP, I can access the web interface with no issue. What I would also like to do is to be able to login on the VM. I tried user name xoa and pass xoa and it does not login.

**Installation logfile**
Attach complete log as a file.

**Comment by ronivay** [comment]
Hi,

from readme:

```
SSH is accessible with username xo with password xopass
```

import script also prints this information after VM has started.
