### ISSUE TITLE
xo-ce image issue for xcp-ng

### ISSUE THREAD

**Issue by lemonsml** [ronivay/XenOrchestraInstallerUpdater#124]
https://xcp-ng.org/forum/topic/5865/xoce-internal_error-while-trying-to-create-vm/37

There has been a pretty breaking bug (above) in the vatesfr/xen-orchestra repo that seems to be persistent in the current image used by xo-vm-import.sh. It doesn't allow for the creation of VMs via XO. I'm trying to get a new VM running inside of your current xo-ce image (2022-05-14), and I'm coming across the same issue. I noticed that the latest build for the xo-ce was on 2022-05-14, but the bug was fixed after that build.

I then tried the next logical thing which is to clone your repo and use the xo.install.sh, but i get a notice that i shouldn't try to run install on xcp-ng/xenserver host, and to use the xo-vm-import.sh instead, which is installing the same image.

I'm wondering if we need to wait another week for an updated image, or if a new image could be built so that I can create VMs again through xo-ce.

Other than that, I've been enjoying this tool set!

**Comment by ronivay** [comment]
Hi,

I'll build and push a new image to fix this. In the meanwhile you can fix your existing imported VM by simply updating XO inside of it, which you should do occasionally anyway. Access the imported VM with SSH using default credentials (assuming you didn't change them yet) `xo/xopass` and run `/opt/XenOrchestraInstallerUpdater/xo-install.sh --update`

**Comment by ronivay** [comment]
Image is now updated. I suggest you practice the above mentioned method instead of importing new VM, as that's the proper course of action for future updates anyway once VM is imported.

Will close this for now. Let me know if you encounter any more issues.

**Comment by lemonsml** [comment]
... not sure why i didn't think of that........ thanks anyways!
