### ISSUE TITLE
AUTOCERT="true" doesn't seem to be working

### ISSUE THREAD

**Issue by Doonga** [ronivay/XenOrchestraInstallerUpdater#130]
**OS Version**: Ubuntu 22.04
**Node.js version**: v16.15.1
**Yarn version**: 1.22.19

**Server specs**
2vCPU 4GB RAM

**Issue**
On initial install, I set up xo-install.cfg as per the wiki for auto generated certificates, at the end of the install the certificate and key were not created and xo-server failed to start. I manually created them and ran an update which ended up working fine. I'm also using a non-root user if that matters.

**Installation logfile**
Attach complete log as a file. 
[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8958791/xo-install.log)

**Comment by Doonga** [comment]
Ok fair enough, it's not a huge deal to create my own anyway. Thanks!

**Comment by ronivay** [comment]
Looked into this a bit. Only sane option would've been to just use filenames without path in sample config for cert/key, that would cause XO to write cert/key to installation directory. That would cause it to recreate certificate after every update which would then introduce a new warning in browser etc so probably not the best idea. Decided to just add a mention to wikipage about permissions when using non-root user.
