### ISSUE TITLE
Issue with Username & password on prebuilt image

### ISSUE THREAD

**Issue by seanlinder** [ronivay/XenOrchestraInstallerUpdater#134]
Issue with default Username & password on prebuilt image. The admin@admin.net & password admin do not seem to work on the current build.

**Comment by ronivay** [comment]
Hi,

Looks like there was a bug with recent changes related to redis in xen orchestra master branch: https://github.com/vatesfr/xen-orchestra/commit/7418d9f6708c171c37ae3867ac4ccdeaf4b2b345

VM was built from commit before that fix. I'll push a new build.

**Comment by ronivay** [comment]
New image is now in place.

**Comment by ronivay** [comment]
Other bug should now be fixed in https://github.com/vatesfr/xen-orchestra/commit/d27b6bd49d1885b385f3488c78ce4ddc392a69e2. I'll push new image once more. Should be available within an hour or so.
