### ISSUE TITLE
Cannot access web UI after update

### ISSUE THREAD

**Issue by jsargent8789** [ronivay/XenOrchestraInstallerUpdater#135]
**OS Version**: Rocky Linux 9
**Node.js version**: node -v 16.16.0
**Yarn version**: yarn -v 1.22.19

**Issue**
describe the issue and what task you were running (update, install)
Cannot GET / thats what I got from the web UI

**Comment by ronivay** [comment]
Hi,

Xen Orchestra master branch changed their redis dependency from version 3.x to 4.x which seems to prefer `::1` as connection address when localhost is defined. Redis by default doesn't listen to v6 localhost address, but only 127.0.0.1. This causes xo-server to fail redis connection and therefore UI fails. I'll make a workaround for rhel distros on this.

For the time being you can fix this by modifying your xo-server.toml configuration, by default it is stored in `/root/.config/xo-server/config.toml`, find line `[redis]` and add this below it: `uri = 'redis://127.0.0.1:6379/0'` and run `systemctl restart xo-server`

**Comment by ronivay** [comment]
Note that there seems to be another bug related to same redis update: https://xcp-ng.org/forum/topic/6188/xo-hosed-on-new-update which i can't fix in this script unfortunately. For now i'd suggest staying below commit `36b94f745d7a678b60e393bd8f8377f17dcd681b`

**Comment by ronivay** [comment]
The other bug should be fixed now as well in https://github.com/vatesfr/xen-orchestra/commit/d27b6bd49d1885b385f3488c78ce4ddc392a69e2
