### ISSUE TITLE
Rocky Linux 9

### ISSUE THREAD

**Issue by jsargent8789** [ronivay/XenOrchestraInstallerUpdater#137]
describe what you would like to get implemented, why and how would this benefit everyone using this script
Any plans on supporting rocky Linux 9

**Comment by jsargent8789** [comment]
#138 I made pull request for the change needed to support the new version of rocky linux 9. I did test it and made sure it installed just fine with rocky linux 9 and it does

**Comment by ronivay** [comment]
Hi,

Thank you. PR merged :)
