### ISSUE TITLE
Please Add Linux Mint to be supported in script

### ISSUE THREAD

**Issue by PrivacyOsint2** [ronivay/XenOrchestraInstallerUpdater#141]
![mint](https://user-images.githubusercontent.com/93969855/185492872-ddc8624e-5201-4342-8c35-574eb84e1161.png)

Please add Linux Mint to this list. Not able to update from xo-server 5.93.1 && xo-web 5.96.0

I upgraded to latest version now.
Had the older script that still works but not sure how long tho. So please add Linux Mint. Thanks.

**Comment by ronivay** [comment]
Hi,

Linux Mint is geared more towards desktop use. XO is meant to be run on a server, preferably on a server dedicated to just that as readme says. Therefore i've no interest in supporting Mint. Goal for this project isn't to support all distros out there but a few which are the most popular ones.

Script has a way of ignoring OS check in the config. No guarantees it works, but you have the possibility to do so if you wish.

I'd suggest running the docker container in Mint instead.
