### ISSUE TITLE
XO Lite installation

### ISSUE THREAD

**Issue by rwjack** [ronivay/XenOrchestraInstallerUpdater#142]
Hey,

Any ideas on how to get XO Lite working?

https://xen-orchestra.com/blog/xen-orchestra-5-74/

![image](https://user-images.githubusercontent.com/59068073/187722185-645ab228-69c5-471f-8132-f7970e48d8aa.png)

Blog post says this ^, though the closest to getting to the page was to:
`wget https://lite.xen-orchestra.com/dist/ -O /opt/xo/xo-web/dist/xolite.html`

But it seems to be broken with a bunch of JS errors.
Was wondering if this is due to the XenOrchestraInstallerUpdater implementation, or is it from Vates side?

**Comment by ronivay** [comment]
Hi,

XO lite and XO are two completely separate things, you don’t run XO lite on top of your XO installation.

That command is supposed to be ran on your XCP-ng host where it’ll be ”hosted”.  It’s accessed from hosts ip-address. Think of it as sort of builtin lightweight mgmt ui.

**Comment by rwjack** [comment]
Oh, I didn't quite catch that one. Thanks for the clarification!
