### ISSUE TITLE
Possibility to update\install certain commit.

### ISSUE THREAD

**Issue by TristisOris** [ronivay/XenOrchestraInstallerUpdater#143]
requried for debugging when something is broken.
we modified script a bit to update 1by1 commit.

```
38 COMMITVER="${COMMITVER:-"4dc7575d5bed3851a800840897f1ae3e19f224b8"}"                                                                                                       
578 runcmd "cd \"$XO_SRC_DIR\" && git checkout -f "${COMMITVER}""
```

just a stupid manual mode, need to change commit name at COMMITVER, then remove /xo folder and run script to install build you need.

Would be nice if you can make this more interactive with startup menu and commit selection.

tldr: that long story begins here) why we need to check every commit. https://xcp-ng.org/forum/topic/6268/pool-is-connected-but-unknown-pool/16?_=1662127957809

**Comment by ronivay** [comment]
Hi,

Installing from specific commit is already supported. See BRANCH setting in `xo-install.cfg`

**Comment by TristisOris** [comment]
wow unexpected. That was very hidden option)
So can you make it more interactive please?

**Comment by ronivay** [comment]
What do you mean with interactive exactly? How?

**Comment by TristisOris** [comment]
same way as now implemented the update procedure, via menu. And add commit name not permanent inside script.

**Comment by ronivay** [comment]
Ok, i see. I don't get the point though. What benefit does it give over setting it in config? I only see it as confusing menu option.

**Comment by TristisOris** [comment]
Not a big benefit, just save a bit time if really need to check 5-10+ commits one by one. And you will not forget to rollback changes at code)
At least this feature not documented anywhere, or i can't find it.

**Comment by ronivay** [comment]
Okay. Yeah i don't see this being used very often (as it's for debugging really) and for that reason the menu option just seems wrong as you save maybe few seconds with it compared to changing it in the config file. Also easier to keep track what you installed last time as it's present in the config. There's no need to do rollbacks if you want to make installations from many different commits like this, each update is a completely separate installation (which makes the rollback option in menu available), using the same persistent data XO has saved previously.

I've done the exact same debug procedure as you did now, installing from multiple different commits one by one trying to pinpoint specific issue and tbh i've never missed such menu option :)

**Comment by TristisOris** [comment]
didn't check yet how rollback works, it say that it store onyl 3 checkpoints, or am i wrong?
anyway thanks. got it.

**Comment by ronivay** [comment]
It will list all installations you have (by date & time) and ask to choose one. Rollback itself is almost instant.

**Comment by ronivay** [comment]
Anyway, thanks for suggestion. I appreciate all of them even if i don’t always agree :) will definitely rethink this if there’s any similar request later on. 

Will close this now. If there’s anything to add, feel free to comment.
