### ISSUE TITLE
Suggestion for document

### ISSUE THREAD

**Issue by sluflyer06** [ronivay/XenOrchestraInstallerUpdater#144]
Might I suggest on the main git page where you describe how to use your amazing work, you put the path of the XenOrchestraInstallerUpdater for reference for newbies.  Thanks for all you do!

**Comment by ronivay** [comment]
Hi,

i don’t quite understand what you mean. What path? You clone this repo to whatever directory you want to, location doesn’t really matter and therefore isn’t documented.
