### ISSUE TITLE
Remove Disclaimer & top warning

### ISSUE THREAD

**Issue by anndix** [ronivay/XenOrchestraInstallerUpdater#147]
Hi,

I am trying to use this in my small production environment with 2 servers. Is there a way to remove the popup warning and top banner ?

`Xen Orchestra from the sources

You are using XO from the sources! That's great for a personal/non-profit usage.

If you are a company, it's better to use it with our appliance + pro support included: [XOA (turnkey appliance)](https://xen-orchestra.com/#!/xoa?pk_campaign=xoa_source_upgrade&pk_kwd=ossmodal)

This version is not bundled with any support nor updates. Use it with caution.`

I know you have mentioned no changes to xcp-ng sources is supported, however any guidance would be highly appreciated. 

Thanks

**Comment by olivierlambert** [comment]
Hi @anndix 

Please carefully read this section of XO official documentation: https://xen-orchestra.com/docs/installation.html#from-the-sources

**Comment by anndix** [comment]
Hi,

Thanks for sharing the link, and yes I have read it. I still would want to explore any way to remove the warning as its being used only internally on a small production environment of 2 servers, nothing complex, just few VMs running.

If there is no way, I wont pursue further.

Thanks

**Comment by olivierlambert** [comment]
If it's used internally, the banner won't cause any problem then :+1: 

Complex or not, if you care about your production infrastructure, you should care about the the project running it. Imagine if everyone does the same thing than you, we'll have 0 revenue and won't be able to deliver anything anymore, and the project will simply die.

**Comment by ronivay** [comment]
Hi,

Sure it's possible to remove the banner among other things since it's open source. Though i've no interest to do so here or give any tips for it, due to reasons mentioned by @olivierlambert above.

**Comment by anndix** [comment]
> If it's used internally, the banner won't cause any problem then 👍
> 
> Complex or not, if you care about your production infrastructure, you should care about the the project running it. Imagine if everyone does the same thing than you, we'll have 0 revenue and won't be able to deliver anything anymore, and the project will simply die.

Understood. Thanks for your time.

**Comment by anndix** [comment]
> Hi,
> 
> Sure it's possible to remove the banner among other things since it's open source. Though i've no interest to do so here or give any tips for it, due to reasons mentioned by @olivierlambert above.

Got it. Thanks
