### ISSUE TITLE
./xo-install.sh install fails

### ISSUE THREAD

**Issue by andcza** [ronivay/XenOrchestraInstallerUpdater#148]
**OS Version**: Debian 11.5

**Server specs**
8xCPU, 8GB RAM

**Issue**
running xo-install.sh as root, selecting option 1 on fresh Debian 11.5

**Installation logfile**

root@XO:~/XenOrchestraInstallerUpdater# ./xo-install.sh
-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Debian 11
Basedir: /opt/xo
User: root
Port: 443
HTTPS: true
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3
Node.js and yarn auto update: true

Errorlog is stored to /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202210121001 for debug purposes

...
-----------------------------------------

1. Install
2. Update
3. Rollback
4. Install proxy
5. Update proxy
6. Exit

: 1

[ok] Running apt-get update

[ok] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils, curl, ntfs-3g, libxml2-utils

[ok] Installing apt-transport-https and ca-certificates packages to support https repos

[ok] Debian 10/11, so installing gnupg also

[info] Checking current node.js version

[info] node.js version already on 16

[ok] Enabling and starting redis service

[ok] Enabling and starting rpcbind service

[info] Fetching Xen Orchestra source code

[fail] Something went wrong, exiting. Check /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202210121001 for more details and use rollback feature if needed

[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/9765562/xo-install.log)

**Comment by ronivay** [comment]
Hi,

Did you possibly ctrl+c some previous install attempt or did it fail before this attempt? Looks like the initial XO repository clone has failed or cancelled before anything was actually cloned.

`rm -rf /opt/xo/xo-src/xen-orchestra` and retry should fix this.

**Comment by andcza** [comment]
Now it's OK. Thanks.
