### ISSUE TITLE
sed: can't read

### ISSUE THREAD

**Issue by chevybeef** [ronivay/XenOrchestraInstallerUpdater#15]
Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
Removing /etc/xo/xo-builds/xen-orchestra-201914011650 because of failed installation.
cat xo-install.log
sed: can't read /etc/xo/xo-builds/xen-orchestra-201914011650/packages/xo-server/sample.config.yaml: No such file or directory

Linux debianzm 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Comment by ronivay** [comment]
Hi,

Thanks for reporting this. Xen-Orchestra sources seem to have changed from yaml to toml format. I’ll see what has actually changed and create a fix asap. Until then u can pull source from latest tagged xo-server release if u need a quick fix.

**Comment by chevybeef** [comment]
Hi, thanks for your script and for responding so quickly. I'm not in any particular rush so I think I'll just wait for your fix.

**Comment by ronivay** [comment]
Hi,

This is now fixed: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/3f20aca2c6a0db1890db757eb2cfabb41625bd1f

Support for .yaml is also kept since this .toml format is only in master branch currently.

**Comment by ronivay** [comment]
> Just a heads-up: The [3f20aca](https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/3f20aca2c6a0db1890db757eb2cfabb41625bd1f) mod worked for a fresh install, but failed for me on some attempts to update prior installs (using ubuntu 16.04). I haven't had a chance to examine it yet -- just happy to see the fresh install work -- but may have a chance to look a bit later.
> 
> Also, warning to users: The default behavior is to listen only on IPv6 if it is available. I don't recall if this was an issue before and I just forgot turning off IPv6. The quick fix to listen on IPv4 instead is to add "hostname = '0.0.0.0'" in the [[http.listen]] block of the config.toml file and then restart the service.
> 
> I appreciate your efforts! Learned about your project from Tom Lawrence, who did a youtube video showing an install with your project. Thanks!

Hmm weird. I didn't encounter any issues with the update myself so not sure what has happened here. If you have a change to debug it at some point, would be awesome. Not that big of a deal in my opinion though since fresh install worked and all future installations will have the new config format.

That IPv6 thing was a good catch, didn't pay attention to that. I think i might add an option to install config to disable IPv6 (add 0.0.0.0 as listen hostname). Thanks.

I've also seen some of Tom's videos on youtube, great stuff :)
