### ISSUE TITLE
Unable to update or install fresh

### ISSUE THREAD

**Issue by gregyski** [ronivay/XenOrchestraInstallerUpdater#153]
**OS Version**: Ubuntu 22.04 / Debian 11.5.0
**Node.js version**: v16.18.0
**Yarn version**: 1.22.19

**Server specs**
2 vCPU 3 GB RAM (woops)

**Issue**
Initially I tried to upgrade an existing installation on Ubuntu that had been upgraded before. When that was failing, I decided to start fresh assuming it was my end as I had had at least one failed upgrade due to disk space. So I setup a clean Debian 11.5 and installed using the sample config as-is. Both situations failed with the same error in the console and log:
```
[..] Running installation

[fail] Something went wrong, exiting. Check /home/_user_/XenOrchestraInstallerUpdater/logs/xo-install.log-202211031539 for more details and use rollback feature if needed
```
```
src/views/settings/SettingsView.vue(102,17): error TS2304: Cannot find name 'XO_LITE_VERSION'.
src/views/settings/SettingsView.vue(103,17): error TS2304: Cannot find name 'XO_LITE_GIT_HEAD'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "type-check" exited with 2.
* @xen-orchestra/lite:build − Error: 1
[15:43:55] Finished 'buildScripts' after 1.72 min
[15:43:55] Finished 'build' after 1.72 min
✖ 1
error Command failed with exit code 1.
```
I note now that I gave it less RAM than recommended. I suspect that isn't the problem here, but I can adjust it up to 4 if requested.

**Installation logfile**
[xo-install.log-202211031539.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/9932577/xo-install.log-202211031539.log)

**Comment by mjtbrady** [comment]
I have just encountered the same problem when attempting an upgrade on Debian 11.5.

I have 4GB RAM allocated to this VM, so that isn't the issue.

An upgrade worked yesterday on the same VM.

**Comment by njpacoma** [comment]
I have encountered this problem today as well. These are those items references
./@xen-orchestra/lite/src/views/settings/SettingsView.vue:const version = XO_LITE_VERSION;
./@xen-orchestra/lite/src/views/settings/SettingsView.vue:const gitHead = XO_LITE_GIT_HEAD;
./@xen-orchestra/lite/vite.config.ts:    XO_LITE_VERSION: JSON.stringify(process.env.npm_package_version),
./@xen-orchestra/lite/vite.config.ts:    XO_LITE_GIT_HEAD: JSON.stringify(process.env.GIT_HEAD),

I have not discovered a workaround for this.

**Comment by ronivay** [comment]
Indeed looks like a recent commit to XO master branch broke the build. There’s already at least one issue about it so let’s wait for a fix.

**Comment by mjtbrady** [comment]
It has been fixed for me.  I have just done a successful update.

**Comment by gregyski** [comment]
Agreed, it is now working fine for me. It looks like I just had some really poor timing.
