### ISSUE TITLE
xo-vm-import.sh error "VMImport: command not found"

### ISSUE THREAD

**Issue by ajoshuasmith** [ronivay/XenOrchestraInstallerUpdater#154]
**Server specs**

8vCPUs 
32GB

**Issue**
Attempting to use the xo-vm-import.sh script. 

After setting network settings for VM; recieves error:
`bash: line 243: VMImport: command not found`

![image](https://user-images.githubusercontent.com/78829059/200712004-7ec32c1d-dae1-419e-8611-85b58c9acde4.png)

Could be something I am doing as I did not see anybody else raise this issue or talk about it! Many thanks!

**Comment by ronivay** [comment]
Hi,

I'm unable to reproduce this. Doesn't make much sense that all the other functions in the script work, but the last one `VMImport` would be missing. Did you follow the instructions and execute:

`sudo bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-vm-import.sh)"` on your host or did you do something else?
