### ISSUE TITLE
An emulator required to run this VM failed to start

### ISSUE THREAD

**Issue by marleyjaffe** [ronivay/XenOrchestraInstallerUpdater#155]
**OS Version**: `XCP-ng 8.2.1`
**Node.js version**: node -v `command not found`
**Yarn version**: yarn -v `command not found`

**Server specs**
```
[00:07 xcp-ng-m ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    8
Core(s) per socket:    1
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
Stepping:              2
CPU MHz:               2399.970
BogoMIPS:              4799.94
Hypervisor vendor:     Xen
Virtualization type:   none
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
Flags:                 fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq est ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ssbd ibrs ibpb stibp
```

```
[00:09 xcp-ng-m ~]# free
              total        used        free      shared  buff/cache   available
Mem:        2492704      314620      874952       12180     1303132     2075848
Swap:       1048572           0     1048572
```

**Issue**
After running the prewritten curl `xo-vm-import.sh` command from the readme and answering the storage and network prompt's, I receive the following error lines. 

```
An emulator required to run this VM failed to start
vm: 7cfe4391-6955-cee0-7e5c-857afbb40f89 (xo-ce)
name: domid 8
msg: QMP failure at File "xc/device.ml", line 3328, characters 71-78
```

I don't see any mention of QMP or emulator in any previous issues in this repo or in the primary `vatesfr/xen-orchestra` repo. Please let me know if there is additional logging I can look at to determine this issues root cause.

**Comment by ronivay** [comment]
Hi,

Is this a fresh installation of xcp-ng and have you recently applied any patches before trying to import this XO VM? Do you have any other VMs running and can those be restarted without issues?

**Comment by marleyjaffe** [comment]
This is not a fresh install. I have had this setup running for a while using the XOA webdeployed VM. I have a config backup from that VM and I was hoping to get the community vm running and import my config to keep my preconfigured setup. I recently ran the updates through using that VM. I do have other VM's running but I can reboot them if necessary.

**Comment by ronivay** [comment]
If you've ran updates recently, you could rule out the possibility of missing toolstack restart being the cause here. `xe-toolstack-restart` on xcp-ng dom0.

**Comment by ronivay** [comment]
Why resume if it was halted? Try to ctrl+c that and run `xe vm-start` instead.

**Comment by marleyjaffe** [comment]
no response for `xe vm-start` after 15 min. I assume it should be fairly quick. is there a verbose option for these commands?

**Comment by ronivay** [comment]
I don’t think there is. Sounds like the xapi isn’t responding or something. Are you sure the patches you ran earlier didn’t have anything that’d require a reboot? The emulator error and now `xe` commands getting stuck after toolstack restart would kinda indicate there was and it can’t work properly until rebooted.

**Comment by marleyjaffe** [comment]
a system reboot seems to have fixed my issues. Thank you for the very prompt support!
