### ISSUE TITLE
Consider Adding Parameter for [logs.transport.syslog]

### ISSUE THREAD

**Issue by JSylvia007** [ronivay/XenOrchestraInstallerUpdater#165]
If possible, in the install script it would be cool to be able to set the `[logs.transport.syslog]` variable so that we don't have to manually add it to the config.toml after each update and then restart xo-server again.

It essentially ends up as a config.toml entry:

```
[logs.transport.syslog]
target = 'tcp://syslog.example.org:514'
```

**Comment by ronivay** [comment]
Hi,

Sure. Available in https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/167

Can you give it a spin before merge.

**Comment by JSylvia007** [comment]
Setting added correctly for me!
