### ISSUE TITLE
Node.js 18.x not supported on Ubuntu 18.04

### ISSUE THREAD

**Issue by ccict** [ronivay/XenOrchestraInstallerUpdater#168]
fresh install of ubuntu 18.04.
(i did try the 22.04.1 but that errored in another way (don't have log)
Anyway i know it worked with 18.04 so tried that, but still got stuck, SORRY !

`Hit:4 https://deb.nodesource.com/node_18.x bionic InRelease
Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:6 http://gb.archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:8 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
Fetched 300 kB in 1s (290 kB/s)
Reading package lists...
+ apt-get install -y yarn
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 110 not upgraded.
Need to get 893 kB of archives.
After this operation, 5,415 kB of additional disk space will be used.
Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.19-1 [893 kB]
Fetched 893 kB in 0s (2,599 kB/s)
Selecting previously unselected package yarn.
(Reading database ... 79730 files and directories currently installed.)
Preparing to unpack .../yarn_1.22.19-1_all.deb ...
Unpacking yarn (1.22.19-1) ...
Setting up yarn (1.22.19-1) ...
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
+ mkdir -p "/opt/xo"
+ mkdir "/opt/xo/xo-builds"
+ mkdir -p "/opt/xo/xo-src/xen-orchestra"
+ git clone "https://github.com/vatesfr/xen-orchestra" "/opt/xo/xo-src/xen-orchestra"
Cloning into '/opt/xo/xo-src/xen-orchestra'...
+ rm -rf "/opt/xo/xo-builds/xen-orchestra-202301192236"
+ cp -r "/opt/xo/xo-src/xen-orchestra" "/opt/xo/xo-builds/xen-orchestra-202301192236"
+ cd /opt/xo/xo-builds/xen-orchestra-202301192236 && git rev-parse HEAD
fe0cc2ebb93950424e1f04c6d3cefc1529e5a43a
+ cd /opt/xo/xo-builds/xen-orchestra-202301192236 && git rev-parse --short HEAD
fe0cc2ebb
+ cd .
Installing Xen Orchestra from branch: master - commit: fe0cc2ebb
+ cd /opt/xo/xo-builds/xen-orchestra-202301192236 && yarn && yarn build
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
+ rm -rf /opt/xo/xo-builds/xen-orchestra-202301192236
root@xooa:/opt/XenOrchestraInstallerUpdater#`

**Comment by ronivay** [comment]
Hi,

Seems that node.js 18.x isn't supported by Ubuntu 18.04 due to an older glibc version.

https://github.com/nodesource/distributions/issues/1392

I might've to just drop the support for Ubuntu 18.04 due to this. Newer OS should be used instead. Let's see if there will be any fix for that or is it just what it is.

If you have issues with newer Ubuntu, please copy the logs here.

**Comment by ccict** [comment]
I just looked into this now. I have my 22.04 server running back up, i'll get the error log from that and post here very shortly.

**Comment by ccict** [comment]
Get:18 http://gb.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [87.1 kB]
Get:19 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [786 kB]
Get:20 http://gb.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [136 kB]
Get:21 http://gb.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [2,448 B]
Get:22 http://gb.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [1,580 B]
Get:23 http://gb.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [9,460 B]
Get:24 http://gb.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [122 kB]
Get:25 http://gb.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [81.2 kB]
Get:26 http://gb.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [84.6 kB]
Get:27 http://gb.archive.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [972 B]
Reading package lists...
E: The repository 'file:/cdrom jammy Release' no longer has a Release file.
Adding component(s) 'universe' to all repositories.
+ apt-get update
Get:1 file:/cdrom jammy InRelease
Ign:1 file:/cdrom jammy InRelease
Get:2 file:/cdrom jammy Release
Err:2 file:/cdrom jammy Release
  File not found - /cdrom/dists/jammy/Release (2: No such file or directory)
Hit:3 http://gb.archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://gb.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://gb.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
E: The repository 'file:/cdrom jammy Release' no longer has a Release file.

**Comment by ronivay** [comment]
Okay, that is unrelated to the script. You reference to a install cd in the sources.list which isn't there anymore. Check your `/etc/apt/sources.list` and remove any cdrom references there. Once `apt update` doesn't give any error, the `xo-install.sh` should go through as well without issues.

**Comment by ccict** [comment]
yeh i just found this also and have removed. I will make sure it's all up to date again and run again.
was late when i raised last night !

**Comment by ccict** [comment]
Indeed that was correct.
I installed 22.04 without check it was on your supported list so jumped the gun and reverted to an older version and caused myself more issues :)

Thanks for supporting AND giving me the fix for an issue outside of your control 


[..] Running installation
[ok] Running installation
[ok] Installing plugins
[info] Installation successful. Enabling xo-server service to start on reboot

**Comment by rizaemet** [comment]
Hello. Just wanted to share for information purposes. I had the same problem on Ubuntu 18.04 server. I upgraded the server to Ubuntu 20.04 with the `do-release-upgrade` command. Then the command `xo-install.sh --update` worked without any problems.

**Comment by ronivay** [comment]
Ubuntu 18 support is now removed from this script. It'll reach end of standard support in the end of this month and doesn't look like the nodesource issue is being fixed so pointless to keep it here. Update to newer ubuntu is the correct path here.

Script can still be ran with disabling OS_CHECK (see readme and config) if needed.
