### ISSUE TITLE
Need to add "findmount" to sudoers

### ISSUE THREAD

**Issue by JSylvia007** [ronivay/XenOrchestraInstallerUpdater#171]
**OS Version**: Ubuntu 22.04
**Node.js version**: v18.13.0
**Yarn version**: 1.22.19

**Server specs**
Install works, this isn't a hardware issue.

**Issue**
Apparently a change needs to be made to the update script that will add `/usr/bin/findmnt` to `/etc/sudoers.d/xo-server-xouser`.  I recently updated to XO (commit #[bfa02](https://github.com/vatesfr/xen-orchestra/commit/bfa0282eccefd24b9aece03e016f3b3f98da4e7a)).  I had been using a previous commit (but I can't remember which one), and remotes worked just fine.  

I updated last night and I got an error when it tried to run a backup:

```
xo01 : Jan 30 09:36:45 : xouser : a password is required ; PWD=/opt/xo/xo-builds/xen-orchestra-202301292111/packages/xo-server ; USER=root ; COMMAND=/usr/bin/findmnt /opt/xo/mounts/d3563718-8bba-419c-bbe9-7243ff982b6d
```

I manually updated the `/etc/sudoers.d/xo-server-xouser` file and added `/usr/bin/findmnt`, then re-ran the metadata backup and it finished without issue.

**Installation logfile**
Attach complete log as a file.

**Comment by ronivay** [comment]
Hi,

Hmm interesting. Need to try to reproduce this. I see the official from sources documentation still doesn't mention anything about needing sudo permissions for `findmnt`: https://xen-orchestra.com/docs/installation.html#sudo

**Comment by ronivay** [comment]
Actually `findmnt` has been used for quite some time: https://github.com/vatesfr/xen-orchestra/pull/4003 so shouldn't be anything that was added recently.

**Comment by JSylvia007** [comment]
I wonder if it was just a one-time glitch.

I will have to do some experiments and let you know.

~Jake
--
Jacob D. Sylvia
Jake Sylvia's Consulting
430 Cole St.
Seekonk, MA 02771
Cell: (508) - 954 - 2536
EMail: ***@***.***
Web: http://www.jacobsylvia.com

**Comment by ronivay** [comment]
I wasn’t able to reproduce a situation where missing findmount root permissions would’ve caused other than logged error message. Remote was still mounted without issues. I guess it still makes sense to add it to sudoers file.

**Comment by JSylvia007** [comment]
It could truly have been a fluke.  I'm all for security first, so don't just make a change that was related to a ghost in my machine LOL.

**Comment by ronivay** [comment]
After reading the earlier mentioned PR in XO repository again and checking the code where `findmnt` command is executed, it is evident that it's executed in a same way as `mount` and `umount`, as in with sudo if it's defined in configuration. I'll report this to XO repo and fix it here if that is indeed by design.
