### ISSUE TITLE
missing stuff

### ISSUE THREAD

**Issue by skynett81** [ronivay/XenOrchestraInstallerUpdater#172]
i do get this error when i try to update the XO . 

error @xen-orchestra/vmware-explorer@0.0.3: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

i do use your  image

and how do i fix so it got more space then just 10G ?

**Comment by dsiminiuk** [comment]
I updated node.js from this https://stackoverflow.com/questions/8191459/how-do-i-update-node-js
and it solved the build issue.

**Comment by ronivay** [comment]
How are you running the update? xo-install.sh (preinstalled kn the image) should handle node update for you. Script logs would be nice if it doesn't do this for you.

Disk resize you need to do from xcp-ng dom0 with cli if you don't have any other management interface available for your host/pool.

**Comment by ronivay** [comment]
Hi,

If node was installed by the `xo-install.sh` script originally, it should also update to 18.x if you still run 16.x. If node was installed via some other means, it might override the binary location for package installed by the script from nodesource repository.
