### ISSUE TITLE
Console access to XVA VM

### ISSUE THREAD

**Issue by 0byt3** [ronivay/XenOrchestraInstallerUpdater#173]
First of all, thank you for the work you put into this automation. It is so great.
Second, I realize this feature is pretty minor and the use case is relatively low, but hoping it might be considered.

I think it would be great for the XVA that you use to import the Xen Orchestra VM to have serial console access enabled. If I find myself in a situation where I need to troubleshoot networking on the VM, but don't have SSH access, I could use the text console through the host CLI to gain access to Debian for troubleshooting.

It would also be convenient for automating more tasks after running your install script that does the import.

**Comment by ronivay** [comment]
Hi,

Serial console should already be available. Text console (`xe console uuid=<xxx>`) isn't.

Try the following on your dom0:

`xl vm-list`

`xl console <vm-ID>`
or
`xl console -t serial <vm-name>`

**Comment by ronivay** [comment]
I'm going to assume this is okay. At least i can access console fine with the above method so should be good. The text console is only available for full PV guests which aren't really used anymore nowadays.

If above doesn't work, please comment back here and we'll see.
