### ISSUE TITLE
Yarn install failing when updating to c8b29da67

### ISSUE THREAD

**Issue by InputObject2** [ronivay/XenOrchestraInstallerUpdater#174]
**OS Version**: Ubuntu 20.04
**Node.js version**: v18.14.2
**Yarn version**: 1.22.19

**Server specs**
2 vCPU, 4GB ram

**Issue**
Trying to update, the installation hangs at the ```yarn``` command on the line

```runcmd "cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME && yarn && yarn build"```

No real error output, log only shows:

```
Updating Xen Orchestra from 'cfa094f20' to 'c8b29da67'
+ cd /opt/xo/xo-builds/xen-orchestra-202302240505 && yarn && yarn build
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "EIO: i/o error, read".
info If you think this is a bug, please open a bug report with the information provided in "/opt/xo/xo-builds/xen-orchestra-202302240505/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I tried removing the xo-sources folder (so it would clone the repo again) but yarn seems to keep failing on the same package.
After a few failures, I added ```npm install``` just before the ```yarn``` command and it seemed to do the trick.

```
runcmd "cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME && npm install && yarn && yarn build"
```

Adding this command doesn't feel right but I could not get it to work without it. 
Any ideas?

**Comment by ronivay** [comment]
Hi,

Is this still happening? I can't seem to reproduce the error.
