### ISSUE TITLE
docker & NTFS support?

### ISSUE THREAD

**Issue by Miky028** [ronivay/XenOrchestraInstallerUpdater#175]
HOST TrueNAS-SCALE-22.02.4
Docker XO commit b63c4
xo-server 5.104.0
xo-web 5.105.0

**Issue**
Trying to restore file from NTFS partition.

**Installation logfile**
xo:api WARN admin | backupNg.listFiles(...) [213ms] =!> Error: Command failed: mount --options=loop,ro,norecovery,sizelimit=71571603456,offset=368050176 --source=/tmp/qfs18qcazn/vhd0 --target=/tmp/u1jfb36ljvk
mount: /tmp/u1jfb36ljvk: unknown filesystem type 'ntfs'.

___________________________________________________

HOST UNRAID Version: 6.9.2 
Docker XO commit 31f85 (tag 5.109.0)
xo-server 5.109.0
xo-web 5.111.0

**Issue**
Trying to restore file from NTFS partition.

**Installation logfile**
xo:api WARN admin | backupNg.listFiles(...) [367ms] =!> Error: Command failed: mount --options=loop,ro,norecovery,sizelimit=71571603456,offset=368050176 --source=/tmp/fk9v3yqexdp/vhd0 --target=/tmp/i32r5s4zroc
mount: /tmp/i32r5s4zroc: wrong fs type, bad option, bad superblock on /dev/loop4, missing codepage or helper program, or other error.

______________________________________________________

I'm certain that in some of previous version it was working.

**Comment by ronivay** [comment]
Could you please report this to correct repository: https://github.com/ronivay/xen-orchestra-docker
