### ISSUE TITLE
Mounting external backup strorage failed

### ISSUE THREAD

**Issue by prononext** [ronivay/XenOrchestraInstallerUpdater#176]
**OS Version**: Ubuntu 22
**Node.js version**:  18
**Yarn version**: latest

Hi ronivay, 

I am having problems with mounting external backup strorages:

 "shortMessage": "Command failed with exit code 1: mount -o domain=x -t cifs //x /run/xo-server/mounts/x",
  "command": "mount -o domain=x -t cifs //x\\backup/AP-VM-Backup /run/xo-server/mounts/x",
  "escapedCommand": "mount -o \"domain=x\" -t cifs \"//x\" \"/run/xo-server/mounts/x\"",
  "exitCode": 1,

Any Idea how to solve it?

Nice install! Thank you

**Comment by prononext** [comment]
Is seems like when setting the `XOUSER `other than root and making `USESUDE `and `GENSUDO `true it does not have the correct permission after that.

**Comment by ronivay** [comment]
Hi,

Sorry for a late reply on this. I haven't had much time lately to focus on this project. So just to confirm, this only happens when XO is running as non-privileged user?
