### ISSUE TITLE
[feature] Option to update to new version release

### ISSUE THREAD

**Issue by bnerickson** [ronivay/XenOrchestraInstallerUpdater#177]
This is an idea for a feature I might try to implement at some point in the future.  I'd like to automate the XOA update process, but don't want to update to (what I see as essentially) a nightly version every time I run the update.

I'd like the updater to intelligently determine whether the the currently running version of XOA is on an older version, and update to the the newest version's release commit.  XOA releases a new version on a monthly cadence, so that would correspond to a commit like this: https://github.com/vatesfr/xen-orchestra/commit/0f09240fb2b883205602fdbcffbcbb9ce301bf7e

Anyway, this would be easier to implement if the XOA team tagged releases (which it looks like they've stopped doing) or else actually issued releases; but they don't do that either.

**Comment by ronivay** [comment]
Hi,

I know what you're after and this has been requested before. Answer stays the same (not going to implement) and is explained more in detail on https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/117

**Comment by bnerickson** [comment]
Thanks for the heads up and reference.
