### ISSUE TITLE
sudo ./xo-install.sh --update  [fail] Only Debian 8/9/10 supported

### ISSUE THREAD

**Issue by rowie** [ronivay/XenOrchestraInstallerUpdater#179]
**OS Version**: Debian 11
**Node.js version**: v18.12.1

**Yarn version**: yarn -v

**Server specs**
2 Cores and 2GB of RAM

**Issue**
i run 
sudo ./xo-install.sh --update 

[fail] Only Debian 8/9/10 supported
after setting the:
OS_CHECK="false"
ARCH_CHECK="false"
in xo-install.cfg
the update runs as it should.

**Comment by ronivay** [comment]
Hey,

Logs should be inside XenOrchestraInstallerUpdater/logs (by default) directory. Could you send the logfile from this failed installation.
