### ISSUE TITLE
Log filled with messages about failed connection to xo-proxy licensing servers

### ISSUE THREAD

**Issue by bogdantomasciuc** [ronivay/XenOrchestraInstallerUpdater#181]
**OS Version**: Debian GNU/Linux 11 (bullseye)
**Node.js version**: v16.15.1
**Yarn version**: 1.22.19

**Server specs**
4 vCPUs and 8 GB RAM

**Issue**
This is not really an issue that is disruptive to work - more of a nuisance. After deploying a number of proxies I find that in the log is being flooded by constant error messages regarding failed connections to a licensing server. I presume that the proxy is trying to find out whether it is licensed or not and fails. This makes finding other logs very difficult. 

**Salmple logfile entries**

```
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.085Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [66ms] =!> [object Object]
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.109Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [108ms] =!> [object Object]
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.110Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [104ms] =!> [object Object]
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.116Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [129ms] =!> [object Object]
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.122Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [91ms] =!> [object Object]
Apr 03 11:01:12 xo xo-server[270711]: 2023-04-03T08:01:12.136Z xo:api WARN bogdan.tomasciuc@***** | proxy.getApplianceUpdaterState(...) [98ms] =!> [object Object]
``` 
These errors also appear in the UI in the logs section as:
![image](https://user-images.githubusercontent.com/23525491/229451865-50c82207-f6fc-48c5-9ce4-562e64a0630c.png)
or
![image](https://user-images.githubusercontent.com/23525491/229451997-2742d675-8b87-459b-a609-fd4c7b9a43be.png)

Perhaps these messages can be silenced somehow.

**Comment by olivierlambert** [comment]
Hi,

As you are using XOA, it's better to open a support ticket, especially for proxies :)

**Comment by bogdantomasciuc** [comment]
Hey, Olivier! Honored to hear from you!
I am using XO compiled from sources. Added proxy in a somewhat manual manner to store as adding proxy from the UI is not supported in sources version.

**Comment by bogdantomasciuc** [comment]
IMHO it really shouldn't be so hard to add a proxy to xo compiled from sources, really :). 
Both products are open and would get free feedback from the community.

**Comment by ronivay** [comment]
Hey,

Yeah there unfortunately isn't a "supported" way of running proxy from sources so it comes with some caveats. As mentioned in readme, the method used here is quite experimental since proxy is expecting certain things out of the box which are there in the appliance. I don't think i will try to change it much until there's hopefully some day a documented way to run it.

**Comment by bogdantomasciuc** [comment]
Hey. Thank you for the answer. I realize that since it is not documented it is difficult and shaky ground. Perhaps @olivierlambert will give a nod and gift the open source community a way to use proxies from sources. It is such an outstanding product and proxies really complete it. And, as I said before, opening proxies to source users would bring about at least testers and fresh ideas to the table. Not to mention potential new customers.

**Comment by bogdantomasciuc** [comment]
I will self-close the issue. It turned to a foss thing and its place is not here. Love both projects ❤️.

**Comment by olivierlambert** [comment]
@bogdantomasciuc no worries and I'm hearing you. It's just that we have not planned to invest our time into it, because it's a bit harder to make something that make sense with the current "DIY from the source thing" (it wasn't planned like this at the start and this will need to be crafted correctly). It's not that we don't want to, it's more a resource/prioritization thing.
