### ISSUE TITLE
Clean yarn cache after build

### ISSUE THREAD

**Issue by hoerup** [ronivay/XenOrchestraInstallerUpdater#182]
The yarn cache can accumulate several gigs of packages  (on my system it's saved in /usr/local/share/.cache/yarn/ )

Add an option to do a `yarn cache clean` after install is done

**Comment by ronivay** [comment]
This is a good idea indeed. Might slow down updates a bit but can be made optional in config. I'll look into this soonish.

**Comment by dsiminiuk** [comment]
@ronivay Only the first time. Then it won't take long between updates.

**Comment by hoerup** [comment]
The best would imho be if yarn could be configured to only cache the latest version of a package instead of accumulating all previously used versions - but that doesn't seem to be the case.  Nor is there any kind of LRU settings that can be used for auto-eviction.

So a optional post-install `yarn cache clean` would be the next-best thing to limit the space consumed by the cache.

**Comment by vmpr** [comment]
that would be a great feature! I just cleared my yarn cache as my server run out of space :)

**Comment by dsiminiuk** [comment]
I used a wrapper script to call the updater already, so I added just the yarn clear cache command at the end. It would be a "nice to have" if it were built in, but there are work-arounds to automate it. 

For example, this is the content of the email I get after an update. 

Checking current node.js version 
node.js version already on 18, checking updates 
Fetching Xen Orchestra source code 
Creating install directory: /etc/xo/xo-builds/xen- orchestra -202304290145 
Updating Xen Orchestra from 'c0465eb4d' to 'fd2c7c2fc' 
No 3rd party plugins to install 
Running installation 
Installing plugins 
Shutting down running xo-server 
Fixing binary path in systemd service configuration file 
Adding WorkingDirectory parameter to systemd service configuration file 
Replacing systemd service configuration file 
Reloading systemd configuration 
Fixing relative path to xo-web installation in xo-server configuration file 
Changing redis connection address in xo-server configuration file 
Activating modified configuration file 
Symlinking fresh xo-server install/update to /etc/xo/xo-server 
Symlinking fresh xo-web install/update to /etc/xo/xo-web 
Symlinking fresh xo-cli install/update to /etc/xo/xo-cli 
Symlinking xo-cli script to /usr/local/bin/xo-cli 
Starting xo-server... 
Update successful. Enabling xo-server service to start on reboot 
Removing old inactive installations after update. Leaving 2 latest 
Cleaning yarn cache... 
yarn cache v1.22.19 
success Cleared cache. 
Done in 11.45s. 
For changes in this commit see [ https://github.com/vatesfr/xen-orchestra/commit/fd2c7c2fc | https://github.com/vatesfr/xen-orchestra/commit/fd2c7c2fc ]

**Comment by ronivay** [comment]
`YARN_CACHE_CLEANUP` boolean config option now implemented which will run cleanup after an update if set to `true`. Defaults to `false`
