### ISSUE TITLE
Unable to start xo-proxy

### ISSUE THREAD

**Issue by fred974** [ronivay/XenOrchestraInstallerUpdater#187]
**OS Version**: Debian11
**Node.js version**:  v18.16.0
**Yarn version**: 1.22.19

**Server specs** 
2vCPU 4GB Ram 30GB HDD

**Issue**
We installed xp-proxy using option 4 from the xo-install.sh script. When the script ended, the service cannot start
`[info] Starting xo-proxy...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open

[fail] Installation completed, but looks like there was a problem when star
[xo-install.log-202305221238.txt](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/11531072/xo-install.log-202305221238.txt)
ting xo-proxy. Check /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202305221238 for more details

Control xo-proxy service with systemctl for stop/start/restart etc.`

**Installation logfile**
Attach complete log as a file. 

[xo-install.log-202305221238.txt](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/11531076/xo-install.log-202305221238.txt)

**Comment by ronivay** [comment]
```
2023-05-22T11:43:45.784Z xo:proxy:bootstrap WARN   Address already in use.
```

You already have something else listening to port 443 so xo-proxy can't start.

**Comment by fred974** [comment]
Hi @ronivay 

I just realise my mistake... I was trying to install xo-proxy on the same server as Xen Orchestra. I didn't realise xo-proxy needed to run in its own VM
https://xcp-ng.org/forum/topic/6647/attempting-open-source-proxy-resolved
