### ISSUE TITLE
Plugins are not present on Ubuntu 22.04 LTS with option PLUGINS set to all 

### ISSUE THREAD

**Issue by VGerris** [ronivay/XenOrchestraInstallerUpdater#194]
**Ubuntu 22.04**:
**v18.17.1**: node -v
**1.22.19**: yarn -v

**Server specs**
2 vCPUs and 3 Gb RAM 

**Issue**
Install with : 
\# (default) all plugins will be installed, including possible 3rd-party plugins if defined.
PLUGINS="all"

Running install in the VM, plugins set to all but no plugins are built or at least visible in the XOA built.

**Installation logfile**
Attach edcomplete log as a file.

**Comment by VGerris** [comment]
[xoinstalllog.txt](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/12366691/xoinstalllog.txt)

**Comment by ronivay** [comment]
They indeed should become visible with either install/update (the XO build part is essentially the same in both). Logs do indicate that all plugins would've been installed so not entirely sure what might be the root cause here, especially if it worked the second time.

**Comment by BSGalactica75** [comment]
I'm experiencing the same issue. I've not only tried the Ubuntu 22.04 install and update twice on two different VMs but also on a Debian 12 install.
