### ISSUE TITLE
Updating or Installing via Script Fails

### ISSUE THREAD

**Issue by adampoconnor** [ronivay/XenOrchestraInstallerUpdater#199]
**OS Version**: Debian 11
**Node.js version**: 18.17.1
**Yarn version**: 1.22.19

**Server specs**
2 CPUs with 4 GiB RAM

**Issue**
When running update on the pre-made image installed via the readme, or when trying to run install after cloning the git on Ubuntu 22, yarn fails with a timeout error. The VM has internet access, is able to apt upgrade without any issue, and speedtest-cli shows good internet speed and latency.

**Installation logfile**
I had to ZIP to attach. Log file shows essentially the same error on pre-made VM image or fresh Ubuntu Server 22 install.
[xo-install.zip](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/13217992/xo-install.zip)

**Comment by ronivay** [comment]
Hey,

Can you verify that you're actually able to access yarnpkg registry from within the VM? Run eq. `curl -I https://registry.yarnpkg.com/@babel/core/-/core-7.23.2.tgz`. If that does give a HTTP/200 response, then it's simply a slow connection and i can look into increasing the timeout with a config option. If you're not able to get a response, then you have a connectivity issue which i cannot fix.

**Comment by adampoconnor** [comment]
The curl command was successful with a 200 response.

**Comment by ronivay** [comment]
Hey,

I've now increased the default network timeout for yarn to 300seconds and it's also configurable with `YARN_NETWORK_TIMEOUT` parameter (in xo-install.cfg). Please give it a try.

**Comment by adampoconnor** [comment]
Since I’m using the image now, should I just delete the updater file and re-clone from here?

**Comment by ronivay** [comment]
No, just run it and it'll self-update.

**Comment by adampoconnor** [comment]
Updated the script and then set a custom timeout of 2,000,000 just for the sake of it. Unfortunately, no improvement. New log file looks basically identical to previous.

**Comment by ronivay** [comment]
Okay, then i'm afraid something in your environment is cutting the connection as you can reproduce the same behaviour on two different VMs and increasing yarn's own timeout doesn't help. I don't unfortunately have much tips to give how to debug this further as it can be very environment specific issue. Based on the data here it isn't related to the script itself.
