### ISSUE TITLE
Can't access Orchestra after build

### ISSUE THREAD

**Issue by bazzacad** [ronivay/XenOrchestraInstallerUpdater#20]
Hi,
I ran the script to build XO on CentOS 7 with a fresh minimal installation.
It said it was successful.
systemctl says xo-server is active & running.
But when I go to it's IP address in my browser I don't get anything.
I can ping the IP address from the same PC that I'm trying to browse from & I can access it via XCP-GP Center & SSH.
What am I missing?

**Comment by ronivay** [comment]
Hi,

Most likely a firewall issue. Check your iptables/firewalld that HTTP is allowed. Script doesn't touch those.

**Comment by bazzacad** [comment]
firewalld did the trick. Thanks for the help.

**Comment by ronivay** [comment]
Great! I’ll add a note about the firewall to the installation procedure.
