### ISSUE TITLE
Update failed - new install fails

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#208]
**OS Version**: Ubuntu 22.04
**Node.js version**: v18.13.0
**Yarn version**: 1.22.19

**Server specs**
2 CPU 4GB RAM VM running on VMware Workstation Pro 17
Currently Xen Orchestra, commit [51c11] Master, commit [5d472]

**Issue**
[..] Running installation
[fail] Something went wrong, exiting. Check /var/log/xo/xo-install.log-202402021302 for more details and use rollback feature if needed

I have a snapshot of the VM prior to removing /etc/xo/ and /root/XenOrchestrUpdaterInstaller/ to do another git clone.

**Installation logfile**
I had to add .log to the log file because the date is appended by default and that isn't a "file type".
[xo-install.log-202402021302.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/14144273/xo-install.log-202402021302.log)

**Comment by ronivay** [comment]
Hey,

Looks like the root cause is this:

```
error tshy@1.11.0: The engine "node" is incompatible with this module. Expected version "16 >=16.17 || 18 >=18.15.0 || >=20.6.1". Got "18.13.0"
```

Newest 18.x version is 18.19.0, so it seems your node is not updating for some reason.

**Comment by dsiminiuk** [comment]
Trying...
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

ssh login again as indicated...
nvm install 18.19.0

node -v
v18.19.0

./xo-install.sh
Update

[info] Updating Xen Orchestra from '51c11c15a' to '5d4723ec0'

[info] Running Installation

getting coffee, BRB. LOL.

Eureka!

"Your Xen Orchestra is up to date"
