### ISSUE TITLE
web interface inaccessible 

### ISSUE THREAD

**Issue by bazzybtec** [ronivay/XenOrchestraInstallerUpdater#209]
**OS Version**: Ubuntu 22.04
**Node.js version**: 18.19.0
**Yarn version**: 1.22.19

**Server specs**
2vcpu 2 core 6gb ram

**Issue**
I have run the script that completed successfully and provided the login details. however when i navigate to the ip address from either an external host or from the browser on the server itself i get 192.168.0.220 didn’t send any data.

I have tried this on both debian 12.5 and ubuntu 22.04 following this exactly
https://www.youtube.com/watch?v=fuS7tSOxcSo

as well as the instructions on this git repo

i have tried this process multiple times now.

**Installation logfile**
Attach complete log as a file. 

● xo-server.service - XO Server
     Loaded: loaded (/etc/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-02-14 14:21:40 UTC; 26min ago
   Main PID: 8538 (node)
      Tasks: 11 (limit: 9347)
     Memory: 122.8M
        CPU: 6.007s
     CGroup: /system.slice/xo-server.service
             └─8538 node /opt/xo/xo-server/dist/cli.mjs

Feb 14 14:21:41 xo xo-server[8538]: 2024-02-14T14:21:41.999Z xo:plugin INFO successfully regist>
Feb 14 14:21:41 xo xo-server[8538]: 2024-02-14T14:21:41.999Z xo:plugin INFO successfully regist>
Feb 14 14:21:41 xo xo-server[8538]: 2024-02-14T14:21:41.999Z xo:plugin INFO successfully regist>
Feb 14 14:21:41 xo xo-server[8538]: 2024-02-14T14:21:41.999Z xo:plugin INFO successfully regist>
Feb 14 14:21:44 xo xo-server[8538]: 2024-02-14T14:21:44.854Z xo:xo-server ERROR uncaught except>
Feb 14 14:21:44 xo xo-server[8538]:   error: TypeError: Cannot read properties of undefined (re>
Feb 14 14:21:44 xo xo-server[8538]:       at ReadFileContext.callback (/opt/xo/xo-builds/xen-or>
Feb 14 14:21:44 xo xo-server[8538]:       at FSReqCallback.readFileAfterOpen [as oncomplete] (n>
Feb 14 14:21:44 xo xo-server[8538]:       at FSReqCallback.callbackTrampoline (node:internal/as>
Feb 14 14:21:44 xo xo-server[8538]: }
[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/14281193/xo-install.log)

**Comment by ronivay** [comment]
Hey,

You might be hitting an issue where the xo-server is only listening to IPv6. Does your Ubuntu server have ipv6 enabled? Try disabling it and restarting xo-server service. If this is the case, there's a separate issue/feature request open to allow defining the listener address which i'm adding soon.

**Comment by bazzybtec** [comment]
I have disabled ipv6 and restarted xo-server with no success. there is no firewall enabled. This is a fresh install of ubuntu

**Comment by ronivay** [comment]
Ah okay, i guess i know what is happening. You're configuring the crt/key files for HTTPS but you have PORT still set to 80 in xo-install.cfg, which probably should be 443. It should work even now, but you'd need to access it with https://<ip-address>:80 URL.

**Comment by bazzybtec** [comment]
Thats it, it works with that :80 after it using https it works. i will redeploy correctly

**Comment by ronivay** [comment]
Great. I’m assuming the reinstall with correct port fixed this for good so closing.
