### ISSUE TITLE
const { delimiter } = require('path') error

### ISSUE THREAD

**Issue by infomatico** [ronivay/XenOrchestraInstallerUpdater#21]
Hello,

When you run the installation script, the below error occurs as soon as it enters the option:

> xo-server and xo-web build quite a while. Grab a cup of coffee and lay back
> 
> Running installation...S 

```
# cat xo-install.log 
/etc/xo/xo-builds/xen-orchestra-201922042329/scripts/run-script:3
const { delimiter } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
error Command failed with exit code 1.
```

**Comment by ronivay** [comment]
Hi,

Please try a tagged xen orchestra release instead. Seems that there's once again something in master branch that is broken.

so edit xo-install.cfg and change BRANCH variable from master to something like tags/xo-server-v5.39.0

**Comment by ronivay** [comment]
Let's reopen this if changing the source branch doesn't work.
