### ISSUE TITLE
Trying to Add syncHookSecret to config.toml

### ISSUE THREAD

**Issue by delgado23** [ronivay/XenOrchestraInstallerUpdater#211]
Hello,

I am trying to setup pre freeze and post thaw webhooks in Xen Orchestra. Per this [doc ](https://github.com/vatesfr/xen-orchestra/blob/master/%40xen-orchestra/xapi/docs/vm-sync-hook.md#configuration) I need to add the following to my xo-server config which I believe is config.toml.

`[xapiOptions]
syncHookSecret = 'unique long string to ensure the request comes from XO'
`
Whenever I add it to the config but then run the script to update my version of Xen it goes away. Is there a way to get this added to the config?

Thanks!

**Comment by ronivay** [comment]
Hey,

Yes there is. Change `CONFIGUPDATE` value to false in `xo-install.cfg` to prevent config from being rewritten.

**Comment by delgado23** [comment]
I will give that a try and report back. Thanks!

**Comment by delgado23** [comment]
Here is what I did. I am not sure if I did something wrong.

Set CONFIGUPDATE=false to false in xo-install.cfg.

Changed the below snippet in config.toml

Before:

```
[xapiOptions]
# The duration XO will wait for a host to be live before assuming it failed to
# restart
restartHostTimeout = '20 minutes'
maxUncoalescedVdis = 1
vdiExportConcurrency = 12
vmEvacuationConcurrency = 3
vmExportConcurrency = 2
vmSnapshotConcurrency = 2

poolMarkingInterval = '6 hours'
poolMarkingMaxAge = '48 hours'
poolMarkingPrefix = 'xo:clientInfo:'
```


After:

```
[xapiOptions]
# The duration XO will wait for a host to be live before assuming it failed to
# restart
restartHostTimeout = '20 minutes'
maxUncoalescedVdis = 1
vdiExportConcurrency = 12
vmEvacuationConcurrency = 3
vmExportConcurrency = 2
vmSnapshotConcurrency = 2

poolMarkingInterval = '6 hours'
poolMarkingMaxAge = '48 hours'
poolMarkingPrefix = 'xo:clientInfo:'
syncHookSecret = 'secretstring'

```
run update using xo-install.sh

The config has been reverted.

```
[xapiOptions]
# The duration XO will wait for a host to be live before assuming it failed to
# restart
restartHostTimeout = '20 minutes'
maxUncoalescedVdis = 1
vdiExportConcurrency = 12
vmEvacuationConcurrency = 3
vmExportConcurrency = 2
vmSnapshotConcurrency = 2

poolMarkingInterval = '6 hours'
poolMarkingMaxAge = '48 hours'
poolMarkingPrefix = 'xo:clientInfo:'

```
Thanks for you help,
Delgado

**Comment by ronivay** [comment]
Check that you're editing the correct config file in the first place. There's the path mentioned in comment above configupdate option. So assuming you haven't changed the the user in `xo-install.cfg`, the file is located in `/root/.config/xo-server/config.toml` which you should edit.

**Comment by delgado23** [comment]
Thanks Ronivay that looks like it did the trick. Feel free to close this ticket. Thank you for the help!
