### ISSUE TITLE
Is the VM image up to date?

### ISSUE THREAD

**Issue by shareefj** [ronivay/XenOrchestraInstallerUpdater#212]
Hey there,

I've just used your installation flow with the pre-built VM and am having issues within XO.  How recently was the VM built?  Just wondering if I should try to build from sources if it's out of date.

Thanks.

**Comment by ronivay** [comment]
Hey,

You can see the build date in repository readme. It was built last saturday so not old. Can you elaborate what kind of issues you have? You can always update the XO within the prebuilt VM as well with `/opt/XenOrchestraInstallerUpdater/xo-install.sh --update`

**Comment by shareefj** [comment]
Thanks for the info.

This issue: https://xcp-ng.org/forum/topic/8417/cannot-create-smb-iso-repository-on-new-xoa/21

Just wanted to be sure I had the latest which seems to be the case.
