### ISSUE TITLE
update for ubundu 19/debian10

### ISSUE THREAD

**Issue by kaloolu** [ronivay/XenOrchestraInstallerUpdater#22]
waiting update for ubundu 19/debian10

**Comment by ronivay** [comment]
Hi,

Debian 10 and Ubuntu 19 ship with nodejs version 10 which xen orchestra doesn't support. It needs to be removed and a hack to be added for version 8 to be installed. 

I've now added support for both distros including the nodejs tasks, but i've put it in experimental branch. You can check that out at:

https://github.com/ronivay/XenOrchestraInstallerUpdater/tree/experimental
