### ISSUE TITLE
[fail] Something went wrong

### ISSUE THREAD

**Issue by Kajetan321** [ronivay/XenOrchestraInstallerUpdater#222]
Hello, when executing:

`sudo /opt/XenOrchestraInstallerUpdater/xo-install.sh`

And selecting update I get:

`[info] Installing nodesource repository`

The system than hangs for a while and eventually returns:

`[fail] Something went wrong, exiting. Check /opt/XenOrchestraInstallerUpdater/logs/xo-install.log-202402271754 for more details and use rollback feature if needed`

The Log shows: 

`+ curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --batch --yes --dearmor -o /usr/share/keyrings/nodesource.gpg
curl: (28) Failed to connect to deb.nodesource.com port 443: Connection timed out
gpg: no valid OpenPGP data found.`

I used the `sudo bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-vm-import.sh)"` scrip[t to create the VM.

Please bare with me, I'm not a develop and I'm learning Github and XO.

**Comment by ronivay** [comment]
It seems that for some reason the server you're trying to install to can't connect to `https://deb.nodesource.com`. I'm able to access it at least now so unless it wasn't temporary down it's something specific to your environment and unfortunately i don't have much tips besides to check possible firewall etc.

**Comment by Kajetan321** [comment]
I started from scratch:

`[12:44 xcp-m83 ~]# sudo bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-vm-import.sh)"

Welcome. This script will import a preconfigured Debian 11 VM image which has Xen Orchestra installed using https://github.com/ronivay/XenOrchestraInstallerUpdater
You need at least 2vCPU/4GB/10GB disk free resources to import VM

Please report any issues to this github project

Which storage repository should the VM use?
default will attempt to use pool default SR

1) 18850841-5eb8-6b28-73ba-cae1c40af157
2) default
Pick a number. CTRL+C to exit: 2

Which network should the VM use?

1) 99b40169-8dab-6e9d-db96-23277b405b4a Pool-wide network associated with eth0
2) 84afdb15-9107-c49a-55fb-7fda844f3f2b Host internal management network
Pick a number. CTRL+C to exit: 1

Set network settings for VM. Leave IP-address as blank to use DHCP

IP address:

Downloading and importing XVA image...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1013M  100 1013M    0     0  20.1M      0  0:00:50  0:00:50 --:--:-- 11.3M

Import complete

Starting VM...
Waiting for VM to start and announce it got IP-address
Waiting for VM to start and announce it got IP-address
Waiting for VM to start and announce it got IP-address

VM Started successfully

You can access Xen Orchestra at https://172.22.1.71 and via SSH at 172.22.1.71
Default credentials for UI: admin@admin.net/admin
Default credentials for SSH: xo/xopass

Remember to change both passwords before putting VM to use!
`
Now I'm getting a slightly different error, but again it seems like a networking issue.
`+ apt-get update
Err:1 http://deb.debian.org/debian bullseye InRelease
  Cannot initiate the connection to debian.map.fastlydns.net:80 (151.101.126.132). - connect (101: Network is unreachable) Could not connect to debian.map.fastlydns.net:80 (2a04:4e42:1e::644), connection timed out Cannot initiate the connection to deb.debian.org:80 (151.101.126.132). - connect (101: Network is unreachable)
`
Any thoughts?

**Comment by ronivay** [comment]
Hey,

Similar as before, although this time it's not just the nodesource that's unreachable. So some sort of network connectivity issue from VM to the internet. None of it not really related to the install scripts here so i unfortunately can't help you much, i'd suggest heading over to xcp-ng forums for community assistance if you can't figure out the reason from your own network setup and infrastructure.

**Comment by eenturk** [comment]
I had the same problem and i can confirm that it was a network related issue not with the firewall. But my network use ipv6 so i think it tried to reach out with the ipv6 address instead of ipv4 which the domain that it tries to connect doesn't support. After disabling ipv6 on the Debian vm and running the script again it works like it should so maybe this helps?

**Comment by Kajetan321** [comment]
I was able to bypass the problem by not relying on DHCP to provide IP configuration.  I'm guessing that a static route that is handed out by our DHCP server is causing problems for the VM.  Weird thing is, this is the first host that has experienced this out of about 40 other hosts that we have.
