### ISSUE TITLE
Rollback to Specific commit...

### ISSUE THREAD

**Issue by RonO-EE** [ronivay/XenOrchestraInstallerUpdater#226]
Hey,

Apparently there is an issue with the latest versions of XOA with doing restores, and I need to rollback to commit c6451cf, to be able to restore a needed VM...

Any way to do that using your amazing scripts?

**Comment by ronivay** [comment]
Hey,

You can put that commit hash to `xo-install.cfg`’s `BRANCH` variable and run update to get to that specific commit. Remember to change that back to master once the issue is fixed so that future updates get you to latest version.

**Comment by RonO-EE** [comment]
That got it!!  Thanks....getting that restore saved me a ton of time... :)

**Comment by ronivay** [comment]
Happy to hear that :)
