### ISSUE TITLE
Backup jobs - Health check fails

### ISSUE THREAD

**Issue by michmoor0725** [ronivay/XenOrchestraInstallerUpdater#227]
**OS Version**: Ubuntu 22.04.4 LTS
**Node.js version**: node -v   v18.19.1
**Yarn version**: yarn -v   1.22.19

**Server specs**
amount of vCPUs and RAM on the machine where you attempt to install
4c/4G

**Issue**
Issue to summarize. Using latest commit, newly created backup jobs health checks fail due to Error: self-signed certificate
Problem described in the forums: https://xcp-ng.org/forum/topic/8618/restoring-from-backup-error-self-signed-certificate/29
FIX: Revert to commit 0ccfd

**Installation logfile**

Error: self-signed certificate
Start: Mar 24, 2024, 01:01:26 PM
End: Mar 24, 2024, 01:08:39 PM
Error: self-signed certificate
Start: Mar 24, 2024, 01:01:05 PM
End: Mar 24, 2024, 01:08:39 PM
Duration: 8 minutes
Error: self-signed certificate
Start: Mar 24, 2024, 01:00:42 PM
End: Mar 24, 2024, 01:08:39 PM
Duration: 8 minutes
Error: self-signed certificate
Type: delta

**Comment by ronivay** [comment]
Hey,

As older commit works fine, this seems to be an issue with XO itself and therefore not something I'm able to solve here. As there's already a forum thread open, I'm assuming this will be fixed by the devs sooner or later. Will keep this issue open until then, if anyone else is looking for a solution.

**Comment by ronivay** [comment]
This should be fixed afaik. Can you confirm that this issue is not present in latest commit?

**Comment by liora2k** [comment]
Yes , it was fixed .Appreciate the quick response LiorOn 26 Mar 2024, at 19:48, Roni Väyrynen ***@***.***> wrote:﻿
This should be fixed afaik. Can you confirm that this issue is not present in latest commit?

**Comment by ronivay** [comment]
Cheers. Will close this then :)
