### ISSUE TITLE
Issue with updating via script

### ISSUE THREAD

**Issue by Xaerioth** [ronivay/XenOrchestraInstallerUpdater#228]
**OS Version**:  Debian 10
**Node.js version**: 18.20.1
**Yarn version**: 1.22.19

**Server specs**
XCP-NG VM
8 CPU
8GB RAM
32GB Storage (5GB Used, 25GB Available per df -h command)

**Issue**
When running the script and selecting update via 2, it gives the following error log, even after a restart
[xo-install.log-202404061141.txt](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/14894970/xo-install.log-202404061141.txt)

**Installation logfile**
Attach complete log as a file.

**Comment by ronivay** [comment]
Hey,

This looks like some IPv6 connectivity issue towards registry.yarnpkg.com, unrelated to the script itself. Check the networking of that VM which you're trying to update. Might've also been some transient issue with yarnpkg registry itself.
