### ISSUE TITLE
Overrides in xo-server/config.toml

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#229]
This is not a bug really, it's ignorance on my part I am sure, so submitted it as a Feature request.

I am trying to set an override in /opt/xo/xo-server/config.toml for the following CI 
```
[xapiOptions]
# The duration XO will wait for a host to be live before assuming it failed to restart
restartHostTimeout = '20 minutes'
```
I want to increase the value to 30 minutes for my use case. I can edit the config.toml file but a new build from the sources reverts it to the default value.

"Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg"

I updated xo-install.conf
CONFIGUPDATE="false"

How do I get this timeout override to persist between builds?

**Comment by ronivay** [comment]
Hey,

You should add that `XapiOptions` section and the config parameter to the config file under `/root/.config/...` instead and not edit the default config file under /opt. The config you set in `xo-install.cfg` prevents that specific file from being overwritten.

**Comment by dsiminiuk** [comment]
OK then.

xo-install.conf now has;
CONFIGUPDATE="true"

/root/.config/xo-server/config.toml now has;
[xapiOptions]
restartHostTimeout='30 minutes'

Build...

Now in /opt/xo/xo-server/config.toml I see

[xapiOptions]
# The duration XO will wait for a host to be live before assuming it failed to
# restart
restartHostTimeout = '20 minutes'

:/

**Comment by ronivay** [comment]
Yeah that parameter in the config file under /opt won't change. The file under /root is an override and should take effect over the one under /opt

**Comment by dsiminiuk** [comment]
I edited my post while you were replying.

The [xapiOptions] section is no longer in /root/config/xo-server/config.toml

**Comment by ronivay** [comment]
Ah right, you should set the `CONFIGUPDATE` to false, not true.

**Comment by dsiminiuk** [comment]
I have added

[xapiOptions]
restartHostTimeout = '30 minutes'

back to the bottom of /root/.config/xo-server/config.toml

and changed xo-install.conf CONFIGUPDATE="false" to prevent the /root/.config... file above from being overridden.

Build...

restartHostTimeout = '30 minutes' is present in /root//config/xo-server/config.toml.

Now I need to wait for a new set of patches to be released to see if the rolling pool update will complete.

Thanks!

**Comment by dsiminiuk** [comment]
Got it working. Thank you
