### ISSUE TITLE
Several unmet peer dependency errors while updating to 05d975a63

### ISSUE THREAD

**Issue by dsampson01** [ronivay/XenOrchestraInstallerUpdater#230]
**OS Version**: Debian 11
**Node.js version**: v18.20.2
**Yarn version**: 1.22.19

**Server specs**
It's a standalone desktop system. xcp-ng is not installed on this machine but rather XOA CE is. 

**Issue**
Was trying to apply an update going from 42dc75e73 to 05d975a63. The update process encountered errors with unmet peer dependencies as listed in the log file below.

**Logfile**
Installation logfile: [xo-install.log-202404191543.txt](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/15046128/xo-install.log-202404191543.txt)

**Comment by dsampson01** [comment]
Came across this in the xcp-ng forum: https://xcp-ng.org/forum/topic/8314/xoce-warning-on-build

Basically it tells the poster to ignore the errors. But the script doesn't ignore these errors and automatically reverts to the previous configuration.

Another similar thread on the forum ends with no response from Julien: https://xcp-ng.org/forum/topic/7516/xoce-warning-on-build

What do we do?

**Comment by ronivay** [comment]
As long as the yarn process exits with exit code 0 (success), the script will ignore possible warnings. Here it clearly doesn't but output doesn't seem to show any error. Needs a bit more investigation why. I haven't had time to look into this unfortunately, will try to do so asap.

**Comment by ronivay** [comment]
No worries. Good that it works now 👍
