### ISSUE TITLE
Don't force xo-proxy port to 443

### ISSUE THREAD

**Issue by andrew64k** [ronivay/XenOrchestraInstallerUpdater#235]
**OS Version**: Debian 11
**Node.js version**: v18.20.2
**Yarn version**: 1.22.19

**Server specs**
2xCPU, 4G RAM

**Issue**
I have the port for proxy config is set to 4443 in both *xo-install.cfg* and *config.toml*
Install script *xo-install.sh* forces port to 443 for service start check if *xo-proxy* is used.

```
    if [[ "$XO_SVC" == "xo-proxy" ]]; then
        local PORT="443"
    fi
```

**Installation logfile**
```
[info] Starting xo-proxy...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
```

**Comment by ronivay** [comment]
Hi,

Yes this is on purpose. When adding proxy to XO, there is no option to define the port and it will always use 443.

**Comment by andrew64k** [comment]
On XO, for the ***Proxies*** page the ***Address*** is just ***remote.site.com:4443***.
Same idea for the ***Servers*** setting ***HTTP proxy URL*** is ***https://YourKey@remote.site.com:4443/***

In your ***xo-install.cfg*** I just use ***PORT="4443"*** and it ends up in ***.config/xo-proxy/config.toml*** as ***port = 4443***

**Comment by ronivay** [comment]
Okay, i need to give this a shot. For the XO proxy, it used to be hard coded to port 443 and was not configurable when adding proxy, hence the installation here forced it to port 443 too.
