### ISSUE TITLE
Centos7 Minimal Install

### ISSUE THREAD

**Issue by cdbessig** [ronivay/XenOrchestraInstallerUpdater#24]
Spun up a fresh centos 7 minimal install vm and ran the installer.  This is was I got:

`Errorlog is stored to ./xo-install.log for debug purposes
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 1

[ok] Installing node.jss

[ok] Installing yarnn

[ok] Installing epel-repoo

[ok] Installing libvhdi-tools from forensics repositoryy

[ok] Installing build dependencies, redis server, python, git, nfs-utilss

[ok] Enabling and starting redis servicee

[ok] Enabling and starting rpcbind servicee
[ok] Creating missing basedir to /etc/xoo
[ok] Creating missing xo-builds directory to /etc/xo/xo-buildss

[info] Fetching Xen Orchestra source code

Cloning into '/etc/xo/xo-src/xen-orchestra'...

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-201911101621
[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[...] Running installation[fail] Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
[fail] Removing /etc/xo/xo-builds/xen-orchestra-201911101621 because of failed installation.`

`[root@xoa XenOrchestraInstallerUpdater]# cat ./xo-install.log

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

/bin/sh: line 1: 15175 Killed                  yarn run clean
[16:24:08] 'buildScripts' errored after 21 s
[16:24:08] Error: Cannot find module 'themes' from '/etc/xo/xo-builds/xen-orchestra-201911101621/packages/xo-web/src/xo-app'
    at /etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /etc/xo/xo-builds/xen-orchestra-201911101621/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
[16:24:08] 'build' errored after 21 s
✖ 3
error Command failed with exit code 1.
[root@xoa XenOrchestraInstallerUpdater]#`

Any ideas?

**Comment by ronivay** [comment]
Hi,

Thanks for reporting. Sounds like there might be something wrong in the xen orchestra sources master branch currently. This has been the case multiple times in the past, since master is not consirered as stable, but works most of the time just fine and has latest features in it. In the meanwhile you can try to use a tagged release, so edit xo-install.cfg and change BRANCH from "master" to "tags/xo-server-v5.51.0" and re-run installation.

**Comment by cdbessig** [comment]
Thank for the reply!  I tried what you suggested but it left more erros:

`
HEAD is now at 0d8786f... feat(xo-server): 5.51.0

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

/bin/sh: line 1: 25818 Killed                  yarn run clean
xo-install.sh: line 262: 25568 Killed                  yarn build > /dev/null
{ Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:1165:24)
    at sync (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/mkdirp/index.js:68:14)
    at outputFileSync (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/output-file-sync/index.js:111:25)
    at /etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:114:43
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:74:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:76:194)
    at <anonymous> errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }
{ Error: ENOENT: no such file or directory, stat 'src/index.bench.js'
    at Object.fs.statSync (fs.js:948:11)
    at Object.chmod (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/util.js:72:47)
    at /etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:118:16
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:74:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-201911101733/node_modules/@babel/cli/lib/babel/dir.js:76:194)
    at <anonymous>
  errno: -2,
`

**Comment by ronivay** [comment]
Hi,

I'm not able to reproduce this with the master branch on a fresh centos7 vagrant VM. I'll try with the actual centos minimal installation also but so far i see no issues here.

Are you running with default xo-install.cfg ? Have you made any changes to the VM prior to using this script. Can you also list which node and yarn versions you have installed just in case.

**Comment by ronivay** [comment]
Not able to reproduce even with a CentOS7 VM with minimal installation running on xcp-ng. 

Let me know the details asked in prior message and let's see if we find a solution. Problem is in the xen orchestra build itself so pretty much all that could affect to it is node and yarn versions.

**Comment by cdbessig** [comment]
Is this helpful / expected:

```
[root@xoa xoa]# yarn --version
1.19.1
[root@xoa xoa]# npm --version
6.4.1
[root@xoa xoa]# node -v
v8.16.2

[root@xoa XenOrchestraInstallerUpdater]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@xoa xoa]#
```

```

From https://github.com/vatesfr/xen-orchestra
   3483e7d..541d90e  master     -> origin/master

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

✖ 3
error Command failed with exit code 1.
```

**Comment by cdbessig** [comment]
I believe I got to the root cause.  My Centos machine had 2GB ram with 0 swap.  I added a 2GB swap and the build was successful.

**Comment by ronivay** [comment]
Hi,

2GB should be enough for xo to run, but in this case seems not. 

Glad you found the solution! Shame that the error is so random in such case.
