### ISSUE TITLE
non-root install leaves user/.config owned by root

### ISSUE THREAD

**Issue by shbitsus** [ronivay/XenOrchestraInstallerUpdater#244]
**OS Version**: Debian 11.9 - Linux xo 5.10.0-30-amd64 #1 SMP Debian 5.10.218-1 (2024-06-01) x86_64 GNU/Linux
**Node.js version**: v20.14.0
**Yarn version**: 1.22.22

**Server specs**
(2) vCPU (Ryzen 9 7950X), 6GB

**Issue**
XO web UI is working fine.
I'm trying to use xo-clii.
Tried xo-cli register and it hung.  Then xo-cli unregister and it threw: 
[Error: EACCES: permission denied, mkdir '/home/brightonit/.config/xo-cli']
So I try mkdir ~/.config/xo-cli and get the same.
Then I find  .config  owner:group is root:root.
I installed xo-install.sh using sudo and .cfg XOUSER=brightonit
Two logs attached:  first failed for out of space on device, second appeared to finish w/o error.

**Installation logfile**

[xo-install.log-202406131534.log](https://github.com/user-attachments/files/15841375/xo-install.log-202406131534.log)
[xo-install.log-202406131610.log](https://github.com/user-attachments/files/15841377/xo-install.log-202406131610.log)

**Comment by ronivay** [comment]
This is now fixed. One caveat is that, if the directory was already created with wrong permissions before, you need to manually fix it. Fix is implemented in a way that if the directory doesn't exist, it'll be created with owner/group being what is defined in `XOUSER` config option. This directory is i by no means XO specific and can potentially contain other things too so being a bit conservative here to not overwrite any permissions that might've already been there.
