### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by robs007** [ronivay/XenOrchestraInstallerUpdater#246]
**OS Version**: Debian 12
**Node.js version**: node -v
**Yarn version**: yarn -v

**Server specs** 4 porc, 8 gig ram
amount of vCPUs and RAM on the machine where you attempt to install

**Issue**
I have been playing with xcp-ng for a few weeks now. I have used you script multiple times to create XO installs with no issues. Last Friday, I went to do another install on a fresh Debian 12 VM, as I have been doing, and I can't get it to work. When I run the install it tells me the "Looks like Xo-server is already running". If I select yes, it fails because it can't shut down the xo-server process because it doesn't exist. If I choose upgrade it tells me the node isn't installed.

I finally had to use the  xo virtual machine on the server to get thing running. I have deleted the Deb 12 VM and created new ones and still the same thing. Strange because I have spun and killed a bunch of these up in the past few weeks doing testing and learning he process and now I'm just stuck. Any thoughts?
Thanks 
**Installation logfile**
Attach complete log as a file.

**Comment by ronivay** [comment]
What does `pgrep -f xo-server` command return on this server where you're seeing the issue?

**Comment by robs007** [comment]
replies 529
________________________________

**Comment by robs007** [comment]
Should I be loading the xen guest tools on the xo install? I noticed the pre-made VM one did not have them.

**Comment by ronivay** [comment]
Which VM are you talking about? Prebuilt VM in this repo should have the tools. Those don't have anything to do with your issue though.

**Comment by robs007** [comment]
Yeah, sorry, I see that now. I assumed you should be loading the tools when building from the script.
________________________________

**Comment by robs007** [comment]
Added a new host to the pool and tried to create another XO on the new host, new VM. Same issue, this was working fines, I don't know what changed.

![image](https://github.com/ronivay/XenOrchestraInstallerUpdater/assets/947023/faf5694d-89c9-4490-b3d6-ce69a065248d)

**Comment by ronivay** [comment]
Can you please share logs and the `pgrep` command output i mentioned earlier. What VM are you using as base? Do you install it from scratch using ISO or are you using some readymade image?

**Comment by robs007** [comment]
pgrep -f xo-server returns 490
Using this ISO debian-12.6.0-amd64-netinst.iso and creating a new VM using the Debian Bookworm 12 (preview) xcp-ng template.
Thinking about it I was using the Debian 11 template before because there wasn't a 12. Don't think that should make a difference, but I can try and build another on with the Deb 11 template.
Thanks
[log.txt](https://github.com/user-attachments/files/16067318/log.txt)

**Comment by ronivay** [comment]
Okay. So clearly the pgrep command finds a process that matches xo-server. If there's no node pkg installed from repository and no systemd service as those steps fail for you too, it almost feels like you're using some image that already contains XO installation but not installed by the script in this repo. 

Could you run `ps -p $(pgrep -f xo-server)` too and paste the output here.

**Comment by robs007** [comment]
robszabo@xo-server-2:~$ ps -p $(pgrep -f xo-server)
    PID TTY          TIME CMD
    499 ?        00:00:00 avahi-daemon

**Comment by ronivay** [comment]
> robszabo@xo-server-2:~$ ps -p $(pgrep -f xo-server)
> 
>     PID TTY          TIME CMD
> 
>     499 ?        00:00:00 avahi-daemon

can you add `f` to the command, so `ps -fp..`. This is interesting.

**Comment by robs007** [comment]
UID          PID    PPID  C STIME TTY          TIME CMD
avahi        499       1  0 07:53 ?        00:00:00 avahi-daemon: running [xo-server-2.local]

**Comment by robs007** [comment]
So I noticed that the XO's that I had installed that worked where on Deb12.5. I tried to install from the Deb 12.5 ISO, but it upgraded to 12.6. That;'s the only difference I can see.

**Comment by ronivay** [comment]
> So I noticed that the XO's that I had installed that worked where on Deb12.5. I tried to install from the Deb 12.5 ISO, but it upgraded to 12.6. That;'s the only difference I can see.

As mentioned above. This is a bug in the script and happens because of the hostname you gave to the server. Pushing a fix shortly.

**Comment by ronivay** [comment]
Fix is now pushed into place. Please re-run the install, script should auto update itself with a new fixed version.

**Comment by robs007** [comment]
Yes, running now, thanks.

**Comment by ronivay** [comment]
Great. I’ll close this as solved.
