### ISSUE TITLE
Script fails with "internal errors encountered: external process killed a task"

### ISSUE THREAD

**Issue by Kajetan321** [ronivay/XenOrchestraInstallerUpdater#248]
Linux xo-ce 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
**Node.js version**: v20.15.1
**Yarn version**: 1.22.22

**Server specs**
Two vCPUs with 4GB of RAM

**Issue**
Script fails with "internal errors encountered: external process killed a task"

**Installation logfile**
[xo-install.log-202407091958.txt](https://github.com/user-attachments/files/16149867/xo-install.log-202407091958.txt)

**Comment by Kajetan321** [comment]
Oh, I forgot to mention, I tried running the script earlier and it run out of room.  I expanded the hard drive to 60GB and tried running the script again, that's when I got the internal error encountered.

**Comment by mchamlee** [comment]
@Kajetan321 I ran into this same issue/error a short time ago. Same server spec, though disk is configured at 20gb. After reviewing the log I attempted the Rollback option, but I don't think it did anything (indicated there wasn't anything to Rollback). I considered giving it more disk or upping the CPU, but before I did that I simply ran the installer again. The 2nd attempt completed successfully, no issues.

**Comment by ronivay** [comment]
As the error suggests, something external seems to have killed the process. Most likely something like an OOM killer, so i'd look into your OS logs for hints what might've happened.

**Comment by Kajetan321** [comment]
I increased the amount of RAM to 6GB, rebooted and tried again.  This time the process finished successfully.

**Comment by Kajetan321** [comment]
I increased the amount of RAM to 6GB, rebooted and tried again.  This time the process finished successfully.  Thank you for the suggestion.
