### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by cdbessig** [ronivay/XenOrchestraInstallerUpdater#25]
I tried to use the docker container with persistence:

`docker run -itd -p 80:80 -v /home/xoa/xo-server:/var/lib/xo-server -v /home/xoa/redis:/var/lib/redis ronivay/xen-orchestra`

But the server never saved my data after a restart.

Here's my exact steps:

run this:
`docker run -itd -p 80:80 -v /home/xoa/xo-server:/var/lib/xo-server -v /home/xoa/redis:/var/lib/redis ronivay/xen-orchestra`

Go into XOA and create a new user account.

`docker kill <containerid>`

`docker run -itd -p 80:80 -v /home/xoa/xo-server:/var/lib/xo-server -v /home/xoa/redis:/var/lib/redis ronivay/xen-orchestra`

Expected result: Go into XOA and see 2 user accounts.

Actual Result: Only the default account is there.

Am I doing something wrong?

**Comment by ronivay** [comment]
Hi,

Redis doesn’t save changes to disk immediately and when you kill the container (and the processes inside) right after making changes they don’t have a change to save state.

So let it run a while. If u need instant results u can play with the monit inside to shutdown processes in a nice way.
