### ISSUE TITLE
Add The Option For XO 6

### ISSUE THREAD

**Issue by delgado23** [ronivay/XenOrchestraInstallerUpdater#252]
It looks like with the latest release XOA from source now has the ability to build XO 6. Would it be possible to add a config option to enable it?

https://xen-orchestra.com/blog/xen-orchestra-5-98/
![Screenshot 2024-08-30 102733](https://github.com/user-attachments/assets/cc9772e2-c0de-4339-8c47-86620e05a5ec)

**Comment by ronivay** [comment]
Sure np. Once i manage to find some time to test this. Seems quite straight forward though.

**Comment by delgado23** [comment]
Thank you @ronivay!

**Comment by bwieg92** [comment]
In the latest blog post, they say this can now be done when using XO from sources

> To access the new preview UI, just add /v6 in your XOA URL. If you are using it from the sources, you can build it with yarn run turbo run build --filter @xen-orchestra/web from the XO root folder.

https://xen-orchestra.com/blog/xen-orchestra-5-99/

**Comment by bwieg92** [comment]
I can confirm that I was able to build and view XO 6 after running `yarn run turbo run build --filter @xen-orchestra/web` from `/opt/xo/xo-server/`

**Comment by ronivay** [comment]
Yeah this seems to be quite simple. Unfortunately i've been really busy with other stuff lately so haven't had time to look into this. Feel free to push PR if any of you have a working example ready.
