### ISSUE TITLE
Install fails due to apt-listbugs

### ISSUE THREAD

**Issue by ep1p** [ronivay/XenOrchestraInstallerUpdater#258]
**OS Version**: Debian Bookworm 12.7

**Server specs**
n/a

**Issue**
During installation on debian with apt-listbugs instlaled, it automatically pins packages to specific versions (due to bugs) which then cause the installation to fail. 

**Installation logfile**
following this cmd:

```
+ apt-get install -y build-essential redis-server libpng-dev git libvhdi-utils python3-minimal lvm2 nfs-common cifs-utils curl ntfs-3g dmidecode patch
..
grave bugs of g++-12 (→ 12.2.0-14) <Resolved in some Version>
 b1 - #1016903 - tree-vectorize: Wrong code at O2 level (-fno-tree-vectorize is working) (Fixed: 12.2.0-18 gcc-12/12.2.0-18)
Summary:
 g++-12(1 bug)
g++-12 will be pinned. Restart APT session to enable
**********************************************************************
****** Exiting with an error in order to stop the installation. ******
**********************************************************************
Fetched 18.6 MB in 1s (29.5 MB/s)
E: Sub-process /usr/bin/apt-listbugs apt returned an error code (10)
E: Failure running script /usr/bin/apt-listbugs apt
```

After this you end up stuck in a state:

```
# apt install g++
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
 
The following packages have unmet dependencies:
g++ : Depends: g++-12 (>= 12.2.0-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I guess the install script needs to handle apt-listbugs being installed and stop it from blocking packages being installed. Or perhaps just a note in the readme that it might interfere! 

Thanks.

**Comment by ronivay** [comment]
Hey,

Only sane thing that i can think of is to bail out immediately if apt-listbugs is installed. There's just no way to guess what the admin of the server really wants to do automatically and bypassing something like this in a script is just plain wrong.

README says:
```
I suggest using a fresh OS installation, let script install all necessary dependencies and dedicate the VM for running Xen Orchestra.
```

The admin of the server is the one who's responsible of getting around this if choosing to use something like apt-listbugs.

**Comment by ronivay** [comment]
I'm going to close this one out. This issue is unrelated to the script itself and will apply to anything that will install any packages so maintainer of the server should take care themselves to disable apt-listbugs from blocking package installs if required.
