### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by mikevipe** [ronivay/XenOrchestraInstallerUpdater#260]
**OS Version**: Debian 12.7.0 Fresh Install
**Node.js version**: v20.17.0
**Yarn version**: 1.22.22

**Server specs**
4vcpu 4GB ram

**Issue**
first install.
./xo-install.sh
Option 1

**Installation logfile**
[info] Fetching Xen Orchestra source code

[fail] Something went wrong, exiting. Check /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202409161934 for more details and use rollback feature if needed

+ command -v git
/usr/bin/git
+ cd . && git config --get remote.origin.url
https://github.com/ronivay/XenOrchestraInstallerUpdater.git
+ cd . && git status --porcelain
+ cd . && git fetch
+ cd . && git rev-parse --short HEAD
088f427
+ cd . && git rev-parse --short FETCH_HEAD
088f427
+ cd . && git diff --name-only @{upstream}| grep xo-install.sh
Running script version 088f427 with config:

PORT="80"
INSTALLDIR="/opt/xo"
SELFUPGRADE=true
CONFIGUPDATE=true
REPOSITORY="https://github.com/vatesfr/xen-orchestra"
BRANCH="master"
PLUGINS="all"
AUTOUPDATE="true"
OS_CHECK="true"
ARCH_CHECK="true"
PRESERVE="3"

+ id -u
0
+ uname -m
x86_64
+ command -v xe
+ grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo '[0-9]{1,2}' | head -1
12
+ grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}'
Debian
+ grep ^GRUB_DISTRIBUTOR /etc/default/grub | grep 'Xen Orchestra'
+ command -v dnf
+ command -v apt-get
/usr/bin/apt-get
+ command -v systemctl
/usr/bin/systemctl
+ df -P -k '/opt' | tail -1 | awk '{print $4}'
39167764
+ grep MemTotal /proc/meminfo | awk '{print $2}'
3983668
+ pgrep -f '^([a-zA-Z0-9_\/-]+?)node.*xo-server'
+ apt-get update
Hit:1 http://mirrors.ocf.berkeley.edu/debian bookworm InRelease
Hit:2 http://mirrors.ocf.berkeley.edu/debian bookworm-updates InRelease
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Reading package lists...
W: https://dl.yarnpkg.com/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
+ apt-get install -y build-essential redis-server libpng-dev git libvhdi-utils python3-minimal lvm2 nfs-common cifs-utils curl ntfs-3g dmidecode patch
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
redis-server is already the newest version (5:7.0.15-1~deb12u1).
libpng-dev is already the newest version (1.6.39-2).
git is already the newest version (1:2.39.5-0+deb12u1).
libvhdi-utils is already the newest version (20210425-1+b2).
python3-minimal is already the newest version (3.11.2-1+b1).
lvm2 is already the newest version (2.03.16-2).
nfs-common is already the newest version (1:2.6.2-4).
cifs-utils is already the newest version (2:7.0-2).
curl is already the newest version (7.88.1-10+deb12u7).
ntfs-3g is already the newest version (1:2022.10.3-1+b1).
dmidecode is already the newest version (3.4-1).
patch is already the newest version (2.7.6-7).
The following packages were automatically installed and are no longer required:
  gyp handlebars javascript-common libc-ares2 libgdk-pixbuf-2.0-0
  libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libjs-async libjs-events
  libjs-inherits libjs-is-typedarray libjs-prettify libjs-regenerate
  libjs-source-map libjs-sprintf-js libjs-typedarray-to-buffer libnotify-bin
  libnotify4 libssl-dev libuv1-dev node-abbrev node-ampproject-remapping
  node-ansi-escapes node-ansi-regex node-ansi-styles node-aproba
  node-are-we-there-yet node-argparse node-arrify node-async node-async-each
  node-auto-bind node-babel-plugin-add-module-exports node-babel7-runtime
  node-balanced-match node-base64-js node-binary-extensions
  node-brace-expansion node-busboy node-camelcase node-caniuse-lite
  node-chownr node-chrome-trace-event node-ci-info node-cjs-module-lexer
  node-cli-boxes node-cli-cursor node-clone node-clone-deep
  node-collection-visit node-color-convert node-color-name node-colors
  node-commander node-commondir node-concat-stream
  node-console-control-strings node-convert-source-map node-core-js
  node-core-js-pure node-core-util-is node-data-uri-to-buffer
  node-decompress-response node-deep-is node-defaults node-define-property
  node-delegates node-depd node-diff node-electron-to-chromium node-encoding
  node-end-of-stream node-err-code node-error-ex node-es-module-lexer
  node-escape-string-regexp node-eslint-utils node-eslint-visitor-keys
  node-esquery node-estraverse node-esutils node-events node-fancy-log
  node-fast-deep-equal node-fast-levenshtein node-fetch node-find-up
  node-flatted node-for-in node-for-own node-foreground-child
  node-fs-readdir-recursive node-fs-write-stream-atomic node-fs.realpath
  node-function-bind node-functional-red-black-tree node-get-caller-file
  node-get-stream node-get-value node-glob node-globals node-got
  node-graceful-fs node-growl node-has-flag node-has-unicode node-has-value
  node-has-values node-hosted-git-info node-iconv-lite node-ieee754 node-iferr
  node-imurmurhash node-indent-string node-inflight node-inherits node-ini
  node-interpret node-ip node-ip-regex node-is-arrayish node-is-binary-path
  node-is-buffer node-is-descriptor node-is-extendable node-is-extglob
  node-is-path-cwd node-is-plain-obj node-is-plain-object node-is-stream
  node-is-typedarray node-is-windows node-isarray node-isexe node-isobject
  node-js-tokens node-jsesc node-json-buffer node-json-parse-better-errors
  node-json-schema node-json-schema-traverse node-json-stable-stringify
  node-jsonify node-jsonparse node-kind-of node-levn node-loader-runner
  node-locate-path node-lodash-packages node-log-driver node-lowercase-keys
  node-lru-cache node-map-visit node-memfs node-merge-stream
  node-mimic-response node-minimatch node-minimist node-minipass
  node-mixin-deep node-mute-stream node-n3 node-negotiator node-neo-async
  node-npm-run-path node-object-inspect node-object-visit node-once
  node-optimist node-optionator node-osenv node-p-cancelable node-p-limit
  node-p-locate node-p-map node-pascalcase node-path-dirname node-path-exists
  node-path-is-absolute node-path-is-inside node-path-type node-pify
  node-pkg-dir node-postcss-value-parser node-prelude-ls
  node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-prr node-pump node-quick-lru node-randombytes node-read
  node-readable-stream node-rechoir node-regenerate
  node-regenerate-unicode-properties node-regenerator-runtime
  node-regenerator-transform node-regexpp node-regjsgen node-repeat-string
  node-require-directory node-resolve node-resolve-cwd node-resolve-from
  node-restore-cursor node-resumer node-retry node-run-queue node-safe-buffer
  node-sellside-emitter node-serialize-javascript node-set-blocking
  node-set-immediate-shim node-shebang-command node-shebang-regex
  node-shell-quote node-signal-exit node-slash node-slice-ansi
  node-source-list-map node-source-map node-source-map-support
  node-spdx-correct node-spdx-exceptions node-spdx-expression-parse
  node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils
  node-string-decoder node-strip-bom node-strip-json-comments
  node-supports-color node-tapable node-terser node-text-table node-through
  node-time-stamp node-to-fast-properties node-tslib node-type-check
  node-typedarray node-typedarray-to-buffer node-undici
  node-unicode-canonical-property-names-ecmascript
  node-unicode-match-property-value-ecmascript
  node-unicode-property-aliases-ecmascript node-unique-filename
  node-unset-value node-util-deprecate node-uuid node-v8flags
  node-validate-npm-package-license node-wcwidth.js node-webpack-sources
  node-wordwrap node-wrappy node-write-file-atomic node-xtend node-y18n
  node-yallist node-yaml
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ apt-get install -y apt-transport-https ca-certificates
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (2.6.1).
ca-certificates is already the newest version (20230311).
The following packages were automatically installed and are no longer required:
  gyp handlebars javascript-common libc-ares2 libgdk-pixbuf-2.0-0
  libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libjs-async libjs-events
  libjs-inherits libjs-is-typedarray libjs-prettify libjs-regenerate
  libjs-source-map libjs-sprintf-js libjs-typedarray-to-buffer libnotify-bin
  libnotify4 libssl-dev libuv1-dev node-abbrev node-ampproject-remapping
  node-ansi-escapes node-ansi-regex node-ansi-styles node-aproba
  node-are-we-there-yet node-argparse node-arrify node-async node-async-each
  node-auto-bind node-babel-plugin-add-module-exports node-babel7-runtime
  node-balanced-match node-base64-js node-binary-extensions
  node-brace-expansion node-busboy node-camelcase node-caniuse-lite
  node-chownr node-chrome-trace-event node-ci-info node-cjs-module-lexer
  node-cli-boxes node-cli-cursor node-clone node-clone-deep
  node-collection-visit node-color-convert node-color-name node-colors
  node-commander node-commondir node-concat-stream
  node-console-control-strings node-convert-source-map node-core-js
  node-core-js-pure node-core-util-is node-data-uri-to-buffer
  node-decompress-response node-deep-is node-defaults node-define-property
  node-delegates node-depd node-diff node-electron-to-chromium node-encoding
  node-end-of-stream node-err-code node-error-ex node-es-module-lexer
  node-escape-string-regexp node-eslint-utils node-eslint-visitor-keys
  node-esquery node-estraverse node-esutils node-events node-fancy-log
  node-fast-deep-equal node-fast-levenshtein node-fetch node-find-up
  node-flatted node-for-in node-for-own node-foreground-child
  node-fs-readdir-recursive node-fs-write-stream-atomic node-fs.realpath
  node-function-bind node-functional-red-black-tree node-get-caller-file
  node-get-stream node-get-value node-glob node-globals node-got
  node-graceful-fs node-growl node-has-flag node-has-unicode node-has-value
  node-has-values node-hosted-git-info node-iconv-lite node-ieee754 node-iferr
  node-imurmurhash node-indent-string node-inflight node-inherits node-ini
  node-interpret node-ip node-ip-regex node-is-arrayish node-is-binary-path
  node-is-buffer node-is-descriptor node-is-extendable node-is-extglob
  node-is-path-cwd node-is-plain-obj node-is-plain-object node-is-stream
  node-is-typedarray node-is-windows node-isarray node-isexe node-isobject
  node-js-tokens node-jsesc node-json-buffer node-json-parse-better-errors
  node-json-schema node-json-schema-traverse node-json-stable-stringify
  node-jsonify node-jsonparse node-kind-of node-levn node-loader-runner
  node-locate-path node-lodash-packages node-log-driver node-lowercase-keys
  node-lru-cache node-map-visit node-memfs node-merge-stream
  node-mimic-response node-minimatch node-minimist node-minipass
  node-mixin-deep node-mute-stream node-n3 node-negotiator node-neo-async
  node-npm-run-path node-object-inspect node-object-visit node-once
  node-optimist node-optionator node-osenv node-p-cancelable node-p-limit
  node-p-locate node-p-map node-pascalcase node-path-dirname node-path-exists
  node-path-is-absolute node-path-is-inside node-path-type node-pify
  node-pkg-dir node-postcss-value-parser node-prelude-ls
  node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-prr node-pump node-quick-lru node-randombytes node-read
  node-readable-stream node-rechoir node-regenerate
  node-regenerate-unicode-properties node-regenerator-runtime
  node-regenerator-transform node-regexpp node-regjsgen node-repeat-string
  node-require-directory node-resolve node-resolve-cwd node-resolve-from
  node-restore-cursor node-resumer node-retry node-run-queue node-safe-buffer
  node-sellside-emitter node-serialize-javascript node-set-blocking
  node-set-immediate-shim node-shebang-command node-shebang-regex
  node-shell-quote node-signal-exit node-slash node-slice-ansi
  node-source-list-map node-source-map node-source-map-support
  node-spdx-correct node-spdx-exceptions node-spdx-expression-parse
  node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils
  node-string-decoder node-strip-bom node-strip-json-comments
  node-supports-color node-tapable node-terser node-text-table node-through
  node-time-stamp node-to-fast-properties node-tslib node-type-check
  node-typedarray node-typedarray-to-buffer node-undici
  node-unicode-canonical-property-names-ecmascript
  node-unicode-match-property-value-ecmascript
  node-unicode-property-aliases-ecmascript node-unique-filename
  node-unset-value node-util-deprecate node-uuid node-v8flags
  node-validate-npm-package-license node-wcwidth.js node-webpack-sources
  node-wordwrap node-wrappy node-write-file-atomic node-xtend node-y18n
  node-yallist node-yaml
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ apt-get install gnupg -y
Reading package lists...
Building dependency tree...
Reading state information...
gnupg is already the newest version (2.2.40-1.1).
The following packages were automatically installed and are no longer required:
  gyp handlebars javascript-common libc-ares2 libgdk-pixbuf-2.0-0
  libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libjs-async libjs-events
  libjs-inherits libjs-is-typedarray libjs-prettify libjs-regenerate
  libjs-source-map libjs-sprintf-js libjs-typedarray-to-buffer libnotify-bin
  libnotify4 libssl-dev libuv1-dev node-abbrev node-ampproject-remapping
  node-ansi-escapes node-ansi-regex node-ansi-styles node-aproba
  node-are-we-there-yet node-argparse node-arrify node-async node-async-each
  node-auto-bind node-babel-plugin-add-module-exports node-babel7-runtime
  node-balanced-match node-base64-js node-binary-extensions
  node-brace-expansion node-busboy node-camelcase node-caniuse-lite
  node-chownr node-chrome-trace-event node-ci-info node-cjs-module-lexer
  node-cli-boxes node-cli-cursor node-clone node-clone-deep
  node-collection-visit node-color-convert node-color-name node-colors
  node-commander node-commondir node-concat-stream
  node-console-control-strings node-convert-source-map node-core-js
  node-core-js-pure node-core-util-is node-data-uri-to-buffer
  node-decompress-response node-deep-is node-defaults node-define-property
  node-delegates node-depd node-diff node-electron-to-chromium node-encoding
  node-end-of-stream node-err-code node-error-ex node-es-module-lexer
  node-escape-string-regexp node-eslint-utils node-eslint-visitor-keys
  node-esquery node-estraverse node-esutils node-events node-fancy-log
  node-fast-deep-equal node-fast-levenshtein node-fetch node-find-up
  node-flatted node-for-in node-for-own node-foreground-child
  node-fs-readdir-recursive node-fs-write-stream-atomic node-fs.realpath
  node-function-bind node-functional-red-black-tree node-get-caller-file
  node-get-stream node-get-value node-glob node-globals node-got
  node-graceful-fs node-growl node-has-flag node-has-unicode node-has-value
  node-has-values node-hosted-git-info node-iconv-lite node-ieee754 node-iferr
  node-imurmurhash node-indent-string node-inflight node-inherits node-ini
  node-interpret node-ip node-ip-regex node-is-arrayish node-is-binary-path
  node-is-buffer node-is-descriptor node-is-extendable node-is-extglob
  node-is-path-cwd node-is-plain-obj node-is-plain-object node-is-stream
  node-is-typedarray node-is-windows node-isarray node-isexe node-isobject
  node-js-tokens node-jsesc node-json-buffer node-json-parse-better-errors
  node-json-schema node-json-schema-traverse node-json-stable-stringify
  node-jsonify node-jsonparse node-kind-of node-levn node-loader-runner
  node-locate-path node-lodash-packages node-log-driver node-lowercase-keys
  node-lru-cache node-map-visit node-memfs node-merge-stream
  node-mimic-response node-minimatch node-minimist node-minipass
  node-mixin-deep node-mute-stream node-n3 node-negotiator node-neo-async
  node-npm-run-path node-object-inspect node-object-visit node-once
  node-optimist node-optionator node-osenv node-p-cancelable node-p-limit
  node-p-locate node-p-map node-pascalcase node-path-dirname node-path-exists
  node-path-is-absolute node-path-is-inside node-path-type node-pify
  node-pkg-dir node-postcss-value-parser node-prelude-ls
  node-process-nextick-args node-promise-inflight node-promise-retry
  node-promzard node-prr node-pump node-quick-lru node-randombytes node-read
  node-readable-stream node-rechoir node-regenerate
  node-regenerate-unicode-properties node-regenerator-runtime
  node-regenerator-transform node-regexpp node-regjsgen node-repeat-string
  node-require-directory node-resolve node-resolve-cwd node-resolve-from
  node-restore-cursor node-resumer node-retry node-run-queue node-safe-buffer
  node-sellside-emitter node-serialize-javascript node-set-blocking
  node-set-immediate-shim node-shebang-command node-shebang-regex
  node-shell-quote node-signal-exit node-slash node-slice-ansi
  node-source-list-map node-source-map node-source-map-support
  node-spdx-correct node-spdx-exceptions node-spdx-expression-parse
  node-spdx-license-ids node-sprintf-js node-ssri node-stack-utils
  node-string-decoder node-strip-bom node-strip-json-comments
  node-supports-color node-tapable node-terser node-text-table node-through
  node-time-stamp node-to-fast-properties node-tslib node-type-check
  node-typedarray node-typedarray-to-buffer node-undici
  node-unicode-canonical-property-names-ecmascript
  node-unicode-match-property-value-ecmascript
  node-unicode-property-aliases-ecmascript node-unique-filename
  node-unset-value node-util-deprecate node-uuid node-v8flags
  node-validate-npm-package-license node-wcwidth.js node-webpack-sources
  node-wordwrap node-wrappy node-write-file-atomic node-xtend node-y18n
  node-yallist node-yaml
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ command -v setcap
/usr/sbin/setcap
+ command -v node
/usr/bin/node
+ command -v npm
/usr/bin/npm
+ node -v 2>/dev/null| grep -Eo '[0-9.]+' | cut -d'.' -f1
20
+ command -v yarn
/usr/local/bin/yarn
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
+ cd "/opt/xo/xo-src/xen-orchestra" && git remote set-url origin "https://github.com/vatesfr/xen-orchestra" &&             git fetch --prune &&             git reset --hard origin/master &&             git clean -xdff
fatal: not a git repository (or any of the parent directories): .git

**Comment by ronivay** [comment]
Remove `/opt/xo/xo-src` directory and try again.
