### ISSUE TITLE
Getting XO Proxy to function

### ISSUE THREAD

**Issue by tuxpowered** [ronivay/XenOrchestraInstallerUpdater#266]
I use XO Proxy for several remotes on our business but the cost for a home-lap is not practical, so I was excited to see your project.

I am unclear on a few steps however. 
After installing a clean debian and running xo-install.sh  Install with option 1.
  1. Install
  2. Update
  3. Rollback
  4. Install proxy
  5. Update proxy
  6. Exit

Seeing that you can install the "Proxy" I proceeded to run the install again with option 4.
This completed without errors and gave a JSON file with the instructions to "Import in to the config"

I assumed this to be in the newly installed XO under  Settings >  XO Config > Import.   _(I am now thinking this is incorrect>???)_

As the "Proxy" then shows up under Proxy, but its not configured to connect to anything. 
https://xen-orchestra.com/blog/xo-proxy-a-concrete-guide/ uses a pull and registration process, so I am not sure that the VM they provide is the right thing to use either. 

Can you provide a little clarity on the correct process to install the "Proxy" ?

**Comment by ronivay** [comment]
Hey,

Sorry for delayed answer on this. So yeah the official XOA does offer a way to deploy a proxy from GUI with few clicks, this will basically download an appliance VM, deploy it to your pool and then configure it as a proxy. This automated method is not available for the XO installed from sources. The method used in this repo is still experimental as there's no "official" way to do it. You're not supposed to run the proxy installation on the same VM where your XO already runs, instead you deploy a separate VM to your pool and run the script on that and install only the proxy. Do check the README as it has some more information about this.

**Comment by tuxpowered** [comment]
Thank you for the update ronivay. 
I have been using the XO from sources (XO CE) for a few years built off Jarli01 script. But seeing your attempt at making proxy work would be hugely helpful. Backing up locally rather sending it to the cloud and back to the local NFS mount is much more efficient. 

I will look into the readme, but thank you for the confirmation that I deployed it wrong. 
I will do some testing over the holiday and see how things fair out. 

I have an actual licensed version of XO for business, and we use 2 proxies registered with it. I can tell you from experience that it has glitches and issues with updates and setup. Both had to be manually setup from the CLI as they never fully completed connection. And on several updates I have had to have support "fix" something that broke or didn't get updated with the "upgrade proxy" button.  So the commercial version doesnt even work with out issues :) That being said, the issues are only related to installs and upgrades once it is in service it works fine. 

So while this is not an "official" way. The Official way, doesn't work well either lol

**Comment by ronivay** [comment]
Yeah you can even keep using the same script for your XO, that doesn't prevent running the proxy install/update separately with this one on the other VM.

As mentioned, this is a bit experimental still and not that much tested, but as long as the proxy functionality doesn't change that much, it should work fine. Do let me know if you encounter any issues and will try to solve them.
