### ISSUE TITLE
Install behind corporate proxy

### ISSUE THREAD

**Issue by Seplik** [ronivay/XenOrchestraInstallerUpdater#268]
Hi,

I'm sitting behind a corporate proxy with username, password and SSL-Interception.
Is there a way to implement a proxy in the config file or a workaround to change the settings in the install script?

Best regards

Mike

**Comment by ronivay** [comment]
Hey,

For the installation i assume? No there is no support for http proxy. In theory it should work if you're able to define global proxy configs for your package manager, curl and yarn.

**Comment by Seplik** [comment]
Got it! After some tries it works....

**Comment by ronivay** [comment]
> Got it! After some tries it works....

Great! happy to hear that
