### ISSUE TITLE
XOA Configuration Update

### ISSUE THREAD

**Issue by billgertz** [ronivay/XenOrchestraInstallerUpdater#27]
@ronivay 

So ran into a problem with XOA. The root seems to be both your script and the XOA package seem to drop configuration files. [This can lead to problems that are difficult for the uninitiated](https://xcp-ng.org/forum/topic/2264/xoa-won-t-start-https-listen-on-configured-port).

Yours seems to be *.xo-server.toml* and theirs seems to be *config.toml*. The upshot is the xo-server loads [both](https://xcp-ng.org/forum/topic/2264/xoa-won-t-start-https-listen-on-configured-port/6). 

After a bit of back and forth [they are changing their documented advice](https://github.com/vatesfr/xen-orchestra/commit/7b47e4024492d38bca6e928748490e0a4880264c) on both the location and name of the configuration file (*~/.config/xo-server/config.toml*) alternately you can drop it in the xo-server directory as *config.toml*. Dropping in both places would be a Bad Thing (TM pending) as both would load, causing confusion.

I'll be happy to submit a PR, any thoughts, or should I leave this to you? BTW, I've started installing a new XOA VM and would be happy to be the guinea pig to getting this right.

**Comment by billgertz** [comment]
@ronivay Hey going to press ahead and with your current script on a fresh VM and see if end up with both _.xo-server.toml_ and _config.toml_. Then work with your script to ensure only only one file is left in place. Can you provide ant tips that I need to watch?

**Comment by ronivay** [comment]
Hi,

Thanks for filing an issue. This isn't the first time they change the way configuration is handled and should be fairly easy to fix. I'll take a look at this asap.

**Comment by ronivay** [comment]
Required a little more effort that i first thought since preferred configuration path is outside of the install directory. Added another script config parameter which offers an option to keep the config file in future updates (since it's now placed in users home directory).

Also removed some old support for the .yaml config at the same time.

Please give it a shot and let me know if you encounter any issues.

https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/9831571cea292b23079c563f545368a0a27a04ca

**Comment by billgertz** [comment]
Thanks, and, um, wow. Didn't expect to hear from you so quickly - this was fortunate as I was just starting the clean install. I'll give it a whirl and let you know how it turns out.

**Comment by billgertz** [comment]
Ok with a fresh install I ended up with both _/etc/xo/xo-server/config.toml_ and _~/.configure/xo-server/config.toml_. This is a problem as xo-server loads both at start. There should be either one or the other, not both. Starting xo-server with debugging: `env debug="*" /etc/xo/xo-server/bin/xo-server` shows that both are indeed loaded:
```
admin.bill@bfxoa002:~$ sudo su -
[sudo] password for xxxxxxxx: 
root@bfxoa002:~# cd /etc/xo/xo-server
root@bfxoa002:/etc/xo/xo-server# systemctl stop xo-server.service 
root@bfxoa002:/etc/xo/xo-server# env DEBUG='*' ./bin/xo-server
  app-conf /etc/xo/xo-builds/xen-orchestra-201927112013/packages/xo-server/config.toml +0ms
  app-conf /root/.config/xo-server/config.toml +1ms
2019-11-27T19:32:43.176Z xo:main INFO Configuration loaded.
2019-11-27T19:32:43.180Z xo:main INFO Web server listening on http://[::]:80
2019-11-27T19:32:43.227Z xo:xo-mixins:hooks DEBUG start start…
2019-11-27T19:32:43.292Z xo:xo-mixins:hooks DEBUG start finished
2019-11-27T19:32:43.292Z xo:xo-mixins:hooks DEBUG clean start…
2019-11-27T19:32:43.298Z xo:xo-mixins:hooks DEBUG clean finished
.
.
.
```

This would lead directly to the same problem we documented with this XCP-ng thread,  just with your script dropping a second config file at _~/.config/xo-server/config.toml_. Perhaps we need to set _UPDATECONFIG_ to rather than _true_ or _false_, but rather:

- native: use _/etc/xo/xo_server_
- installer: use _~/.config/xo-server/
- unchanged: use whatever directory is currently used, default to installer if no config found

In any case both configs in place after the install is a Bad Thing.

Ideas?

**Comment by ronivay** [comment]
Hi,

This is expected. If you take a look at the /etc/xo/xo-server/config.toml file (which comes from the repository) unaltered, it does have some default configuration that sample.config.toml doesn't and it's instructed not to be touched. The one in ~/.config/xo-server/config.toml is used to overwrite settings from the default ones.

**Comment by billgertz** [comment]
Ah, that wasn't clear to me.

Let me try altering the copy in the installers home directory and see if we have a startup as expected.

Here is the altered the copy of _~/.config/xo-server/config.toml_ for HTTPS:

```
.
.
.
[http.listen]]
# Address on which the server is listening on.
#
# Sets it to 'localhost' for IP to listen only on the local host.
#
# Default: all IPv6 addresses if available, otherwise all IPv4 addresses.
# hostname = 'localhost'

# Port on which the server is listening on.
#
# Default: undefined
hostname = '0.0.0.0'
port = 443

# Instead of `host` and `port` a path to a UNIX socket may be specified
# (overrides `host` and `port`).
#
# Default: undefined
# socket = './http.sock'

# # Basic HTTPS.
# #
# # You can find the list of possible options there
# # https://nodejs.org/docs/latest/api/tls.html#tls.createServer
# #
# # The only difference is the presence of the certificate and the key.
# [[http.listen]]
# #hostname = '127.0.0.1'
# port = 443
#
# # File containing the certificate (PEM format).
# #
# # If a chain of certificates authorities is needed, you may bundle them
# # directly in the certificate.
# #
# # Note: the order of certificates does matter, your certificate should come
# # first followed by the certificate of the above
# # certificate authority up to the root.
# #
# # Default: undefined
cert = '/etc/ssl/certs/xoa/xoa.crt'
#
# # File containing the private key (PEM format).
# #
# # If the key is encrypted, the passphrase will be asked at
# # server startup.
# #
# # Default: undefined
key = '/etc/ssl/certs/xoa/xoa.key'

# Redirect http to https
redirectToHttps = true

# List of files/directories which will be served.
[http.mounts]
.
.
.
```
Looks like that worked, xo-server came up as over risen by _~/.config/xo-server/config.toml_

```
.
.
.
root@bfxoa002:/etc/xo/xo-server# env DEBUG='*' ./bin/xo-server
  app-conf /etc/xo/xo-builds/xen-orchestra-201927112013/packages/xo-server/config.toml +0ms
  app-conf /root/.config/xo-server/config.toml +1ms
2019-11-28T01:53:39.281Z xo:main INFO Configuration loaded.
2019-11-28T01:53:39.294Z xo:main INFO Web server listening on https://0.0.0.0:80
2019-11-28T01:53:39.342Z xo:xo-mixins:hooks DEBUG start start…
2019-11-28T01:53:39.406Z xo:xo-mixins:hooks DEBUG start finished
2019-11-28T01:53:39.406Z xo:xo-mixins:hooks DEBUG clean start…
2019-11-28T01:53:39.412Z xo:xo-mixins:hooks DEBUG clean finished
.
.
.
```

That makes better sense on what was going on. I'll alter my original xoa config to conform to this schema. So leave the conf in _/etc/so/xo-server/config.toml_ alone and all of the over rides in _~/.config/xo-server/config.toml_. I'll reread the [doc pages](https://xen-orchestra.com/docs/) and see if this point is clear. If not I'll suggest an edit to make it so.

Thanks for your quick work and putting up with my misapprehension.

**Comment by billgertz** [comment]
@ronivay 
Er, no that doesn't seem clear:
> Now you have to create a config file for xo-server:

> $ cd packages/xo-server
> $ mkdir -p ~/.config/xo-server
> $ cp sample.config.toml ~/.config/xo-server/config.toml
> Note: If you're installing xo-server as a global service, you may want to copy the file to /etc/xo-server/config.toml instead.

Think that comment could be improved somewhat, or we don't really understand why they intend...

**Comment by ronivay** [comment]
Yeah i think the default configuration and override isn't really addressed in the documentation purely because user shouldn't touch the default config anyway. That part just explains how to put the sample config to home directory for possible overrides.

Feel free to make a pull request on that if you think that should be better explained.

I suppose this issue can be closed since the home directory configuration override is working as expeted, right?

**Comment by billgertz** [comment]
@ronivay 
Hey thanks again for the help, and sure close the issue. It is working as it should. I'll do a deeper review of this with other doc they have on hand. If this isn't addressed it probably should be.

Thanks again.
