### ISSUE TITLE
Anyway to remove persistant banner?

### ISSUE THREAD

**Issue by pageb018** [ronivay/XenOrchestraInstallerUpdater#28]
I just installed your script and it worked great however I notice I get a persistent banner warning. I have tried the options here:

https://github.com/vatesfr/xen-orchestra/issues/4175

but they have not worked for me... 

Was wondering if anyone has any ideas?

**Comment by ronivay** [comment]
Hi,

Tbh i have no idea. Never attempted to do this myself. I suppose this is more like a question to xen orchestra forums since it doesn’t actually have anything to do with the script this repo is about.

**Comment by andyjhall** [comment]
This can be removed by adding some sed commands into xo-install.sh on line 403 (just before compilation)

`cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-web/src/xo-app
sed -i 's/this.displayOpenSourceDisclaimer()/ /gi' index.js
sed -i 's/!this.state.dismissedSourceBanner/false/gi' index.js`

This is obviously subject to change and could break at any time, it may be worth looking at changing the value of the **env.XOA_PLAN** variable, this is set to 5 for sources and seems to be the crux of the opensource checks.

**Comment by ronivay** [comment]
> This can be removed by adding some sed commands into xo-install.sh on line 403 (just before compilation)
> 
> `cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-web/src/xo-app`
> `sed -i 's/this.displayOpenSourceDisclaimer()/ /gi' index.js`
> `sed -i 's/!this.state.dismissedSourceBanner/false/gi' index.js`
> 
> You can also just run the above sed commands followed by a `yarn build` in the `$INSTALLDIR/xo-builds/xen-orchestra-$TIME` folder at anytime to remove the popups from a prebuilt install.
> 
> This is obviously subject to change and could break at any time, it may be worth looking at changing the value of the **env.XOA_PLAN** variable, this is set to 5 for sources and seems to be the crux of the opensource checks, however initially changing this seemed to result in a broken install.

Nice. I’m not going to impelent this though. Touching the actual sources is out of scope from the goal that this script tries to achieve.

**Comment by tig987** [comment]
If you want to remove all the banners and warnings from the current version of XO you can add these updated commands into xo-install.sh (just before compilation):

```
cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-web/src/xo-app
sed -i 's/this.displayOpenSourceDisclaimer()/ /gi' index.js
sed -i 's/!this.state.dismissedSourceBanner/false/gi' index.js

cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-web/src/xo-app/menu
# remove red question marks from XOA menu items
sed -i 's/<UpdateTag key='\''update'\'' \/>/null/gi' index.js
sed -i 's/extra: <UpdateTag \/>,/ /gi' index.js
# remove "no support" warning from menu - show "Community" instead
sed -i 's/process.env.XOA_PLAN === 5 ?/process.env.XOA_PLAN === 99 ?/gi' index.js

cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME/packages/xo-web/src/xo-app/home
# remove "Pro Support" warnings from hosts and pools list
sed -i 's/supportLevel !== '\''total'\''/false/gi' pool-item.js
sed -i 's/proSupportStatus !== undefined && proSupportStatus.level !== '\''success'\''/false/gi' host-item.js
```

Tested against current master branch commit [cfea2](https://github.com/vatesfr/xen-orchestra/commit/cfea2b3a2b3ce6bd82266c8dc232e3eec59feace)
