### ISSUE TITLE
xo-install.sh --update error

### ISSUE THREAD

**Issue by boulwarek** [ronivay/XenOrchestraInstallerUpdater#29]
When trying to update my Xen Orchestra instance using this script with this command
`./xo-install.sh --update` I received a message stating the following:
[fail] Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed

I reviewed the log in question and found this:
```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

Note: I am not a developer and am not familiar enough with git to make any suggestions.
After some googling around, I ended up making this change to the xo-install.sh script and the script upgraded my installation properly. (added "origin master" to the git pull command)

```
         if [[ ! -d "$XO_SRC_DIR" ]]; then
                mkdir -p "$XO_SRC_DIR"
                git clone https://github.com/vatesfr/xen-orchestra "$XO_SRC_DIR"
        else
                cd "$XO_SRC_DIR"
                git pull origin master
                cd $(dirname $0)
        fi
```

Again, I am no developr and have no clue what I am doing, but this worked for me and I just wanted to reach out and see if this was a proper way to correct this issue.

**Comment by ronivay** [comment]
Hi,

Interesting. I see no reason why just git pull shouldn’t work since the repository should already be cloned there and stay on specific branch unless changed. So you first used the regular install procedure from this script and then later tried to update and ended up with this error? Did you change any parameters from xo-install.cfg in between?

**Comment by boulwarek** [comment]
I located the issue, which was my fault. I did the initial install with the script, but ran into a backup restoration issue that forced me to change the branch and roll back my installation to an earlier version using some step by step instructions I found. Not understanding git, I didn't realize this would break the update script.
