### ISSUE TITLE
node.js LTS version is now available for XO

### ISSUE THREAD

**Issue by rizaemet** [ronivay/XenOrchestraInstallerUpdater#30]
Hello,
now node.js lts version (12.x) is available for xo instead of 8.x
commit: [https://github.com/vatesfr/xen-orchestra/commit/cf8bd759e3a7c0280ccaa5123d33d21b48d004fa](https://github.com/vatesfr/xen-orchestra/commit/cf8bd759e3a7c0280ccaa5123d33d21b48d004fa)

**Comment by ronivay** [comment]
Hi,

Thanks. Ended up to failed installation on first run so need to debug and test this a bit further before implementing.

**Comment by ronivay** [comment]
https://github.com/vatesfr/xen-orchestra/issues/4869

waiting for reply to this

**Comment by ronivay** [comment]
oh well, tests failed because of OOM within the test VM. node 8.x worked, 12.x didn't :)

this is now implemented: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/adf9b407355ad98f904ae7b8f4d33a3c7fde05e8
