### ISSUE TITLE
Getting error on fresh Debian 10 install

### ISSUE THREAD

**Issue by jacobgad** [ronivay/XenOrchestraInstallerUpdater#31]
xo-install.log file from failed install

Cloning into '/etc/xo/xo-src/xen-orchestra'...

WARNING: We noticed you're using the `useBuiltIns` option without declaring a c$

You should also be sure that the version you pass to the `corejs` option matche$

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - Java$

Writing Node.js report to file: report.20200317.225448.16961.0.001.json
Node.js report completed
 1: 0x9ef190 node::Abort() [gulp build]
 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [gulp build]
 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, b$
 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, $
 5: 0xd0a765  [gulp build]
 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector$

**Comment by ronivay** [comment]
Hi,

You’re running out of memory. Try to increase the amount of RAM of your VM

**Comment by jacobgad** [comment]
Thank you so much, you are awesome!
and thank you for getting back to me so quick

**Comment by ronivay** [comment]
Let me know if it helps. Increased memory usage seems to be because of the newer nodejs version. Bumped into this myself as well during testing.

**Comment by jacobgad** [comment]
You were correct, pushed the RAM to 4GB from the previous 2GB and I can confirm that it is now working.
Can't thank you enough for your help and all your hard work!

**Comment by ronivay** [comment]
Good stuff. Enjoy :)
