### ISSUE TITLE
apt-key Error

### ISSUE THREAD

**Issue by nowjon** [ronivay/XenOrchestraInstallerUpdater#32]
Hi, 

I've got a newer Ubuntu 18.04.4 LTS install where I tried to run the script wiht autoinstall and got the below error, anyone know how to get around this? 

Warning: apt-key output should not be parsed (stdout is not a terminal)
Warning: apt-key output should not be parsed (stdout is not a terminal)
E: Sub-process /usr/bin/dpkg returned an error code (1)

Thank you!

**Comment by ronivay** [comment]
Hi,

Is this a fresh ubuntu installation you’re using? Are you having any issues installing packages outside this script? First thought is that you have an issue with your packages which is unrelated to this script. 

Please try to install something with apt-get and see how it goes.

**Comment by nowjon** [comment]
After spinning up a new VM for this it worked fine, thank you!
