### ISSUE TITLE
New installation

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#34]
Hello, thank you for this project. I have been unable to "build XO from sources".

I have a fresh Debian 9 VM on XCP-Ng. 2CPU 4GB RAM.

I don't know what pre-requisites there are for the installation to succeed.

I ran the Autoinstall but I have no web server on this VM. Which would I install? It is not mentioned.

Is the Docker container the correct path? I don't have Docker installed and I don't see any instructions to do so.

Perhaps a beta user's perspective (noob) is useful but I'd really like to get this working.

Thanks
D

**Comment by ronivay** [comment]
Hi,

You don’t need a webserver and autoinstall does install everything you need but it doesn’t touch your firewall settings. How did the install go? Last output? Any logs?

**Comment by dsiminiuk** [comment]
I went and installed Docker trying to find my way through and didn't get far, blew it up, then deleted it. I do know how to take snapshots, I swear.

I'm starting over with a new CentOS 7 minimal VM.  More to come...

**Comment by ronivay** [comment]
Yup the docker option isn’t really automated here at all and i probably should delete it from the script completely. 

The autoinstall is the one you want and shouldn’t require anything from you except to open software firewall in case VM has one out of the box.

Just take the output and logs (logfile is set in xo-install.cfg) in case installation fails for you.

**Comment by Bibi40k** [comment]
Hi,
i can give you something to fix :)
On CentOS it cannot find "libvhdi-tools". I think they stop offering support.


Can you please help me with the firewall, on Debian10 after checking these outputs ? 

From .log
`[fail] Looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details
root@xoa1:~/XenOrchestraInstallerUpdater# ^M
-bash: $'\r': command not found
root@xoa1:~/XenOrchestraInstallerUpdater# journalctl -u xo-server
-- Logs begin at Mon 2020-04-06 01:55:36 EDT, end at Mon 2020-04-06 02:04:08 EDT. --
Apr 06 02:04:04 xoa1 systemd[1]: Started XO Server.
Apr 06 02:04:05 xoa1 xo-server[13952]: internal/modules/cjs/loader.js:583
Apr 06 02:04:05 xoa1 xo-server[13952]:     throw err;
Apr 06 02:04:05 xoa1 xo-server[13952]:     ^
Apr 06 02:04:05 xoa1 xo-server[13952]: Error: Cannot find module 'bluebird'
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Module.require (internal/modules/cjs/loader.js:637:17)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at require (internal/modules/cjs/helpers.js:22:18)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-202006040201/packages/xo-server/bin/xo-server:21
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Apr 06 02:04:05 xoa1 xo-server[13952]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Apr 06 02:04:05 xoa1 systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 06 02:04:05 xoa1 systemd[1]: xo-server.service: Failed with result 'exit-code'.
Apr 06 02:04:05 xoa1 systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
Apr 06 02:04:05 xoa1 systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 1.
Apr 06 02:04:05 xoa1 systemd[1]: Stopped XO Server.
Apr 06 02:04:05 xoa1 systemd[1]: Started XO Server.
Apr 06 02:04:05 xoa1 xo-server[13966]: internal/modules/cjs/loader.js:583
root@xoa1:~/XenOrchestraInstallerUpdater# cat xo-install.log
Cloning into '/etc/xo/xo-src/xen-orchestra'...
./xo-install.sh: line 267: 13843 Segmentation fault      yarn > /dev/null
`

**Comment by ronivay** [comment]
> On CentOS it cannot find "libvhdi-tools". I think they stop offering support.

I'm unable to reproduce this on fresh CentOS installation. Libvhdi-tools install properly. Do you have any more details on this?

> Can you please help me with the firewall, on Debian10 after checking these outputs ?

According to the output there's no problem with firewall but something failed with yarn installation and therefore build was incomplete or something which prevents xo-server to start. Can you delete /etc/xo completely and run the installation from the start. Also make sure your VM has enough RAM to complete all tasks (3GB minimum, 4GB preferred).

**Comment by Bibi40k** [comment]
1. Revert from snapshot to clean install Debian10
2. Allocated 4GB
3. Rerun the script - exactly the same errors as before
4. Extra info (it was before but i did not posted). The script crashes on this step, with this message:
`[info] Starting xo-server...
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open

[fail] Looks like there was a problem when starting xo-server/reading journalctl. Please see logs                                                  for more details
`

I deleted CentOS installation, i can't give more details.

**Comment by ronivay** [comment]
Interesting. Not able to reproduce any of this. Just ran successful installation with both CentOS 7 and Debian 10 without issues.

Could you have something outside of your environment (firewall or some other network appliance) that could cause issues if you also failed to install the libvhdi-tools with CentOS which seems to work just fine?

**Comment by Bibi40k** [comment]
I'm on a pool with 2 servers, both running on a fresh install of XCP-ng 8.1
2 x 1GB NICs bonded connected to a router
2 x 10GB NICs bonded connected to a switch with the SR

**Comment by Bibi40k** [comment]
I've noticed that nodejs cannot be updated to v12, do you have any sollution for this ?

`nodejs is already the newest version (10.15.2~dfsg-2).`

**Comment by ronivay** [comment]
Was just going to ask your nodejs and yarn versions currently installed. That explains it, newer nodejs is then not installed and yarn fails. That needs to be removed.

**Comment by Bibi40k** [comment]
How can i solve this ?

**Comment by olivierlambert** [comment]
Maybe you should follow the official procedure to install XO from the sources?  https://xen-orchestra.com/docs/from_the_sources.html#packages-and-pre-requisites

**Comment by Bibi40k** [comment]
Thanks Olivier, i tried that too, follow the link and instructions manually

XO needs Node.js. Please use Node LTS.
We'll consider at this point that you've got a working node on your box. E.g:
$ node -v
v12.16.1
If not, see this page for instructions on how to install Node.

**Comment by ronivay** [comment]
> Maybe you should follow the official procedure to install XO from the sources? https://xen-orchestra.com/docs/from_the_sources.html#packages-and-pre-requisites

:) 

Guide also suggests using nodesource repository, which this script already does so doesn't really help.

**Comment by ronivay** [comment]
> How can i solve this ?

Try minimal Debian 10 base installation or remove that nodejs 10 package (lot of instructions all over the internet how to remove packages, i don't have any preference here), and try install procedure again or follow nodesource guide and install correct nodejs version manually and then run the script again.
https://github.com/nodesource/distributions/blob/master/README.md

**Comment by ronivay** [comment]
> How can i solve this ?

Please do a git pull on this repository and rerun installation. Possible nodejs v10 from debian 10 base repository will now be replaced with v12.

**Comment by Bibi40k** [comment]
I did and rerun, did not work. This is what i have manually tried.
There must be something else that doesn't allow nodejs to update to v12

**Comment by ronivay** [comment]
> I did and rerun, did not work. This is what i have manually tried.
> There must be something else that doesn't allow nodejs to update to v12

Do you see the ”installing node.js” in the script output? Can you verify you actually still have nodejs v10? How did the install fail now, same log lines?

**Comment by Bibi40k** [comment]
Still v10, i already did that at the begining.

`root@xoa1:~/XenOrchestraInstallerUpdater# node -v
v10.15.2
root@xoa1:~/XenOrchestraInstallerUpdater# curl -sL https://deb.nodesource.com/setup_12.x | bash -

## Installing the NodeSource Node.js 12.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_12.x buster InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 http://security.debian.org/debian-security buster/updates InRelease
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_12.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 12.x repo...

+ echo 'deb https://deb.nodesource.com/node_12.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_12.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 https://deb.nodesource.com/node_12.x buster InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Hit:5 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 12.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


root@xoa1:~/XenOrchestraInstallerUpdater# apt-get install -y nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (10.15.2~dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@xoa1:~/XenOrchestraInstallerUpdater# node -v
v10.15.2
`


```
1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 1

[ok] Running apt-get update

[ok] Installing apt-transport-https and ca-certificates packages to support https repos

[ok] Debian 10, so installing gnupg also

[ok] Installing node.js

[ok] Installing node.js

[ok] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils

[ok] Enabling and starting redis service

[ok] Enabling and starting rpcbind service

[info] Fetching Xen Orchestra source code

Updating 8424fc4c1..9a72c4014
Fast-forward
 CHANGELOG.unreleased.md               |  2 ++
 packages/xo-server-audit/config.toml  | 39 ---------------------------------------
 packages/xo-server-audit/package.json |  3 ---
 packages/xo-server-audit/src/index.js | 76 ++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------
 packages/xo-server/sample.config.toml |  8 ++++++++
 packages/xo-server/src/index.js       |  4 +++-
 yarn.lock                             |  4 ++--
 7 files changed, 65 insertions(+), 71 deletions(-)
 delete mode 100644 packages/xo-server-audit/config.toml

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202006040603
[info] Updating xen-orchestra from '8424fc4c1' to '9a72c4014'

[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file

[info] Adding WorkingDirectory parameter to systemd service configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration


[info] Starting xo-server...
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open
        waiting for port to be open

[fail] Looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details

```

**Comment by Bibi40k** [comment]
Wow, what an error ...
I probably was very sleepy/dizzy/drunk last night when i downloaded and installed Debian 32bit version

Although seems that NVP can compile the latest LTS nodejs, i start over ...

Sorry for wasting your time

**Comment by ronivay** [comment]
Heh no worries. At least i added that feature to update possibly existing nodejs v10 to v12 in debian 10 now :)

That explains it since there doesn't seem to be a 32bit package version available from nodesource repo. Maybe it can be compiled, haven't tried. Although i suggest you to get that 64bit version anyway to install on.

**Comment by Bibi40k** [comment]
It worked now :)

You can also add this check because when xoa deploys it only have 2GB so by instinct i first set it to use 2 :)

`# Check for required memory
totalk=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
if [ "$totalk" -lt "3000000" ]; then echo "XOA Requires at least 3GB Memory, 4GB recommended!"; exit 1; fi `

**Comment by ronivay** [comment]
Great!

There already is a similar warning shown in red when running the script if less than 3GB of memory. I decided not to exit when that happens. Up to user to decide if they want to continue anyway.

**Comment by ronivay** [comment]
> I went and installed Docker trying to find my way through and didn't get far, blew it up, then deleted it. I do know how to take snapshots, I swear.
> 
> I'm starting over with a new CentOS 7 minimal VM. More to come...

@dsiminiuk did you manage to finish the installation?

**Comment by dsiminiuk** [comment]
I built two versions of CentOS 7 and I was never able to even ping my gateway. I could ping other guests on the same LAN. Gave up for now.

Built a new Ubuntu 18 server, everything OK and I can ping my gateway too! 2 CPU 4 GB RAM.

Ran Autoinstall
[..] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils[fail] Something went wrong, exiting. Check ./xo-install.log

root@ubuntu:~/XenOrchestraInstallerUpdater# cat xo-install.log
E: Unable to locate package redis-server
E: Unable to locate package libvhdi-utils

add-apt-repository universe   <--maybe add this to the Autoinstall script

Re-running Autoinstall...

[ok] Running apt-get update
[ok] Installing apt-transport-https and ca-certificates packages to support https repos
[ok] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils
[ok] Enabling and starting redis service
[ok] Enabling and starting rpcbind service
[ok] Creating missing basedir to /etc/xo
[ok] Creating missing xo-builds directory to /etc/xo/xo-builds
[info] Fetching Xen Orchestra source code
[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202006041608
[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back
[..] Running installation
[info] No plugins to install
[info] Fixing binary path in systemd service configuration file
[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Fixing relative path to xo-web installation in xo-server configuration file
[info] Activating modified configuration file
[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web
[info] Replacing systemd service configuration file
[info] Reloading systemd configuration
[info] Starting xo-server...
        waiting for port to be open
        WebUI started in port 80. Make sure you have firewall rules in place to allow access.
        Default username: admin@admin.net password: admin
[info] Installation successful. Enabling xo-server to start on reboot

This is promising...

**Comment by ronivay** [comment]
> I built two versions of CentOS 7 and I was never able to even ping my gateway. I could ping other guests on the same LAN. Gave up for now.
> 
> Built a new Ubuntu 18 server, everything OK and I can ping my gateway too! 2 CPU 4 GB RAM.
> 
> Ran Autoinstall
> [..] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils[fail] Something went wrong, exiting. Check ./xo-install.log
> 
> root@ubuntu:~/XenOrchestraInstallerUpdater# cat xo-install.log
> E: Unable to locate package redis-server
> E: Unable to locate package libvhdi-utils
> 
> add-apt-repository universe <--maybe add this to the Autoinstall script

Hi,

Happy you got it to finish after all. These packages are in the base repository for ubuntu and debian so no need to add additional repositories. I don’t know what kind of setup you have so can’t really say why thise couldn’t be found. Unfortunately i’m not able to support every possible base image or environment and don’t even want to :) i trust that if people something out of the ordinary, they can also come up with a solution.
