### ISSUE TITLE
plugin selection

### ISSUE THREAD

**Issue by dsiminiuk** [ronivay/XenOrchestraInstallerUpdater#38]
I don't see a way to request a feature/enhancement so an issue it is... sorry!

When running an update or new installation, please add an option to select plugins from the available ones in the repo. Display the list of plugins that are already installed, those that are deprecated (no longer available) and available plugins which can be included in a build.

Enter a number to go to the plugins menu, then list them by number, enter a number in the list to toggle which will included or excluded in the build. The unavailable/deprecated would be force marked for removal if you proceed with a build.

**Comment by ronivay** [comment]
Hi,

Thanks for a suggestion. To me this sounds quite complicated and time consuming to implement considering the fact that it would be for addons only.

There’s already an option to install wanted plugins or just select all if nothing needs to be filtered out. Even though it requires some manual work to write down desired plugins, so would choosing plugins from a list and likely most people will still choose to install all of them if they don’t know what they actually want (and then it’s a small effort to edit the .cfg once when they do).

**Comment by dsiminiuk** [comment]
Agreed about the effort, it would just be a convenience.

My interest is in the discovery of new plugins and when to remove the deprecated without having to audit the list in the git package.

There are many I have no use for, auth-ldap, auth-github, auth-google, others, etc, so using PLUGINS="ALL" clutters up the XO plugins page and I wold like to keep it minimalistic to just what I use. This is my choice of course, so I'll continue in the old fashioned way.

Thanks for considering.
