### ISSUE TITLE
XO won't start after updating

### ISSUE THREAD

**Issue by peterg10** [ronivay/XenOrchestraInstallerUpdater#42]
Sorry, didn't note the old version of XO I was running but after a git pull it won't start. Not much to go on from `systemctl status`:

```systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-05-24 09:21:41 BST; 4h 27min ago
 Main PID: 1678 (code=exited, status=1/FAILURE)

May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Unit entered failed state.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: Stopped XO Server.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Start request repeated too quickly.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: Failed to start XO Server.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Unit entered failed state.
May 24 09:21:41 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Failed with result 'exit-code'.
```

There's some more detail in `journalctl -xe`though: 
```May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]: Error: Cannot find module 'bluebird'
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]: Require stack:
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]: - /etc/xo/xo-builds/xen-orchestra-202024050905/packages/xo-server/bin
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Module.require (internal/modules/cjs/loader.js:1019:19)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at require (internal/modules/cjs/helpers.js:77:18)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Object.<anonymous> (/etc/xo/xo-builds/xen-orchestra-2020240509
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Module.load (internal/modules/cjs/loader.js:977:32)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:   code: 'MODULE_NOT_FOUND',
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:   requireStack: [
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:     '/etc/xo/xo-builds/xen-orchestra-202024050905/packages/xo-server/
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]:   ]
May 24 14:05:34 xo.linuxplanet.co.uk xo-server[21798]: }
```

I also tried cloning the repo again and starting with a new install, that fails too:
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version
2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend expli
citly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json
`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```
I'm not sure if that's related to fail with my original install or something new.

I've no idea about node.js so I'm stuck.

**Comment by ronivay** [comment]
How was the old version installed? Git pull where and what doesn’t start? Sorry, little confused about what’s the situation here. I’d suggest you start with a fresh VM as it’s instructed in the readme.

**Comment by peterg10** [comment]
The original version (which has been successfully updated several times) was from a git clone of `https://github.com/ronivay/XenOrchestraInstallerUpdater.git` then `sudo ./xo-install`.
The VM OS hasn't been touched.

If I start with a new VM, will I lose all my XO configuration (tags, backup schedules, etc) ?

**Comment by ronivay** [comment]
Okay my bad then. Assumed this was the first time you used this script and there was some older version installed with some other means.

When was this updated last time? There has been a major change from node 8.x to 12.x quite recently. You can check this with node -v

**Comment by peterg10** [comment]
```
$ node -v
v12.16.3
```

**Comment by ronivay** [comment]
Okay, that’s correct. Could you then try to change branch to latest tagged branch (it’s explained inside cfg file) from xo-install.cfg and run update again.

**Comment by peterg10** [comment]
I changed to `BRANCH="release"` : 
```
$ sudo ./xo-install.sh --update

[ok] Checking updates for nodejs and yarn

[info] Fetching Xen Orchestra source code

Already up-to-date.

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202024051514
[info] Checking out latest tagged release 'xo-server-v5.51.1'

[info] Updating xen-orchestra from 'ec8df7ce5' to '876bb4898'

[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file

[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Fixing relative path to xo-web installation in xo-server configuration file
[info] Activating modified configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration


[info] Starting xo-server...
	waiting for port to be open
	waiting for port to be open
	waiting for port to be open
	waiting for port to be open
	waiting for port to be open
	waiting for port to be open

[fail] Looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details
```
Checking `journalctl`.....
```
May 24 15:16:15 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Start request repeated too quickly.
May 24 15:16:15 xo.linuxplanet.co.uk systemd[1]: Failed to start XO Server.
-- Subject: Unit xo-server.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit xo-server.service has failed.
--
-- The result is failed.
May 24 15:16:15 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Unit entered failed state.
May 24 15:16:15 xo.linuxplanet.co.uk systemd[1]: xo-server.service: Failed with result 'exit-code'.
```

In the XO troubleshooting documentation it suggests running:
rm -rf node_modules
yarn
yarn build
...in the build directory, I thought that was in `/opt/xo/xo-builds/` but there's nothing there.

**Comment by ronivay** [comment]
That depends what is the build directory defined in configuration. For you it seems to be /etc/xo

Removing node_modules most likely doesn’t help because they are installed from scratch to every new install/update.

Which OS are you running? I could test this out as well.

**Comment by peterg10** [comment]
Debian 10 x64

**Comment by ronivay** [comment]
I'm not able to reproduce this issue with fresh install of Debian 10. I don't have much to suggest based on logs provided here. First thought would be that yarn/node.js is out of date, but latter was already confirmed to be up to date. yarn should also be automatically updated when running update option from this script as long as AUTOUPDATE variable is set to true in cfg file, so probably not that either. One test you could do is to move /etc/xo completely to different name and remove that systemd service file from /etc/systemd/system/xo-server.service and run install, but if that doesn't help either it is most likely something related to dependencies but not entirely clear which one.

I assume you didn't change anything in the cfg file or anywhere else before running the failed update first time?

**Comment by peterg10** [comment]
I've never touched the .cfg file. I've always followed the same procedure, running `xo-install.sh` and selecting the update option.

I've rolled back to a working XO VM snapshot from before the upgrade and will try the same steps again. In the working pre-upgrade snapshot, `AUTOUPDATE=true` so it would have been that way before too.

**Comment by ronivay** [comment]
Okay. If you still encounter the same issues, you might want to try and do a generic dist-upgrade if there is an issue with some of the dependencies which i doubt though, but not too many options here.

**Comment by okynnor** [comment]
I second @peterg10 findings.  Like him, I have been running an older version of this script.  This time, it stopped the upgraded at the plugin named auth-ldap plugin.  So I then upgraded this script the latest version.  It upgraded perfectly but XO doesn't run properly in the sense that there is no login screen.  

I reverted to a prior night snapshot of the VM just to run the prior version before the latest available XO upgraded (i.e. 5.47). 

If there's any more questions that I can help answer or test the script, let me know.

**Comment by ronivay** [comment]
> I second @peterg10 findings. Like him, I have been running an older version of this script. This time, it stopped the upgraded at the plugin named auth-ldap plugin. So I then upgraded this script the latest version. It upgraded perfectly but XO doesn't run properly in the sense that there is no login screen.
> 
> I reverted to a prior night snapshot of the VM just to run the prior version before the latest available XO upgraded (i.e. 5.47).
> 
> If there's any more questions that I can help answer or test the script, let me know.

Are you running Debian 10 as well? Could you grab the commits from this script git directory and from working installation xen orchestra source directory. Latter should is in $INSTALLDIR/xo-builds/xen-orchestra-date. You can verify the currently in use date directory by checking where the symlink it $INSTALLDIR/xo-server or $INSTALLDIR/xo-web points to. $INSTALLDIR is defined in your xo-install.cfg file.

Command to run is: git rev-parse HEAD

**Comment by okynnor** [comment]
I am running: 
ronny@xo-ce:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

from xo-install.cfg: 
# Base dir for installation and future updates
INSTALLDIR="/etc/xo"

Hope I didn't miss something. Happy to help.

**Comment by ronivay** [comment]
Okay, just run below command inside the XenOrchestraInstallerUpdater directory and inside /etc/xo/xo-builds/xen-orchestra-202030041501 

`git rev-parse HEAD`

If you try the update again and it fails to start, also attach the output from command 
`journalctl -u xo-server -n 100`

**Comment by okynnor** [comment]
Ran: git rev-parse HEAD
output: 5a5837b8ed5ee77c5c62720bb3a155af449ecac5

should I update by using the old or the new script?

**Comment by ronivay** [comment]
Please run the git command in both directories mentioned above.

Test the update with most recent version.

Can you confirm that xo-server version, is it really 5.47 as you mentioned earlier?

**Comment by okynnor** [comment]
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ git rev-parse HEAD
223b56120d528425c5923590a31d47b9e44b3acc

ronny@xo-ce:/etc/xo/xo-builds/xen-orchestra-202030041501$ git rev-parse HEAD
5a5837b8ed5ee77c5c62720bb3a155af449ecac5

Currently running version: xo-server 5.59.0

**Comment by ronivay** [comment]
Thank you. Hmm interesting that it worked now :) maybe these two issues aren’t related after all.

**Comment by ronivay** [comment]
@peterg10 

If you're still having issues with this. I just added a big commit which refactored the whole logging logic and installation logfile should have plenty of more information now about what could've gone wrong. Logs now go to their own separate log directory and each install/update task has own logfile.

**Comment by ronivay** [comment]
Please reopen issue if there is still problems to install and provide the logfile which has plenty of information now for debugging.

**Comment by eBeagle** [comment]
I have a similar problem upgrading from a previous version of the script on a Debian 9 VM with NodeJS 8 installed.

It seems the logic to update ```nodejs``` and ```yarn``` doesn't take into account that a new repository pointing to the new version 12 needs to be added to ```/etc/apt/sources.list.d```. Therefore when the script runs ```apt-get install -y --only-upgrade nodejs yarn``` it simply looks for the latest version on the current repository and doesn't update the packages.

If I remove both packages (``` apt remove nodejs yarn```) and choose option 1 to AutoInstall  the logic in the new script first tests if ```yarn``` is the latest version and installs its latest version otherwise, but ```nodejs``` is installed as a dependency:
```
=== CMD ===: apt-get install -y yarn

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  nodejs
The following NEW packages will be installed:
  nodejs yarn
0 upgraded, 2 newly installed, 0 to remove and 15 not upgrade.
```
Because ```nodejs``` repository at ```/etc/apt/sources.list.d``` is still pointing to version 8 the new version of ```yarn``` is installed but the old version of ```nodejs``` is re-installed as a dependency.

My suggestion is to tweak the logic in both the installation and autoupdate parts of script to first test whether each package ```nodejs``` and ```yarn``` needs updating to the latest version, then add the new repositories to ```/etc/apt/sources.list.d``` and finally run ```apt install``` for the packages that need to be installed/updated.

The only problem is that the test for the latest version may need to be updated every time a new version is released, so the script can point to the correct repositories.

**Comment by okynnor** [comment]
something has definitely changed.  I ran sudo ./xo-install.sh, 
the script seemed that it ran successfully without any errors
but on restart Xen-orchestra website can't load (i.e. no login screen)

**Comment by ronivay** [comment]
@eBeagle thanks. I’ll make a fix for that asap.

@okynnor this issue is closed and already has like three different issues scrambled in it. Could you please open up a new issue and give details asked in the template. Information in your message here doesn’t really give me anything to work with.

**Comment by ronivay** [comment]
@eBeagle 

https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/d1a7f2bda2f3bbfd513b2914012d87b03292d920

node.js major version should now be upgraded when running update if AUTOUPDATE variable is set to true in configuration file.

**Comment by eBeagle** [comment]
Thank you @ronivay the update is now working, but if you select Autoinstall in a system where an older version of ```nodejs``` and/or ```yarn``` are installed their versions are not updated and the installation fails.

The code only checks whether a version is installed:
```
# only run automated node install if executable not found
cmdlog "which node"
cmdlog "which npm"
if [[ -z $(which node 2>>$LOGFILE) ]] || [[ -z $(which npm 2>>$LOGFILE) ]]; then
```
and
```
# only install yarn repo and package if not found
cmdlog "which yarn"
if [[ -z $(which yarn 2>>$LOGFILE) ]]; then
```
Since the installation fails if a version of ```nodejs``` older than 12 is used, my suggestion is to check ```nodejs``` and ```yarn``` versions for any OS version like you currently do for Debian 10 and update their versions accordingly to the min required version.

If you don't want to change the system automatically you could use the AUTOUPDATE variable on the Autoinstall option as well.

Another suggestion for further enhancement is to include the value of AUTOUPDATE in the list of options that will be used for installation.

**Comment by ronivay** [comment]
Yeah i noticed this while working with the update feature and was planning some elegant way to achieve it :) it’s anyway suggested to use a fresh minimal install of a VM which shouldn’t then have node.js already so wasn’t rushing with this. Will fix it soonish though.

**Comment by eBeagle** [comment]
No worries. The script is working fine. It's more a question of fine tuning. ;-)

**Comment by okynnor** [comment]
@ronivay You know it is easier, as I noted earlier, to delete the folder and reclone the Git repository than to waste a whole bunch to time with a "fresh minimal install of a VM"

**Comment by ronivay** [comment]
> @ronivay You know it is easier, as I noted earlier, to delete the folder and reclone the Git repository than to waste a whole bunch to time with a "fresh minimal install of a VM"

I'm sure it is. I'm not talking about a situation where debugging after failed installation. I'm referring to the usual use case when everything is working fine. There really is no reason to run install option more than once and updates after that. First install should be performed to a fresh minimal installation as stated in instructions.

**Comment by ronivay** [comment]
@eBeagle 

node.js will now be upgraded during install as well if autoupdate is set to true

https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/28453b3e0d84d60ee98b7c5d9f8a775a7ad11943

**Comment by eBeagle** [comment]
Yes, it's working now. Thank you for the updates.
