### ISSUE TITLE
Script incorrectly reports key as not being a PEM RSA private key file

### ISSUE THREAD

**Issue by evan-swinney** [ronivay/XenOrchestraInstallerUpdater#43]
**Debian 10 Buster**:

**Issue**
Using a minimalist install on Debian 10, after cloning the repo and creating a self-signed certificate in `/etc/ssl/xo/`, and providing the correct path within `xo-install.cfg` (copied from sample) to the generated keys via:
```
PATH_TO_HTTPS_CERT=/etc/ssl/xo/xo.crt
PATH_TO_HTTPS_KEY=/etc/ssl/xo/xo.key
```
The script reported this error:
```
[fail] /etc/ssl/xo/xo.key doesn't look like PEM RSA private key file. Please check file or remove HTTPS settings from ./xo-install.cfg and try again
```
I generated the self-signed cert via within the `/etc/ssl/xo/` directory:
```
openssl req -newkey rsa:4096 \
            -x509 \
            -sha256 \
            -days 3650 \
            -nodes \
            -out xo.crt \
            -keyout xo.key
```
I narrowed it down to line 689 on commit https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/345f28aadb80a37ad08a50a908e4a705e6faba98. The call to `file -s $PATH_TO_HTTPS_KEY` incorrectly identifies the file as `ASCII text`. I know this is most likely a problem with `file -s` on my system. What confuses me is that this was a stock install of Debian 10 Buster, and the system was stock aside from setting up the self signed certificate and installing `git`.

On my system, I commented out the two if statements in `function CheckCertificate` and was able to successfully launch the script and install Xen Orchestra.

Perhaps a different method of checking the keys is in order?

**Installation logfile**
No log was generated.

**Comment by ronivay** [comment]
Hello,

Thank you. My bad for assuming file program to work from deb package is at does with rpm. 

Interestingly i found a bug report about file program not recognizing openssh/openssl keys from 2007 which was then fixed.

I removed that check for now. Anyway that was more like an extra check and not absolutely necessary, there are other checks for ssl key/cert still in place.

I'll see if there's any other way to accomplish what i wanted to do there.
