### ISSUE TITLE
[info] Creating install directory: /opt/xo/xo-builds/xen-orchestra-202030050027[fail]

### ISSUE THREAD

**Issue by mathieusibilla** [ronivay/XenOrchestraInstallerUpdater#44]
**OS Version**: Debian 10
**Node.js version**: v12.17.0
**NPM version**: 6.14.4

**Server specs**
6 vCPUs and 6GiB RAM 

**Issue**
Followed the instruction found on Lawrence syste to use your script and ran into a failed to create install directory /opt/xo/xo-builds/xen-orchestra-202030050027

**Installation logfile**
```
copy and paste the output from xo-install.log (by default)
```
**xo-server.service log**
```
copy and paste the output (if available) from command journalctl -u xo-server -n 100
root@debian:~/XenOrchestraInstallerUpdater# journalctl -u xo-server -n 100
-- Logs begin at Fri 2020-05-29 23:37:12 BST, end at Sat 2020-05-30 00:29:41 BST. --
May 29 23:54:42 debian xo-server[14934]:     at Object.<anonymous> (/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server:21:18)
May 29 23:54:42 debian xo-server[14934]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
May 29 23:54:42 debian xo-server[14934]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
May 29 23:54:42 debian xo-server[14934]:     at Module.load (internal/modules/cjs/loader.js:986:32)
May 29 23:54:42 debian xo-server[14934]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
May 29 23:54:42 debian xo-server[14934]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
May 29 23:54:42 debian xo-server[14934]:   code: 'MODULE_NOT_FOUND',
May 29 23:54:42 debian xo-server[14934]:   requireStack: [
May 29 23:54:42 debian xo-server[14934]:     '/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server'
May 29 23:54:42 debian xo-server[14934]:   ]
May 29 23:54:42 debian xo-server[14934]: }
May 29 23:54:42 debian systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 29 23:54:42 debian systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 29 23:54:42 debian systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
May 29 23:54:42 debian systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 2.
May 29 23:54:42 debian systemd[1]: Stopped XO Server.
May 29 23:54:42 debian systemd[1]: Started XO Server.
May 29 23:54:42 debian xo-server[14941]: internal/modules/cjs/loader.js:969
May 29 23:54:42 debian xo-server[14941]:   throw err;
May 29 23:54:42 debian xo-server[14941]:   ^
May 29 23:54:42 debian xo-server[14941]: Error: Cannot find module 'bluebird'
May 29 23:54:42 debian xo-server[14941]: Require stack:
May 29 23:54:42 debian xo-server[14941]: - /opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server
May 29 23:54:42 debian xo-server[14941]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
May 29 23:54:42 debian xo-server[14941]:     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
May 29 23:54:42 debian xo-server[14941]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
May 29 23:54:42 debian xo-server[14941]:     at require (internal/modules/cjs/helpers.js:72:18)
May 29 23:54:42 debian xo-server[14941]:     at Object.<anonymous> (/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server:21:18)
May 29 23:54:42 debian xo-server[14941]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
May 29 23:54:42 debian xo-server[14941]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
May 29 23:54:42 debian xo-server[14941]:     at Module.load (internal/modules/cjs/loader.js:986:32)
May 29 23:54:42 debian xo-server[14941]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
May 29 23:54:42 debian xo-server[14941]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
May 29 23:54:42 debian xo-server[14941]:   code: 'MODULE_NOT_FOUND',
May 29 23:54:42 debian xo-server[14941]:   requireStack: [
May 29 23:54:42 debian xo-server[14941]:     '/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server'
May 29 23:54:42 debian xo-server[14941]:   ]
May 29 23:54:42 debian xo-server[14941]: }
May 29 23:54:42 debian systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 29 23:54:42 debian systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 29 23:54:42 debian systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
May 29 23:54:42 debian systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
May 29 23:54:42 debian systemd[1]: Stopped XO Server.
May 29 23:54:42 debian systemd[1]: Started XO Server.
May 29 23:54:42 debian xo-server[14948]: internal/modules/cjs/loader.js:969
May 29 23:54:42 debian xo-server[14948]:   throw err;
May 29 23:54:42 debian xo-server[14948]:   ^
May 29 23:54:42 debian xo-server[14948]: Error: Cannot find module 'bluebird'
May 29 23:54:42 debian xo-server[14948]: Require stack:
May 29 23:54:42 debian xo-server[14948]: - /opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server
May 29 23:54:42 debian xo-server[14948]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
May 29 23:54:42 debian xo-server[14948]:     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
May 29 23:54:42 debian xo-server[14948]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
May 29 23:54:42 debian xo-server[14948]:     at require (internal/modules/cjs/helpers.js:72:18)
May 29 23:54:42 debian xo-server[14948]:     at Object.<anonymous> (/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server:21:18)
May 29 23:54:42 debian xo-server[14948]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
May 29 23:54:42 debian xo-server[14948]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
May 29 23:54:42 debian xo-server[14948]:     at Module.load (internal/modules/cjs/loader.js:986:32)
May 29 23:54:42 debian xo-server[14948]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
May 29 23:54:42 debian xo-server[14948]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
May 29 23:54:42 debian xo-server[14948]:   code: 'MODULE_NOT_FOUND',
May 29 23:54:42 debian xo-server[14948]:   requireStack: [
May 29 23:54:42 debian xo-server[14948]:     '/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server'
May 29 23:54:42 debian xo-server[14948]:   ]
May 29 23:54:42 debian xo-server[14948]: }
May 29 23:54:42 debian systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 29 23:54:42 debian systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 29 23:54:42 debian systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
May 29 23:54:42 debian systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
May 29 23:54:42 debian systemd[1]: Stopped XO Server.
May 29 23:54:42 debian systemd[1]: Started XO Server.
May 29 23:54:43 debian xo-server[14955]: internal/modules/cjs/loader.js:969
May 29 23:54:43 debian xo-server[14955]:   throw err;
May 29 23:54:43 debian xo-server[14955]:   ^
May 29 23:54:43 debian xo-server[14955]: Error: Cannot find module 'bluebird'
May 29 23:54:43 debian xo-server[14955]: Require stack:
May 29 23:54:43 debian xo-server[14955]: - /opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server
May 29 23:54:43 debian xo-server[14955]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
May 29 23:54:43 debian xo-server[14955]:     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
May 29 23:54:43 debian xo-server[14955]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
May 29 23:54:43 debian xo-server[14955]:     at require (internal/modules/cjs/helpers.js:72:18)
May 29 23:54:43 debian xo-server[14955]:     at Object.<anonymous> (/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server:21:18)
May 29 23:54:43 debian xo-server[14955]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
May 29 23:54:43 debian xo-server[14955]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
May 29 23:54:43 debian xo-server[14955]:     at Module.load (internal/modules/cjs/loader.js:986:32)
May 29 23:54:43 debian xo-server[14955]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
May 29 23:54:43 debian xo-server[14955]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
May 29 23:54:43 debian xo-server[14955]:   code: 'MODULE_NOT_FOUND',
May 29 23:54:43 debian xo-server[14955]:   requireStack: [
May 29 23:54:43 debian xo-server[14955]:     '/opt/xo/xo-builds/xen-orchestra-202029052353/packages/xo-server/bin/xo-server'
May 29 23:54:43 debian xo-server[14955]:   ]
May 29 23:54:43 debian xo-server[14955]: }
May 29 23:54:43 debian systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 29 23:54:43 debian systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 29 23:54:43 debian systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
May 29 23:54:43 debian systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
May 29 23:54:43 debian systemd[1]: Stopped XO Server.
May 29 23:54:43 debian systemd[1]: xo-server.service: Start request repeated too quickly.
May 29 23:54:43 debian systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 29 23:54:43 debian systemd[1]: Failed to start XO Server.

**Comment by ronivay** [comment]
Hi,

If it really failed to that part on your first install, you wouldn’t have that xo-server service at all. So please fill in all the information asked in the issue template. Was this the first install or an update and what was the final outcome/what have you already tried to do? Copy the output from xo-install.log also which is now missing.

**Comment by mathieusibilla** [comment]
Hi, It is the first install, I've loaded xcp-ng late last night (Debian Buster running for 9 hours now), I do have the XOA instance installed (via the deploy script). it is the first time I tried your script
root@debian:~/XenOrchestraInstallerUpdater# nano xo-install.log opens a blank file with no content at all.
I can upload the whole terminal session from my very first login on the Debian VM.

**Comment by ronivay** [comment]
Hi,

Okay. I'm trying to understand how can you have the xo-server.service there if the installation script failed at the stage where it's trying to create the install directory. There really isn't anything installed at that stage. If you still have the script output, that would be helpful.

I assume you aren't running this against the XOA VM right?

**Comment by ronivay** [comment]
If you're still having issues with this and you're not using the XOA VM, then do a git pull of this script and run it again. Logging got a big overhaul and logs are in their own logs directory.

**Comment by mathieusibilla** [comment]
Hi, last night was the very first time I tried to install xcp-ng and using your script.

What do you mean by running against the XOA VM? (sorry if this is a dumb question)

**Comment by ronivay** [comment]
Just wanted to make sure you're not trying to use this script on the XOA VM aka Xen Orchestra Virtual Appliance, but you aren't so that's fine.

But please update this script repo and try again in case you haven't got it to work still. Logfile should have a lot more information about what is going wrong if it still fails. Just notice that the logfile path changed also, you can check logfile path from the output of the script when you start it before hitting 1 for autoinstall.

**Comment by mathieusibilla** [comment]
Hi,

Just tried again and the same error came up, here is what I have done and the output of /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041

root@debian:~# git clone https://github.com/ronivay/XenOrchestraInstallerUpdater.git
fatal: destination path 'XenOrchestraInstallerUpdater' already exists and is not an empty directory.
root@debian:~# rm -r XenOrchestraInstallerUpdater/
root@debian:~# ls -al
total 28
drwx------  4 root root 4096 May 30 20:40 .
drwxr-xr-x 18 root root 4096 May 29 23:16 ..
-rw-------  1 root root 1219 May 30 08:58 .bash_history
-rw-r--r--  1 root root  570 Jan 31  2010 .bashrc
drwxr-xr-x  3 root root 4096 May 29 23:54 .config
drwxr-xr-x  3 root root 4096 May 30 00:37 .local
-rw-r--r--  1 root root  148 Aug 17  2015 .profile
root@debian:~# git clone https://github.com/ronivay/XenOrchestraInstallerUpdater.git
Cloning into 'XenOrchestraInstallerUpdater'...
remote: Enumerating objects: 166, done.
remote: Counting objects: 100% (166/166), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 546 (delta 98), reused 94 (delta 43), pack-reused 380
Receiving objects: 100% (546/546), 123.22 KiB | 824.00 KiB/s, done.
Resolving deltas: 100% (317/317), done.
root@debian:~# ls -al
total 32
drwx------  5 root root 4096 May 30 20:40 .
drwxr-xr-x 18 root root 4096 May 29 23:16 ..
-rw-------  1 root root 1219 May 30 08:58 .bash_history
-rw-r--r--  1 root root  570 Jan 31  2010 .bashrc
drwxr-xr-x  3 root root 4096 May 29 23:54 .config
drwxr-xr-x  3 root root 4096 May 30 00:37 .local
-rw-r--r--  1 root root  148 Aug 17  2015 .profile
drwxr-xr-x  5 root root 4096 May 30 20:41 XenOrchestraInstallerUpdater
root@debian:~# cd XenOrchestraInstallerUpdater/
root@debian:~/XenOrchestraInstallerUpdater# ls -al
total 108
drwxr-xr-x 5 root root  4096 May 30 20:41 .
drwx------ 5 root root  4096 May 30 20:40 ..
drwxr-xr-x 8 root root  4096 May 30 20:41 .git
drwxr-xr-x 3 root root  4096 May 30 20:41 .github
-rw-r--r-- 1 root root   212 May 30 20:41 .gitignore
-rw-r--r-- 1 root root 35147 May 30 20:41 LICENSE
-rw-r--r-- 1 root root  4371 May 30 20:41 README.md
-rw-r--r-- 1 root root  1426 May 30 20:41 sample.xo-install.cfg
drwxr-xr-x 5 root root  4096 May 30 20:41 tests
-rwxr-xr-x 1 root root 34349 May 30 20:41 xo-install.sh
root@debian:~/XenOrchestraInstallerUpdater# ./xo-install.sh 
-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Debian 10 
Basedir: /opt/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041 for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 1

[ok] Running apt-get update

[ok] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils, curlls, curl

[ok] Installing apt-transport-https and ca-certificates packages to support https repos

[ok] Debian 10, so installing gnupg also

[ok] Installing setcap

[ok] Enabling and starting redis service

[ok] Enabling and starting rpcbind service

[info] Fetching Xen Orchestra source code

[info] Creating install directory: /opt/xo/xo-builds/xen-orchestra-202030052041[fail] Something went wrong, exiting. Check /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041 for more details and use rollback feature if needed
[fail] Removing /opt/xo/xo-builds/xen-orchestra-202030052041 because of failed installation.
./xo-install.sh: line 79: echo: write error: No space left on device
root@debian:~/XenOrchestraInstallerUpdater# cd /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041
bash: cd: /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041: Not a directory
root@debian:~/XenOrchestraInstallerUpdater# nano /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041

  GNU nano 3.2                                                   /root/XenOrchestraInstallerUpdater/logs/xo-install.log-202030052041                                                              

The following packages were automatically installed and are no longer required:
  libbrotli1 libc-ares2 libuv1 nodejs-doc
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
=== CMD ===: apt-get install -y apt-transport-https ca-certificates

Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20190110).
apt-transport-https is already the newest version (1.8.2.1).
The following packages were automatically installed and are no longer required:
  libbrotli1 libc-ares2 libuv1 nodejs-doc
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
=== CMD ===: apt-get install gnupg -y

Reading package lists...
Building dependency tree...
Reading state information...
gnupg is already the newest version (2.2.12-1+deb10u1).
The following packages were automatically installed and are no longer required:
  libbrotli1 libc-ares2 libuv1 nodejs-doc
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
=== CMD ===: which setcap

=== CMD ===: apt-get install -y libcap2-bin

Reading package lists...
Building dependency tree...
Reading state information...
libcap2-bin is already the newest version (1:2.25-2).
The following packages were automatically installed and are no longer required:
  libbrotli1 libc-ares2 libuv1 nodejs-doc
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
=== CMD ===: which yarn

=== CMD ===: which node

=== CMD ===: which npm

=== CMD ===: /bin/systemctl enable redis-server && /bin/systemctl start redis-server

Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
=== CMD ===: /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind

Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
=== CMD ===: cd "/opt/xo/xo-src/xen-orchestra"

=== CMD ===: git pull

Already up to date.
=== CMD ===: cd .

=== CMD ===: rm -rf "/opt/xo/xo-builds/xen-orchestra-202030052041"

=== CMD ===: cp -r "/opt/xo/xo-src/xen-orchestra /opt/xo/xo-builds/xen-orchestra-202030052041"

cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/objects/pack/pack-b674410590303a6b2b0feadbe1795c33f75f9b4b.pack': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/objects/pack/pack-b674410590303a6b2b0feadbe1795c33f75f9b4b.idx': No space left on device
cp: cannot create directory '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/objects/info': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/config': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/packed-refs': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/HEAD': No space left on device
cp: cannot create directory '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/logs': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.git/FETCH_HEAD': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.editorconfig': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.env.example': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.eslintrc.js': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.flowconfig': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.gitignore': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.prettierrc.js': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/.travis.yml': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/CHANGELOG.md': No space left on device
cp: error writing '/opt/xo/xo-builds/xen-orchestra-202030052041/CHANGELOG.unreleased.md': No space left on device
cp: error writing '/opt/xo/

**Comment by ronivay** [comment]
Hi,

Okay that explains it. No space left on device is kinda self explanatory. You are running out of disk space so it can’t copy the sources there.

**Comment by mathieusibilla** [comment]
it did hit me in the face as it showed on the screen!
How big would you recommend?

**Comment by ronivay** [comment]
Start with 20GB for example an increase later on if needed.

**Comment by mathieusibilla** [comment]
I had a Ubuntu VM ready to spin up with 40GB and it worked straight away. Many thanks for all your help.

**Comment by ronivay** [comment]
I added a free disk space check to the script so that something like this is more obvious.
