### ISSUE TITLE
Update failing with latest XO Build

### ISSUE THREAD

**Issue by biggen1684** [ronivay/XenOrchestraInstallerUpdater#45]
Update seems to be failing to console with this error message:

`./xo-install.sh: line 347: PLUGINS: unbound variable`

The log file doesn't show any error messages at all.  This is with a fresh `git pull` of your repo.

I'm able to roll back without any issue.  This is a Debian 10 VM by the way.

**Comment by ronivay** [comment]
Hi,

Script exited because of missing variable, so that doesn't end up to logs. Reason was a recent change to exit the script when there's some missing variable but i forgot to make a workaround for plugins since it's instructed to comment out completely if not needed. Should be fixed now.
