### ISSUE TITLE
Install on 2GB vm

### ISSUE THREAD

**Issue by hoerup** [ronivay/XenOrchestraInstallerUpdater#47]
It is possible to install XO on a 2GB vm but you need to override nodejs' memory autodetect system

export NODE_OPTIONS='--max-old-space-size=3072'

that way nodejs can grow beyond installed ram and it's up to operating system to use the swap system where necessary

**Comment by hoerup** [comment]
It is possible to limit the mem requirements a bit by forcing gulp to run in serial mode:

```
--- xo-install.sh       2020-06-04 13:45:57.706146778 +0200
+++ xo-install.sh_new   2020-06-04 13:45:51.033421811 +0200
@@ -523,7 +523,7 @@
        echo
        printprog "Running installation"
        cmdlog "cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME && yarn  && yarn build"
-       cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME >>$LOGFILE 2>&1 && yarn >>$LOGFILE 2>&1 && yarn build >>$LOGFILE 2>&1
+       cd $INSTALLDIR/xo-builds/xen-orchestra-$TIME >>$LOGFILE 2>&1 && sed -i 's/gulp.parallel/gulp.series/g' packages/xo-web/gulpfile.js && yarn >>$LOGFILE 2>&1 && yarn build >>$LOGFILE 2>&1
        printok "Running installation"

        # Install plugins
```

**Comment by ronivay** [comment]
Yes it is, but there's simply no guarantees that it will work. Script isn't enforcing any specific memory limit, only gives a warning about it so nothing is preventing an experienced user to tinker with their nodejs settings. I have no interest really to support this approach.
