### ISSUE TITLE
Update succeeds but web interface not running.

### ISSUE THREAD

**Issue by okynnor** [ronivay/XenOrchestraInstallerUpdater#49]
**OS Version**:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Node.js version**: node -v

v8.17.0

**Yarn version**: yarn -v

1.21.1

**Server specs**
amount of vCPUs: 2
RAM: 1GB

**Issue**

attempted to update Xen Orchestra. It was successful but in reality, the web interface doesn't come up. 

**Installation logfile**

Last login: Sat Jun  6 04:42:15 2020
ronny@xo-ce:~$ cd XenOrchestraInstallerUpdater/
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ ls
LICENSE    sample.xo-install.cfg  xo-install.cfg      xo-install.log
README.md  tests                  xo-install.cfg.old  xo-install.sh
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo nano xo-install.cfg
[sudo] password for ronny: 
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo ./xo-install.sh 
[sudo] password for ronny: 
Sorry, try again.
[sudo] password for ronny: 

WARNING: you have less than 3GB of RAM in your system. Installation might run out of memory

-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Ubuntu 18 
Basedir: /etc/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to ./xo-install.log for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 4
Which installation to roll back?

1) /etc/xo/xo-builds/xen-orchestra-202030041501
2) /etc/xo/xo-builds/xen-orchestra-202001040443
3) /etc/xo/xo-builds/xen-orchestra-202016042132
Pick a number. CTRL+C to exit: ^C
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo ./xo-install.sh 

WARNING: you have less than 3GB of RAM in your system. Installation might run out of memory

-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Ubuntu 18 
Basedir: /etc/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to ./xo-install.log for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 1
Looks like xo-server process is already running, consider running update instead. Continue anyway?
[y/N]: 
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo ./xo-install.sh 

WARNING: you have less than 3GB of RAM in your system. Installation might run out of memory

-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Ubuntu 18 
Basedir: /etc/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to ./xo-install.log for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 2

[ok] Checking updates for nodejs and yarn

[info] Fetching Xen Orchestra source code

Updating 6212109fc..c1d588264
Fast-forward
 .prettierrc.js                                     |    2 +-
 @vates/decorate-with/README.md                     |   45 +
 @vates/decorate-with/USAGE.md                      |   12 +
 @vates/decorate-with/index.js                      |    4 +
 @vates/decorate-with/package.json                  |   30 +
 @vates/parse-duration/README.md                    |   47 +
 @vates/parse-duration/USAGE.md                     |   14 +
 .../parse-duration/index.js                        |    4 +-
 @vates/parse-duration/package.json                 |   32 +
 @vates/read-chunk/README.md                        |    4 +-
 @vates/read-chunk/package.json                     |    4 +
 @xen-orchestra/async-map/README.md                 |    4 +-
 @xen-orchestra/async-map/package.json              |    6 +-
 @xen-orchestra/audit-core/README.md                |    4 +-
 @xen-orchestra/audit-core/package.json             |    6 +-
 @xen-orchestra/babel-config/README.md              |    2 +-
 @xen-orchestra/babel-config/index.js               |    2 +-
 @xen-orchestra/babel-config/package.json           |    6 +-
 @xen-orchestra/backups-cli/README.md               |    4 +-
 @xen-orchestra/backups-cli/_composeCommands.js     |    2 +-
 @xen-orchestra/backups-cli/commands/clean-vms.js   |   12 +-
 @xen-orchestra/backups-cli/package.json            |    6 +-
 @xen-orchestra/backups/README.md                   |    4 +-
 @xen-orchestra/backups/package.json                |    8 +-
 @xen-orchestra/cr-seed-cli/README.md               |    4 +-
 @xen-orchestra/cr-seed-cli/index.js                |    2 +-
 @xen-orchestra/cr-seed-cli/package.json            |    6 +-
 @xen-orchestra/cron/README.md                      |    4 +-
 @xen-orchestra/cron/package.json                   |    6 +-
 @xen-orchestra/defined/README.md                   |    4 +-
 @xen-orchestra/defined/package.json                |    6 +-
 @xen-orchestra/emit-async/README.md                |    6 +-
 @xen-orchestra/emit-async/USAGE.md                 |    2 +-
 @xen-orchestra/emit-async/package.json             |    6 +-
 @xen-orchestra/fs/README.md                        |    4 +-
 @xen-orchestra/fs/package.json                     |   10 +-
 @xen-orchestra/fs/src/_mount.js                    |    5 +-
 @xen-orchestra/fs/src/abstract.js                  |    2 +-
 @xen-orchestra/fs/src/fs.spec.js                   |    2 +-
 @xen-orchestra/log/README.md                       |    4 +-
 @xen-orchestra/log/package.json                    |    6 +-
 @xen-orchestra/log/src/configure.js                |    6 +-
 @xen-orchestra/log/src/index.js                    |    6 +-
 @xen-orchestra/log/src/utils.js                    |    5 +-
 @xen-orchestra/mixin/README.md                     |    4 +-
 @xen-orchestra/mixin/package.json                  |    6 +-
 @xen-orchestra/self-signed/README.md               |    4 +-
 @xen-orchestra/self-signed/package.json            |    6 +-
 @xen-orchestra/template/README.md                  |    4 +-
 @xen-orchestra/template/package.json               |    6 +-
 @xen-orchestra/upload-ova/README.md                |    2 +-
 @xen-orchestra/upload-ova/package.json             |   12 +-
 @xen-orchestra/upload-ova/src/config.js            |    2 +-
 @xen-orchestra/upload-ova/src/index.js             |    2 +-
 CHANGELOG.md                                       |   12 +-
 CHANGELOG.unreleased.md                            |   24 +-
 docs/.vuepress/config.js                           |    1 +
 docs/SUMMARY.md                                    |   82 -
 docs/acls.md                                       |    6 +-
 docs/advanced.md                                   |   42 +-
 docs/architecture.md                               |  248 +-
 docs/assets/delta_final.png                        |  Bin 0 -> 200457 bytes
 docs/assets/deltamerge1.png                        |  Bin 0 -> 202958 bytes
 docs/assets/deltamerge2.png                        |  Bin 0 -> 209319 bytes
 docs/assets/loadbalance1.png                       |  Bin 0 -> 18108 bytes
 docs/assets/loadbalance3.png                       |  Bin 0 -> 22168 bytes
 docs/assets/loadbalance4.png                       |  Bin 0 -> 29875 bytes
 docs/assets/nodelta.png                            |  Bin 0 -> 154390 bytes
 docs/assets/withoutproxy.png                       |  Bin 0 -> 274764 bytes
 docs/assets/withproxy.png                          |  Bin 0 -> 315180 bytes
 docs/authentication.md                             |   20 -
 docs/backup.md                                     |    4 +-
 docs/backup_reports.md                             |    5 +-
 docs/backups.md                                    |   66 +-
 docs/built-in.md                                   |   10 -
 docs/cloudinit.md                                  |   63 -
 docs/community.md                                  |    1 +
 docs/concurrency.md                                |   49 -
 docs/continuous_replication.md                     |   12 +-
 docs/contributing.md                               |   18 +-
 docs/delta_backups.md                              |   18 +-
 docs/directpurchase.md                             |   51 -
 docs/disaster_recovery.md                          |    4 +-
 docs/docker_support.md                             |  194 --
 docs/editions.md                                   |   58 -
 docs/emergency_shutdown.md                         |   29 -
 docs/features.md                                   |   20 -
 docs/file_level_restore.md                         |   21 -
 docs/general-troubleshooting.md                    |    4 +-
 docs/github.md                                     |   19 -
 docs/google.md                                     |   40 -
 docs/health.md                                     |   15 -
 docs/installation.md                               |   30 +-
 docs/invoices.md                                   |    9 -
 docs/ldap.md                                       |   22 -
 docs/load_balancing.md                             |   50 +-
 docs/logs.md                                       |   25 -
 docs/manage_infrastructure.md                      |   72 +-
 docs/metadata_backup.md                            |    4 +-
 docs/others.md                                     |   19 -
 docs/patching.md                                   |   32 -
 docs/proxy.md                                      |    6 +-
 docs/purchase.md                                   |   63 +-
 docs/recipes.md                                    |    3 -
 docs/reseller.md                                   |   10 +-
 docs/resources_delegation.md                       |   24 -
 docs/reverse_proxy.md                              |   48 -
 docs/rolling_snapshots.md                          |    4 +-
 docs/saml.md                                       |   23 -
 docs/scheduler.md                                  |   54 -
 docs/sdn_controller.md                             |    4 +-
 docs/search.md                                     |  128 -
 docs/self_service.md                               |   73 -
 docs/smart_backup.md                               |   39 -
 docs/supported-version.md                          |   37 -
 docs/through_purchase_department.md                |   28 -
 docs/trial.md                                      |   31 -
 docs/trial_activation.md                           |   35 -
 docs/troubleshooting.md                            |   32 +-
 docs/updates.md                                    |    0
 docs/upgrade.md                                    |   33 -
 docs/user_interface.md                             |   63 -
 docs/users.md                                      |   22 +-
 docs/visualizations.md                             |   17 -
 docs/vm_creation.md                                |   85 -
 docs/vm_import_export.md                           |   35 -
 docs/vm_management.md                              |   78 -
 docs/web-hooks.md                                  |   76 -
 docs/xo-cli.md                                     |  107 -
 docs/xo-server.md                                  |   85 -
 docs/xo-web.md                                     |   13 -
 docs/xosan.md                                      |  148 +-
 docs/xosan_create.md                               |   67 -
 docs/xosan_disperse.md                             |   50 -
 docs/xosan_replicated.md                           |   88 -
 docs/xosan_requirements.md                         |   41 -
 docs/xosan_trial.md                                |   25 -
 docs/xosan_types.md                                |   28 -
 package.json                                       |   23 +-
 packages/complex-matcher/README.md                 |    4 +-
 packages/complex-matcher/package.json              |    6 +-
 packages/complex-matcher/src/index.js              |    8 +-
 packages/value-matcher/README.md                   |    5 +-
 packages/value-matcher/package.json                |    6 +-
 packages/vhd-cli/README.md                         |    4 +-
 packages/vhd-cli/package.json                      |   10 +-
 packages/vhd-cli/src/commands/synthetize.js        |   10 +-
 packages/vhd-lib/README.md                         |    4 +-
 packages/vhd-lib/merge.integ.spec.js               |    2 +-
 packages/vhd-lib/package.json                      |   12 +-
 packages/vhd-lib/src/createContentStream.js        |    2 +-
 packages/vhd-lib/src/createReadableRawStream.js    |    2 +-
 packages/vhd-lib/src/createSyntheticStream.js      |    4 +-
 .../src/createVhdStreamWithLength.integ.spec.js    |    2 +-
 packages/xapi-explore-sr/README.md                 |    4 +-
 packages/xapi-explore-sr/package.json              |    6 +-
 packages/xapi-explore-sr/src/index.js              |    2 +-
 packages/xen-api/README.md                         |    4 +-
 packages/xen-api/package.json                      |    8 +-
 packages/xen-api/src/_coalesceCalls.js             |    2 +-
 packages/xen-api/src/cli.js                        |    1 +
 packages/xen-api/src/index.js                      |   61 +-
 packages/xen-api/src/inject-events.js              |    4 +-
 packages/xo-acl-resolver/README.md                 |    4 +-
 packages/xo-acl-resolver/package.json              |    4 +-
 packages/xo-cli/README.md                          |    4 +-
 packages/xo-cli/package.json                       |    7 +-
 packages/xo-cli/src/config.js                      |   22 +-
 packages/xo-cli/src/index.js                       |   34 +-
 packages/xo-collection/README.md                   |    6 +-
 packages/xo-collection/USAGE.md                    |    2 +-
 packages/xo-collection/package.json                |    6 +-
 packages/xo-collection/src/collection.spec.js      |   82 +-
 packages/xo-collection/src/index.spec.js           |   18 +-
 packages/xo-collection/src/unique-index.spec.js    |   14 +-
 packages/xo-collection/src/view.example.js         |    2 +-
 packages/xo-common/README.md                       |    4 +-
 packages/xo-common/package.json                    |    6 +-
 packages/xo-import-servers-csv/README.md           |    4 +-
 packages/xo-import-servers-csv/package.json        |    6 +-
 packages/xo-lib/README.md                          |    6 +-
 packages/xo-lib/USAGE.md                           |    2 +-
 packages/xo-lib/example.js                         |   26 +-
 packages/xo-lib/package.json                       |    6 +-
 packages/xo-remote-parser/README.md                |    4 +-
 packages/xo-remote-parser/package.json             |    6 +-
 packages/xo-server-audit/README.md                 |    2 +-
 packages/xo-server-audit/package.json              |    6 +-
 packages/xo-server-audit/src/index.js              |    3 +-
 packages/xo-server-auth-github/README.md           |    2 +-
 packages/xo-server-auth-github/package.json        |    4 +-
 packages/xo-server-auth-google/README.md           |    2 +-
 packages/xo-server-auth-google/package.json        |    6 +-
 packages/xo-server-auth-ldap/README.md             |    2 +-
 packages/xo-server-auth-ldap/package.json          |    8 +-
 packages/xo-server-auth-ldap/src/index.js          |    9 +-
 packages/xo-server-auth-ldap/src/test-cli.js       |   19 +-
 packages/xo-server-auth-saml/README.md             |    2 +-
 packages/xo-server-auth-saml/package.json          |    6 +-
 packages/xo-server-backup-reports/README.md        |    2 +-
 packages/xo-server-backup-reports/package.json     |    6 +-
 packages/xo-server-backup-reports/src/index.js     |    5 +-
 packages/xo-server-load-balancer/README.md         |    2 +-
 packages/xo-server-load-balancer/package.json      |    4 +-
 .../src/performance-plan.js                        |   19 +-
 packages/xo-server-perf-alert/README.md            |    2 +-
 packages/xo-server-perf-alert/package.json         |    8 +-
 packages/xo-server-perf-alert/src/index.js         |    2 +-
 packages/xo-server-sdn-controller/README.md        |    2 +-
 packages/xo-server-sdn-controller/package.json     |    8 +-
 packages/xo-server-sdn-controller/src/index.js     |   11 +-
 packages/xo-server-test-plugin/index.js            |   10 +-
 packages/xo-server-test-plugin/package.json        |    6 +-
 packages/xo-server-test/README.md                  |    2 +-
 packages/xo-server-test/package.json               |    4 +-
 packages/xo-server-test/src/_randomId.js           |    5 +-
 .../xo-server-test/src/old-tests/group.spec.js     |    2 +-
 packages/xo-server-test/src/old-tests/host.spec.js |    2 +-
 .../xo-server-test/src/old-tests/schedule.spec.js  |    2 +-
 packages/xo-server-test/src/old-tests/vbd.spec.js  |    2 +-
 packages/xo-server-test/src/old-tests/vif.spec.js  |    2 +-
 packages/xo-server-test/src/old-tests/vm.spec.js   |    2 +-
 packages/xo-server-transport-email/README.md       |    2 +-
 packages/xo-server-transport-email/package.json    |    6 +-
 packages/xo-server-transport-icinga2/README.md     |    2 +-
 packages/xo-server-transport-icinga2/package.json  |    8 +-
 packages/xo-server-transport-nagios/README.md      |    2 +-
 packages/xo-server-transport-nagios/package.json   |    6 +-
 packages/xo-server-transport-slack/README.md       |    2 +-
 packages/xo-server-transport-slack/package.json    |    6 +-
 packages/xo-server-transport-xmpp/README.md        |    2 +-
 packages/xo-server-transport-xmpp/package.json     |    6 +-
 packages/xo-server-usage-report/README.md          |    2 +-
 packages/xo-server-usage-report/package.json       |    6 +-
 packages/xo-server-usage-report/src/index.js       |    4 +-
 packages/xo-server-web-hooks/README.md             |    2 +-
 packages/xo-server-web-hooks/package.json          |    6 +-
 packages/xo-server/package.json                    |   12 +-
 packages/xo-server/src/_createNdJsonStream.js      |    2 +-
 packages/xo-server/src/_decorateWith.js            |   14 -
 packages/xo-server/src/_dedupeUnmount.js           |    2 +-
 packages/xo-server/src/_ensureArray.spec.js        |    8 +-
 packages/xo-server/src/_extractIpFromVmNetworks.js |    4 +-
 packages/xo-server/src/_pDebounceWithKey.js        |    2 +-
 packages/xo-server/src/_pDebounceWithKey.spec.js   |    2 +-
 packages/xo-server/src/api/disk.js                 |    6 +-
 packages/xo-server/src/api/vdi.js                  |    2 +-
 packages/xo-server/src/api/vm.js                   |   18 +-
 packages/xo-server/src/api/xo.js                   |    5 +-
 packages/xo-server/src/api/xosan.js                |   20 +-
 packages/xo-server/src/glob-matcher.js             |    4 +-
 packages/xo-server/src/index.js                    |   19 +-
 packages/xo-server/src/logs-cli.js                 |   58 +-
 packages/xo-server/src/math.spec.js                |    8 +-
 packages/xo-server/src/utils.js                    |    6 +-
 packages/xo-server/src/utils.spec.js               |   30 +-
 packages/xo-server/src/xapi-object-to-xo.js        |   11 +-
 packages/xo-server/src/xapi/index.js               |   16 +-
 packages/xo-server/src/xapi/mixins/networking.js   |    4 +-
 packages/xo-server/src/xapi/mixins/patching.js     |    8 +-
 packages/xo-server/src/xapi/mixins/vm.js           |   21 +-
 packages/xo-server/src/xapi/utils.js               |    8 +-
 packages/xo-server/src/xo-mixins/api.js            |    4 +-
 packages/xo-server/src/xo-mixins/authentication.js |    3 +-
 .../xo-server/src/xo-mixins/backups-ng/index.js    |   22 +-
 packages/xo-server/src/xo-mixins/backups.js        |    2 +-
 .../xo-server/src/xo-mixins/config-management.js   |   21 +-
 .../xo-server/src/xo-mixins/file-restore-ng.js     |    2 +-
 packages/xo-server/src/xo-mixins/hooks.js          |    2 +-
 .../src/xo-mixins/jobs/execute-call.spec.js        |    4 +-
 .../xo-server/src/xo-mixins/metadata-backups.js    |    2 +-
 packages/xo-server/src/xo-mixins/proxies.js        |    7 +-
 packages/xo-server/src/xo-mixins/workers/worker.js |    2 +-
 packages/xo-server/src/xo-mixins/xen-servers.js    |    2 +-
 packages/xo-server/src/xo.js                       |    2 +-
 packages/xo-vmdk-to-vhd/README.md                  |    6 +-
 packages/xo-vmdk-to-vhd/USAGE.md                   |    2 +-
 packages/xo-vmdk-to-vhd/package.json               |   12 +-
 packages/xo-web/gulpfile.js                        |   24 +-
 packages/xo-web/package.json                       |    4 +-
 packages/xo-web/src/common/base-component.js       |    2 +-
 packages/xo-web/src/common/intl/index.js           |    6 +-
 packages/xo-web/src/common/intl/locales/fr.js      |    2 +-
 packages/xo-web/src/common/intl/locales/it.js      |    2 +-
 packages/xo-web/src/common/intl/locales/tr.js      |    2 +-
 packages/xo-web/src/common/intl/messages.js        |    9 +-
 packages/xo-web/src/common/ip-utils.js             |    5 +-
 packages/xo-web/src/common/reaclette-utils.js      |    5 +-
 packages/xo-web/src/common/select-objects.js       |   20 +-
 packages/xo-web/src/common/selectors.js            |    2 +-
 packages/xo-web/src/common/sorted-table/index.js   |    8 +-
 packages/xo-web/src/common/store/actions.js        |    2 +-
 packages/xo-web/src/common/tooltip/get-position.js |    2 +-
 packages/xo-web/src/common/tooltip/index.js        |   24 +-
 packages/xo-web/src/common/utils.js                |    9 +-
 packages/xo-web/src/common/xo-parallel-chart.js    |    5 +-
 packages/xo-web/src/common/xo-week-charts/index.js |   26 +-
 .../xo-web/src/common/xo/copy-vm-modal/index.js    |  128 -
 .../xo-web/src/common/xo/copy-vms-modal/index.js   |  121 +-
 packages/xo-web/src/common/xo/index.js             |   59 +-
 .../src/common/xo/migrate-vdi-modal/index.js       |    8 +-
 packages/xo-web/src/patch-react.js                 |    2 +-
 packages/xo-web/src/xo-app/backup/new/index.js     |   15 +-
 .../xo-web/src/xo-app/backup/overview/tab-jobs.js  |   26 +-
 packages/xo-web/src/xo-app/disk-import/index.js    |    2 +-
 packages/xo-web/src/xo-app/home/index.js           |    5 +
 packages/xo-web/src/xo-app/home/sr-item.js         |    7 +-
 packages/xo-web/src/xo-app/host/tab-advanced.js    |    6 +-
 packages/xo-web/src/xo-app/import/index.js         |    2 +-
 packages/xo-web/src/xo-app/jobs/new/index.js       |    4 +-
 packages/xo-web/src/xo-app/new-vm/index.js         |    5 +-
 .../xo-web/src/xo-app/settings/plugins/index.js    |    2 +
 packages/xo-web/src/xo-app/sr/index.js             |    4 +-
 packages/xo-web/src/xo-app/user/index.js           |    5 +-
 packages/xo-web/src/xo-app/vm/tab-advanced.js      |   13 +
 packages/xo-web/src/xo-app/vm/tab-network.js       |   56 +-
 packages/xo-web/src/xo-app/xoa/update/index.js     |    2 +-
 scripts/README.md.tpl                              |    4 +-
 scripts/normalize-packages                         |   14 +-
 yarn.lock                                          | 3105 +++++++++++++-------
 320 files changed, 4139 insertions(+), 4224 deletions(-)
 create mode 100644 @vates/decorate-with/README.md
 create mode 100644 @vates/decorate-with/USAGE.md
 create mode 100644 @vates/decorate-with/index.js
 create mode 100644 @vates/decorate-with/package.json
 create mode 100644 @vates/parse-duration/README.md
 create mode 100644 @vates/parse-duration/USAGE.md
 rename packages/xo-server/src/_parseDuration.js => @vates/parse-duration/index.js (77%)
 create mode 100644 @vates/parse-duration/package.json
 delete mode 100644 docs/SUMMARY.md
 create mode 100644 docs/assets/delta_final.png
 create mode 100644 docs/assets/deltamerge1.png
 create mode 100644 docs/assets/deltamerge2.png
 create mode 100644 docs/assets/loadbalance1.png
 create mode 100644 docs/assets/loadbalance3.png
 create mode 100644 docs/assets/loadbalance4.png
 create mode 100644 docs/assets/nodelta.png
 create mode 100644 docs/assets/withoutproxy.png
 create mode 100644 docs/assets/withproxy.png
 delete mode 100644 docs/authentication.md
 delete mode 100644 docs/built-in.md
 delete mode 100644 docs/cloudinit.md
 delete mode 100644 docs/concurrency.md
 delete mode 100644 docs/directpurchase.md
 delete mode 100644 docs/docker_support.md
 delete mode 100644 docs/editions.md
 delete mode 100644 docs/emergency_shutdown.md
 delete mode 100644 docs/features.md
 delete mode 100644 docs/file_level_restore.md
 delete mode 100644 docs/github.md
 delete mode 100644 docs/google.md
 delete mode 100644 docs/health.md
 delete mode 100644 docs/invoices.md
 delete mode 100644 docs/ldap.md
 delete mode 100644 docs/logs.md
 delete mode 100644 docs/others.md
 delete mode 100644 docs/patching.md
 delete mode 100644 docs/recipes.md
 delete mode 100644 docs/resources_delegation.md
 delete mode 100644 docs/reverse_proxy.md
 delete mode 100644 docs/saml.md
 delete mode 100644 docs/scheduler.md
 delete mode 100644 docs/search.md
 delete mode 100644 docs/self_service.md
 delete mode 100644 docs/smart_backup.md
 delete mode 100644 docs/supported-version.md
 delete mode 100644 docs/through_purchase_department.md
 delete mode 100644 docs/trial.md
 delete mode 100644 docs/trial_activation.md
 delete mode 100644 docs/updates.md
 delete mode 100644 docs/upgrade.md
 delete mode 100644 docs/user_interface.md
 delete mode 100644 docs/visualizations.md
 delete mode 100644 docs/vm_creation.md
 delete mode 100644 docs/vm_import_export.md
 delete mode 100644 docs/vm_management.md
 delete mode 100644 docs/web-hooks.md
 delete mode 100644 docs/xo-cli.md
 delete mode 100644 docs/xo-server.md
 delete mode 100644 docs/xo-web.md
 delete mode 100644 docs/xosan_create.md
 delete mode 100644 docs/xosan_disperse.md
 delete mode 100644 docs/xosan_replicated.md
 delete mode 100644 docs/xosan_requirements.md
 delete mode 100644 docs/xosan_trial.md
 delete mode 100644 docs/xosan_types.md
 delete mode 100644 packages/xo-server/src/_decorateWith.js
 delete mode 100644 packages/xo-web/src/common/xo/copy-vm-modal/index.js

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202020061652
[ok] Shutting down xo-server

[info] Updating xen-orchestra from '6212109fc' to 'c1d588264'

[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file

[info] Adding WorkingDirectory parameter to systemd service configuration file
[info] Fixing relative path to xo-web installation in xo-server configuration file
[info] Activating modified configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration

[info] Starting xo-server...

	WebUI started in port 80. Make sure you have firewall rules in place to allow access.
	Default username: admin@admin.net password: admin

[info] Installation successful. Enabling xo-server to start on reboot

[ok] Removing old installations. Leaving 3 latest
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ exit
logout
Connection to xo closed.
ronny@Ronnys-MacBook-Pro-2 ~ % ssh ronny@xo
ronny@xo's password: 
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Jun 20 16:53:21 UTC 2020

  System load:  0.39               Processes:           113
  Usage of /:   54.6% of 14.70GB   Users logged in:     0
  Memory usage: 20%                IP address for eth0: 192.168.1.4
  Swap usage:   0%

 * "If you've been waiting for the perfect Kubernetes dev solution for
   macOS, the wait is over. Learn how to install Microk8s on macOS."

   https://www.techrepublic.com/article/how-to-install-microk8s-on-macos/

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

12 packages can be updated.
0 updates are security updates.

Last login: Sat Jun 20 16:24:37 2020 from 192.168.1.130
ronny@xo-ce:~$ sudo ./xo-install.sh 
[sudo] password for ronny: 
sudo: ./xo-install.sh: command not found
ronny@xo-ce:~$ sudo ./xo-install.sh 
sudo: ./xo-install.sh: command not found
ronny@xo-ce:~$ sudo ./xo-install.sh 
sudo: ./xo-install.sh: command not found
ronny@xo-ce:~$ ls
node_modules  package-lock.json  XenOrchestraInstallerUpdater
ronny@xo-ce:~$ cd XenOrchestraInstallerUpdater/
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ ls
LICENSE    sample.xo-install.cfg  xo-install.cfg      xo-install.log
README.md  tests                  xo-install.cfg.old  xo-install.sh
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo ./xo-install.sh 

WARNING: you have less than 3GB of RAM in your system. Installation might run out of memory

-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Ubuntu 18 
Basedir: /etc/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to ./xo-install.log for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 4
Which installation to roll back?

1) /etc/xo/xo-builds/xen-orchestra-202030041501
2) /etc/xo/xo-builds/xen-orchestra-202016042132
3) /etc/xo/xo-builds/xen-orchestra-202020061652
Pick a number. CTRL+C to exit: 2

[info] Setting /etc/xo/xo-server symlink to /etc/xo/xo-builds/xen-orchestra-202016042132/packages/xo-server
[info] Setting /etc/xo/xo-web symlink to /etc/xo/xo-builds/xen-orchestra-202016042132/packages/xo-web

[info] Replacing xo.server.service systemd configuration file

[info] Restarting xo-server...

ronny@xo-ce:~/XenOrchestraInstallerUpdater$ sudo ./xo-install.sh 

WARNING: you have less than 3GB of RAM in your system. Installation might run out of memory

-----------------------------------------

Welcome to automated Xen Orchestra install

Following options will be used for installation:

OS: Ubuntu 18 
Basedir: /etc/xo 
User: root 
Port: 80
HTTPS: false 
Git Branch for source: master
Following plugins will be installed: all
Number of previous installations to preserve: 3

Errorlog is stored to ./xo-install.log for debug purposes

Xen Orchestra configuration will be stored to /root/.config/xo-server/config.toml, if you don't want it to be replaced with every update, set CONFIGUPDATE to false in xo-install.cfg
-----------------------------------------

1. Autoinstall
2. Update / Install without packages
3. Deploy docker container
4. Rollback to another existing installation
5. Exit

: 1
Looks like xo-server process is already running, consider running update instead. Continue anyway?
[y/N]: y
Stopping xo-server...
[ok] OS Ubuntu so making sure universe repository is enabled

[ok] Running apt-get update

[..] Installing build dependencies, redis server, git, libvhdi-utils, python-min[ok] Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common, cifs-utils, curl

[..] Installing apt-transport-https and ca-certificates packages to support http[ok] Installing apt-transport-https and ca-certificates packages to support https repos

[ok] Enabling and starting redis service

[ok] Enabling and starting rpcbind service

[info] Fetching Xen Orchestra source code

Already up to date.

[info] Creating install directory: /etc/xo/xo-builds/xen-orchestra-202020061655
[info] Updating xen-orchestra from 'c79ebfdd0' to 'c1d588264'

[info] xo-server and xo-web build quite a while. Grab a cup of coffee and lay back

[ok] Running installation

[ok] Installing plugins

[info] Fixing binary path in systemd service configuration file

[info] Adding WorkingDirectory parameter to systemd service configuration file

[info] Symlinking fresh xo-server install/update to /etc/xo/xo-server
[info] Symlinking fresh xo-web install/update to /etc/xo/xo-web

[info] Replacing systemd service configuration file
[info] Reloading systemd configuration

[info] Starting xo-server...

	WebUI started in port 80. Make sure you have firewall rules in place to allow access.
	Default username: admin@admin.net password: admin

[info] Installation successful. Enabling xo-server to start on reboot
ronny@xo-ce:~/XenOrchestraInstallerUpdater$ 
copy and paste the output from installation logfile. by default logfiles are stored in logs directory
```
**xo-server.service log**
```
copy and paste the output (if available) from command journalctl -u xo-server -n 100
```

**Comment by ronivay** [comment]
Hi,

Please pull the latest version of this script, update your VM to have at least 3GB of RAM as suggested by the script and run the update again. If it still doesn’t start, copy and paste the logfile content (logfile location told in script output when being ran), by default it’s under logs directory inside XenOrchestraInstallerUpdater directory.

**Comment by okynnor** [comment]
Hi, 

I have done just that and it is running perfectly. 

It looks like the major differences is that node.js was updated from 8 to 12.  

I'll test it why 1GB may affect the install though.

**Comment by ronivay** [comment]
Hi,

I just today created a fix to upgrade node.js major version if its too old, so that might’ve helped it. The warning about RAM isn’t there without a reason. Too less RAM can cause weird issues and unexpected behaviour when some parts of yarn/yarn build aren’t completed succesfully. If it’s installing perfectly now, i’ll close the issue. Feel free to get back here if you have any further questions.

**Comment by okynnor** [comment]
@ronivay I performed some testing.  I reverted to an old snapshot of the VM.  I increased the RAM memory to 3GB and ran the following two steps: 

`git clone https://github.com/ronivay/XenOrchestraInstallerUpdater.git` inside the XenOrchestraInstallerUpdater directory 
then
`sudo ./xo-install.sh`

Unfortunately, the result was the same in that the XO web interface didn't come up. 

So, the only was to delete the directory, XenOrchestraInstallerUpdater, get the code via Git cone and re-ran it by using option #2.  Then, the script upgraded node.js from 8 --> 12.x

Let me know if I did anything wrong.

**Comment by ronivay** [comment]
Okay. This makes sense if/when the old snapshotted VM had node.js v8 installed. Install procedure doesn’t install new node.js if there already is one (it’s mainly designed for fresh VM’s). Update procedure had the fix to upgrade node.js version if it’s too old so that’s why it worked. 

I’ll see if i can come up with a good solution to install part as well.
