### ISSUE TITLE
Plugins are not installed

### ISSUE THREAD

**Issue by Lodewykdk** [ronivay/XenOrchestraInstallerUpdater#5]
Hi there,

Ran the script on Ubuntu 16.04, Debain 8 and 9. Plugins are not installed. I changed the following as per the Readme...

PLUGINS="xo-server-auth-ldap,xo-server-transport-email,xo-server-usage-report,xo-server-perf-alert"

Please advise?

**Comment by ronivay** [comment]
Hi,

Stupid mistake from me. The actual installation procedure was missing from previous commit. Commited a fix now.
