### ISSUE TITLE
Couldn't install node xcp-ng distro

### ISSUE THREAD

**Issue by GogoAkira** [ronivay/XenOrchestraInstallerUpdater#51]
Can I do anything about this, trying not to install everything manually :)

logs show following:

```
## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: xcp-ng-release-8.1.0-6.x86_64.
```

Also running `curl -sL https://deb.nodesource.com/test | bash -` shows `bash: npm: command not found Error executing command` but node website says npm gets installed with node js

edit: 
       Managed to installed node and npm using nvm `https://github.com/nvm-sh/nvm` but it's installed under `/root/.nvm/versions` I don't know where should I sym link this to so that yarn can see node is installed as it is, npm works and the test script from node passes now.

This script says node is installed and skips to yarn but yarn says node isn't installed.

OK I see that's a deb url up there but no matter, it wouldn't even start before nvm and now it does.

I did this `n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local` from `https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps`  I don't even know :) but now I can see which node.

Also before rebooting npm and node -v wouldn't work even though it's installed, after above command we will see.

I couldn't install yum yarn because it's dependency is 'nodejs' instead of node v12.* whatever?, but I did install it using `npm install yarn -g` and so now the script told me to grab a cup of coffee which I will, then run XO and then reboot and see if it sticks :)

so the installation failed, checking logs again.

.. well it failed because the default distro installation gave me only 1.4GB of RAM "JavaScript heap out of memory"
Now have to figure out how to allocate more memory to dom0

OK so edited `/boot/efi/EFI/xenserver/grub.cfg` line with dom0 mem max, ran `grub-mkconfig and grub-mkconfig -o grub.cfg`  my coffe is cold, installation is runnng.

What's weird npm now works and node -v after reboot fine but yarn I had to reinstall with node and it's in /usr/local/bin/yarn , how to make it stick becauese after reboot it will probably break my XO if yarn is nowhere to be found and I'll have to npm install yarn -g again. So werid

Sorry for many questions :) 

Installation finshed waiting for port to be open and xo-server didn't start :) yet because the whatever is using port 80? 

Instructions say allow port 80, do they mean allow it in firewall, pretty sure it's allowed because some server is running the default page after you install the distro.?

well xo-server.service is running, not visible because something else is using port 80, don't see anything in iptables. 
How to turn off whatever is running now asking me to deploy xo or center, what is the name of that.

Don't really know why I tried to install XO on the same machine aka dom0 that xcp-ng is installed to instead of installing in on a VM , I guess because I assumed we needed XO to install VM's in the first place so I went ahead and tried to install XO on dom0. Is it not supposed to go there? I just broke the grub and now `xl list` doestn't even work, reinstalling :)

If anywone has any advice on any of this please do

Well, only now I understand what Appliance at the end means :) 

Disregard most of this, but if anyone has any comments please do.

**Comment by ronivay** [comment]
Hello,

You got it eventually :) As readme says, there's a set of supported operating systems and you should use a fresh installation from any of those. This is not designed to work directly on xenserver/xcp-ng host and wont ever be as it has only one job, be a hypervisor.

Use the appliance option if you can't currently access your xcp-ng easily via other means. Otherwise deploy a fresh minimal installation of centos 8/debian 10/ubuntu 20 and try xo-install.sh again.

**Comment by GogoAkira** [comment]
Yeah thanks man this was a journey :) , I got the free XOA deployed and now I'm going to do appliance from your instructions and then do a proper script on a Debian I install later :) , I was making assuming many things without reading slowly and jumping to conclusions :)

Thanks for the script
