### ISSUE TITLE
Appliance - No resolv.conf

### ISSUE THREAD

**Issue by qwow5** [ronivay/XenOrchestraInstallerUpdater#53]
Installed latest appliance (10/11/20) on a fresh xcp-ng server and realized that the system was not able to resolve DNS queries.

After further inspection, I discovered that the system had no resolv.conf file present. Adding a resolv.conf file with a valid DNS server fixed this problem.

**Comment by ronivay** [comment]
Hello,

Did you use static ip-address or dhcp? If latter, does your dhcp server offer a DNS server(s)? If not, it will be empty.

**Comment by qwow5** [comment]
Thanks for the quick reply!

I used a static IP.

**Comment by ronivay** [comment]
Hmm okay. I’ll take a look what might have happened.

**Comment by ronivay** [comment]
Indeed the base was missing resolvconf service so /etc/resolv.conf wasn't populated from interfaces config. This is now fixed and updated image is in place.
