### ISSUE TITLE
UPGRADE SUCCESS BUT SERVICE NOT START

### ISSUE THREAD

**Issue by informaticavera** [ronivay/XenOrchestraInstallerUpdater#58]
Ubuntu 18.04.5 LTS
NODE v12.16.2
YARN 1.21.1

Dec  1 12:18:52 xoa xo-server[1723]: ✖ The expression evaluated to a falsy value:
Dec  1 12:18:52 xoa xo-server[1723]:   (0, _assert.default)(global.Promise === require('bluebird'))
Dec  1 12:18:52 xoa xo-server[1723]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
Dec  1 12:18:52 xoa xo-server[1723]:   (0, _assert.default)(global.Promise === require('bluebird'))
Dec  1 12:18:52 xoa xo-server[1723]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202001121149/packages/xo-server/src/index.js:681:3)
Dec  1 12:18:52 xoa xo-server[1723]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202001121149/node_modules/exec-promise/index.js:57:13
Dec  1 12:18:52 xoa xo-server[1723]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
Dec  1 12:18:52 xoa xo-server[1723]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202001121149/node_modules/exec-promise/index.js:56:10)
Dec  1 12:18:52 xoa xo-server[1723]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202001121149/packages/xo-server/bin/xo-server:27:24)
Dec  1 12:18:52 xoa xo-server[1723]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Dec  1 12:18:52 xoa xo-server[1723]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Dec  1 12:18:52 xoa xo-server[1723]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Dec  1 12:18:52 xoa xo-server[1723]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Dec  1 12:18:52 xoa xo-server[1723]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Dec  1 12:18:52 xoa xo-server[1723]:     at internal/main/run_main_module.js:18:47
Dec  1 12:18:52 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Dec  1 12:18:52 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.

**Comment by ronivay** [comment]
Hi,

Sorry for late response to this. Could you please try the update again. It seems that there might've been some recent change in xen orchestra sources master branch causing this.

**Comment by informaticavera** [comment]
it seems that the problem continues

**Comment by ronivay** [comment]
Hi,

Okay. Could you grab the logfile from your latest installation attempt (logs directory inside same directory where xo-install.sh is, if you haven't changed the location in config) for more information about the issue. If you can find the lines which tell the issue, just paste them here. Otherwise the entire logfile, and please use code block to prevent github from formatting the pasted information.

**Comment by informaticavera** [comment]
[xo-install.zip](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/5677800/xo-install.zip)

**Comment by ronivay** [comment]
Thanks. Build procedure seems to have been successful according to logs and don't really see any issue here. Could you grab a little bit more log output from journalctl from the attempted service start with journalctl -u xo-server -n 150 for example. I might have a bug in service start check when update is ran (reports everything successful even if service doesn't start) but i'll look into it.

**Comment by informaticavera** [comment]
Thanks!!!!

dic 11 10:21:55 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 23.
dic 11 10:21:55 xoa systemd[1]: Stopped XO Server.
dic 11 10:21:55 xoa systemd[1]: Started XO Server.
dic 11 10:21:59 xoa xo-server[9498]: ✖ The expression evaluated to a falsy value:
dic 11 10:21:59 xoa xo-server[9498]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:21:59 xoa xo-server[9498]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:21:59 xoa xo-server[9498]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:21:59 xoa xo-server[9498]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:21:59 xoa xo-server[9498]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:21:59 xoa xo-server[9498]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:21:59 xoa xo-server[9498]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:21:59 xoa xo-server[9498]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:21:59 xoa xo-server[9498]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:21:59 xoa xo-server[9498]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:21:59 xoa xo-server[9498]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:21:59 xoa xo-server[9498]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:21:59 xoa xo-server[9498]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:21:59 xoa xo-server[9498]:     at internal/main/run_main_module.js:18:47
dic 11 10:21:59 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:21:59 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:21:59 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:21:59 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 24.
dic 11 10:21:59 xoa systemd[1]: Stopped XO Server.
dic 11 10:21:59 xoa systemd[1]: Started XO Server.
dic 11 10:22:03 xoa xo-server[9539]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:03 xoa xo-server[9539]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:03 xoa xo-server[9539]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:03 xoa xo-server[9539]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:03 xoa xo-server[9539]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:03 xoa xo-server[9539]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:03 xoa xo-server[9539]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:03 xoa xo-server[9539]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:03 xoa xo-server[9539]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:03 xoa xo-server[9539]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:03 xoa xo-server[9539]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:03 xoa xo-server[9539]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:03 xoa xo-server[9539]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:03 xoa xo-server[9539]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:03 xoa xo-server[9539]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:03 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:03 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:03 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:03 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 25.
dic 11 10:22:03 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:03 xoa systemd[1]: Started XO Server.
dic 11 10:22:06 xoa xo-server[9581]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:06 xoa xo-server[9581]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:06 xoa xo-server[9581]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:06 xoa xo-server[9581]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:06 xoa xo-server[9581]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:06 xoa xo-server[9581]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:06 xoa xo-server[9581]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:06 xoa xo-server[9581]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:06 xoa xo-server[9581]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:06 xoa xo-server[9581]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:06 xoa xo-server[9581]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:06 xoa xo-server[9581]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:06 xoa xo-server[9581]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:06 xoa xo-server[9581]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:06 xoa xo-server[9581]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:06 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:06 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:06 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:06 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 26.
dic 11 10:22:06 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:06 xoa systemd[1]: Started XO Server.
dic 11 10:22:10 xoa xo-server[9616]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:10 xoa xo-server[9616]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:10 xoa xo-server[9616]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:10 xoa xo-server[9616]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:10 xoa xo-server[9616]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:10 xoa xo-server[9616]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:10 xoa xo-server[9616]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:10 xoa xo-server[9616]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:10 xoa xo-server[9616]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:10 xoa xo-server[9616]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:10 xoa xo-server[9616]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:10 xoa xo-server[9616]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:10 xoa xo-server[9616]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:10 xoa xo-server[9616]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:10 xoa xo-server[9616]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:10 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:10 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:10 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:10 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 27.
dic 11 10:22:10 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:10 xoa systemd[1]: Started XO Server.
dic 11 10:22:13 xoa xo-server[9655]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:13 xoa xo-server[9655]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:13 xoa xo-server[9655]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:13 xoa xo-server[9655]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:13 xoa xo-server[9655]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:13 xoa xo-server[9655]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:13 xoa xo-server[9655]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:13 xoa xo-server[9655]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:13 xoa xo-server[9655]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:13 xoa xo-server[9655]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:13 xoa xo-server[9655]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:13 xoa xo-server[9655]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:13 xoa xo-server[9655]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:13 xoa xo-server[9655]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:13 xoa xo-server[9655]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:13 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:13 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:13 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:13 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 28.
dic 11 10:22:13 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:13 xoa systemd[1]: Started XO Server.
dic 11 10:22:17 xoa xo-server[9696]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:17 xoa xo-server[9696]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:17 xoa xo-server[9696]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:17 xoa xo-server[9696]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:17 xoa xo-server[9696]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:17 xoa xo-server[9696]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:17 xoa xo-server[9696]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:17 xoa xo-server[9696]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:17 xoa xo-server[9696]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:17 xoa xo-server[9696]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:17 xoa xo-server[9696]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:17 xoa xo-server[9696]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:17 xoa xo-server[9696]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:17 xoa xo-server[9696]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:17 xoa xo-server[9696]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:17 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:17 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:17 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:17 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 29.
dic 11 10:22:17 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:17 xoa systemd[1]: Started XO Server.
dic 11 10:22:20 xoa xo-server[9739]: ✖ The expression evaluated to a falsy value:
dic 11 10:22:20 xoa xo-server[9739]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:20 xoa xo-server[9739]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
dic 11 10:22:20 xoa xo-server[9739]:   (0, _assert.default)(global.Promise === require('bluebird'))
dic 11 10:22:20 xoa xo-server[9739]:     at main (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/src/index.js:681:3)
dic 11 10:22:20 xoa xo-server[9739]:     at /opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:57:13
dic 11 10:22:20 xoa xo-server[9739]:     at new Promise (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:164:7)
dic 11 10:22:20 xoa xo-server[9739]:     at execPromise (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/node_modules/exec-promise/index.js:56:10)
dic 11 10:22:20 xoa xo-server[9739]:     at Object.<anonymous> (/opt/xen-orchestra/xo-builds/xen-orchestra-202011120958/packages/xo-server/bin/xo-server:27:24)
dic 11 10:22:20 xoa xo-server[9739]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
dic 11 10:22:20 xoa xo-server[9739]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
dic 11 10:22:20 xoa xo-server[9739]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
dic 11 10:22:20 xoa xo-server[9739]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
dic 11 10:22:20 xoa xo-server[9739]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
dic 11 10:22:20 xoa xo-server[9739]:     at internal/main/run_main_module.js:18:47
dic 11 10:22:20 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
dic 11 10:22:20 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
dic 11 10:22:21 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
dic 11 10:22:21 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 30.
dic 11 10:22:21 xoa systemd[1]: Stopped XO Server.
dic 11 10:22:21 xoa systemd[1]: Started XO Server.

**Comment by ronivay** [comment]
Hmh, can't figure out from these what's the issue. The install procedure seems to finish as it's supposed and there are no errors during build but somehow xen orchestra still fails to start properly and outputs those error messages. Can't reproduce this with similar Ubuntu setup either.

My Ubuntu VM ended up with yarn 1.22.5 and node 12.20.0. Those should be updated during the update procedure. Are you still having the same versions as in the beginning?

Unfortunately at this point i have no other tips than start fresh and copy /var/lib/xo-server data directory from the old one to keep original data.

**Comment by ronivay** [comment]
Hi,

just a followup on this. did you manage to rebuild and transfer data over or any other update on this?

**Comment by informaticavera** [comment]
I'm sorry, I haven't been able to do the test yet

**Comment by informaticavera** [comment]
I have tried a fresh installation and the result is the same.  In the beginning my versions are:
Orchestra 5.45.1, with xo-server and xo-web 5.58.2
Node version 12.16.2
Yarn version 1.21.1

**Comment by ronivay** [comment]
How did you start with some versions if this was a fresh installation? Could you please try this on a fresh deployed ubuntu VM. If that works, you can manually move the important data over from you old installation. Sorry but i have no other tips at this point. Install logs looked fine to me but since there still is an issue when starting the service and it isn’t clear in logs what actually happens it’s difficult to try to guide you further.

**Comment by CodeSeba** [comment]
Hi. I have the same problem. Bluebird module not found and can't start XO.

For lab testing, I try first with virtualbox and debian 10 i386, with only minimal packages (ssh and standard system tools), then install XO with XenOrchestraInstallerUpdater (git master) and finished good but with warnings --> "Bluebird module not found"

For a second test, I try virtualbox and this time with debian 10 amd64, with only minimal packages (ssh and standard system tools), now is installed perfectly as expected.

Maybe that module is only for x64 arch. I hope this will help you to find out a solution.

**Comment by ronivay** [comment]
Hi,

Thank you, this helps alot. Didn't somehow even come to my mind that it might be because of 32/64bit differences. Most likely 32bit isn't supported at all. I'll look into this.

**Comment by informaticavera** [comment]
a clean install on ubuntu 18.04 64bits works without problems

**Comment by ronivay** [comment]
If this worked before, i'm sure there has been a change after going from node 8.x to node 12.x during the upgrade. I don't see any reason really why one should run a 32bit OS nowadays so i'm just going to implement a check that installation is being run on a 64bit system as part of the OS check.

**Comment by ronivay** [comment]
Check now implemented in: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/8d2e1e37916c08a19f291b1459bbc3a2b759475a

Thank you both for details on this.
