### ISSUE TITLE
Appliance - Failed writing body

### ISSUE THREAD

**Issue by bazzacad** [ronivay/XenOrchestraInstallerUpdater#60]
When I run the Appliance script on my 8.2 host I get the following error:

> Downloading and importing XVA image...
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0 3879M    0 15107    0     0  18799      0 60:06:43 --:--:-- 60:06:43 18813
> curl: (23) Failed writing body (0 != 15107)

Any suggestions?

**Comment by ronivay** [comment]
Most likely something with the vm-import and curl gives error because piped command exits. Piped command output isn't printed to stderr so it's not visible here. You can try running manually:

`curl "https://xo-appliance.yawn.fi/downloads/image.xva" | xe vm-import filename=/dev/stdin`

This should output any error the xe vm-import command gives which might explain it.

**Comment by bazzacad** [comment]
Thanks, here's what I got:

> [11:08 xcp-ng ~]# curl "https://xo-appliance.yawn.fi/downloads/image.xva" | xe vm-import filename=/dev/stdin
>   % TotalError: No SR specified and Pool default SR is null
>     % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0 3879M    0 15107    0     0  14254      0 79:16:44  0:00:01 79:16:43 14265
> curl: (23) Failed writing body (0 != 15107)

**Comment by ronivay** [comment]
Okay, that explains it. VM is being imported to your default SR (storage repository). I suppose it isn’t possible to have SR’s but none set as default so sounds like your XCP-ng installation is missing SR. Configure that first and you’re good to go.

That’s usually done during installation but you might’ve skipped it. 

Read more here for example: https://xcp-ng.org/docs/storage.html
