### ISSUE TITLE
Option to remove the normal version when switching to Docker version

### ISSUE THREAD

**Issue by Haribo112** [ronivay/XenOrchestraInstallerUpdater#64]
I was previously running the installed version of Xen Orchestra using you script to install and update. I have now switched to the Docker version, also using your script. However; running ```htop``` shows that there are still some parts of the previous version running and I am unsure how to make them stop. Maybe your script could include an option to remove the 'native' installed version of XO?

**Comment by ronivay** [comment]
Hi,

that docker portion in this script is sort of remnant from very early days when container i maintained wasn’t in it’s own repository. That part in this script doesn’t really do anything except pull container and give some instructions how to start it. it doesn’t do anything for possibly existing installation.

I’ve been meaning to remove docker portion completely to avoid confusion but hasn’t been a priority. Maybe i’ll take care of it now :)

You can simply run systemctl stop xo-server && systemctl disable xo-server to shut old installation down and prevent it from automatically starting anymore.

**Comment by Haribo112** [comment]
I ran the systemctl commands; however this still leaves redis-server and xe-daemon running. I'm also seeing multipathd still running, which I assume is also started by XO?

**Comment by ronivay** [comment]
multipathd isn't started by xen orchestra. xe-daemon is xen-tools for your VM and related to the fact you're running that on XCP-NG/XenServer, so leave it on. redis-server you can stop if you don't need it for anything else (same commands as above, replace xo-server with redis-server).

**Comment by Haribo112** [comment]
Thanks. Any hints on directories I can delete to remove all the xo related stuff from my Ubuntu install? Or should I make a clean new VM and run docker on that.

**Comment by ronivay** [comment]
Clean install is obviously safest, but should be fairly simple to cleanup. If you used the default base directory for sources and built xen-orchestra's, then remove /opt/xo and all subdirectories. If this was something else, then you probably know better what you configured :)

Actual persistent xen-orchestra data is at /var/lib/xo-server and /var/lib/redis which you can remove completely. Note that you're safe to remove these only if you didn't bind mount same directories to container with -v option. 

Docker stuff is now removed from this script and it will live completely in it's own repo from now on.
