### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Daniel-Furcht** [ronivay/XenOrchestraInstallerUpdater#7]
Hi, I have tried update XOA to latest version and a erro raised as described bellow:

### **During Update**

Replacing systemd service configuration file
Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
Removing /etc/xo/xo-builds/xen-orchestra-201801080900 because of failed installation.

### **Log**

Cloning into '/etc/xo/xo-builds/xen-orchestra-201801080900'...
DEPRECATION WARNING on line 29, column 8 of /etc/xo/xo-builds/xen-orchestra-201801080900/packages/xo-web/src/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

DEPRECATION WARNING on line 63, column 8 of /etc/xo/xo-builds/xen-orchestra-201801080900/packages/xo-web/src/index.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

/bin/cp: '/etc/xo/xo-builds/xen-orchestra-201801080900/packages/xo-server/xo-server.service' e '/etc/systemd/system/xo-server.service' são o mesmo arquivo

**Comment by Daniel-Furcht** [comment]
The service file is a symlink to the same file... perhaps these copy step is not necessary.

**Comment by ronivay** [comment]
Hi,

Older installations seem to indeed break because of the existing symlink. Should be fixed in commit:
https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/77142b63bb5fa508712117c51a600944e6a772ce

Can you confirm, thanks.

**Comment by ronivay** [comment]
No issues during my own tests so this should be okay.

**Comment by sspanjers** [comment]
I seem to be having the same problem.  Debian 9.6, script seems to be running along properly, it gets to starting the xo-server, waiting for the port to be open.  Then it fails with the error message below.

Message:
waiting for port to be open
Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
Removing /etc/xo/xo-builds/xen-orchestra-201816121406 because of failed installation.

Checking the installation log: 
Cloning into '/etc/xo/xo-src/xen-orchestra'...
DEPRECATION WARNING on line 29, column 8 of /etc/xo/xo-builds/xen-orchestra-201$
Including .css files with @import is non-standard behaviour which will be remov$
Use a custom importer to maintain this behaviour. Check your implementations do$

DEPRECATION WARNING on line 63, column 8 of /etc/xo/xo-builds/xen-orchestra-201$
Including .css files with @import is non-standard behaviour which will be remov$
Use a custom importer to maintain this behaviour. Check your implementations do$

**Comment by ronivay** [comment]
Hi,

Issue in the first message is fixed. You seem to have an issue with the service not starting. Errors from the service don’t end up to scripts error log, they are found from the systemd log. Are you running the default configuration or custom ? Please paste your configuration file if you altered it. Also check what you have in service logs after this error occurs with: journalctl -u xo-server -n 50

**Comment by sspanjers** [comment]
I am just running default configuration, no alterations.

Here is the service log output:

-- Logs begin at Sun 2018-12-16 14:02:11 EST, end at Mon 2018-12-17 18:42:11 EST. --
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:94:103)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at _next (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:96:194)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at /etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:96:364
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._execute (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/debuggability.js:313:9)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._resolveFromExecutor (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:483:18)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at new Promise (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:79:10)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at /etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:96:97
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at _createWebServer (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:411:27)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at createWebServer (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:399:27)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at /etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/src/index.js:574:26
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Generator.next (<anonymous>)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:94:103)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at _next (/etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-server/dist/index.js:96:194)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at tryCatcher (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/util.js:16:23)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._settlePromiseFromHandler (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:512:31)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._settlePromise (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:569:18)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._settlePromise0 (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:614:10)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Promise._settlePromises (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/promise.js:694:18)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at _drainQueueStep (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/async.js:138:12)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at _drainQueue (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/async.js:131:9)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Async._drainQueues (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/async.js:147:5)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at Immediate.Async.drainQueues [as _onImmediate] (/etc/xo/xo-builds/xen-orchestra-201816121430/node_modules/bluebird/js/release/async.js:17:14)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at runCallback (timers.js:810:20)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at tryOnImmediate (timers.js:768:5)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      errno: 'EADDRINUSE',
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      code: 'EADDRINUSE',
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      syscall: 'listen',
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      address: '::',
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      port: 80,
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      niceAddress: 'http://localhost:80',
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      [Symbol(originalCallSite)]:
Dec 16 14:35:30 XenOrchestra xo-server[17987]:       [ CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {} ],
Dec 16 14:35:30 XenOrchestra xo-server[17987]:      [Symbol(mutatedCallSite)]:
Dec 16 14:35:30 XenOrchestra xo-server[17987]:       [ CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         [Object],
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         [Object],
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         [Object],
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         [Object],
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {},
Dec 16 14:35:30 XenOrchestra xo-server[17987]:         CallSite {} ] } }
Dec 16 14:35:30 XenOrchestra xo-server[17987]: 2018-12-16T19:35:30.615Z - xo:main - [WARN]   Address already in use.
Dec 16 14:35:31 XenOrchestra xo-server[17987]: 2018-12-16T19:35:31.112Z - xo:main - [INFO] Setting up / → /etc/xo/xo-builds/xen-orchestra-201816121430/packages/xo-web/dist

**Comment by ronivay** [comment]
Hello,

Okay so it seems you have some other process running in port 80, and xo-server can't bind to it and fails to start. Can you please check from netstat output which process is listening port 80 currently. If it's xo-server, then manually shut it down and try update again. If it's something else, then shut it down or run xo-server in another port.

**Comment by sspanjers** [comment]
That was it.  The VM I had was running apache2 in the background.  I disabled that service, and re-installed the script.  Worked beautifully!  Thanks!
