### ISSUE TITLE
Debian 9.5 setcap failed

### ISSUE THREAD

**Issue by ShiroiKuma** [ronivay/XenOrchestraInstallerUpdater#8]
setcap is missing on a default Debian 9.5 install.

Need to install libcap2-bin to allow the setcap for non-Root bindings to work

**Comment by ShiroiKuma** [comment]
Also looks like 9.5 default install has put node at /usr/bin/node and /usr/bin/nodejs is a symlink

**Comment by hoerup** [comment]
Instead of having distro dependencies for basically the same setcap but with different paths, wouldn't it be better to have a
```
if [ -x "/usr/bin/node" ] ; then
  setcap node
else 
setcap nodejs
fi
```

**Comment by ronivay** [comment]
Hi,

Thanks for reporting this issue. This functionality is indeed a bit old and not tested that well. I redefined it a little and commited a fix in: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/618aeed559e62a247f6199d1ff4106205f2f9972
