### ISSUE TITLE
xo-install freezes on checking universe repository

### ISSUE THREAD

**Issue by maxcerny** [ronivay/XenOrchestraInstallerUpdater#81]
Uubuntu 20.04

**Server specs**
8vCPU 32GB RAM

Installation freezes on checking universe repository.

=== CMD ===: which yum

=== CMD ===: which apt-get

=== CMD ===: which xe

=== CMD ===: which xe

=== CMD ===: add-apt-repository universe

Adding component(s) 'universe' to all repositories.
Press [ENTER] to continue or Ctrl-c to cancel.Aborted.

Easily fixed by adding -y to xo-install.sh

**Comment by maxcerny** [comment]
#82 fixes the issue

**Comment by ronivay** [comment]
Thanks!
