### ISSUE TITLE
Script stuck at curl error

### ISSUE THREAD

**Issue by jeebsion** [ronivay/XenOrchestraInstallerUpdater#84]
I've got this whilst trying to install on version xcp-ng 8.2:

```
Downloading and importing XVA image...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 3716M    0 15107    0     0   5780      0   7d 19h  0:00:02   7d 19h  5781
curl: (23) Failed writing body (0 != 15107)
```
I wonder is there any problem with the curl syntax at all?

**Comment by ronivay** [comment]
Hi,

It's actually xe import command that fails. It doesn't output errors. I need to fix that.

In the meanwhile you can run the failing command manually to see the actual error:

curl "https://xo-appliance.yawn.fi/downloads/image.xva" | xe vm-import filename=/dev/stdin

My guess is that you're missing the default storage repository in your XCP-ng/XenServer (something you setup during installation).

**Comment by ronivay** [comment]
Commited a fix to not throw errors to the trash from import command: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/780d8bd2808f58e849070c270c3e6aa71d804898

**Comment by jeebsion** [comment]
> Hi,
> 
> It's actually xe import command that fails. It doesn't output errors. I need to fix that.
> 
> In the meanwhile you can run the failing command manually to see the actual error:
> 
> curl "https://xo-appliance.yawn.fi/downloads/image.xva" | xe vm-import filename=/dev/stdin
> 
> My guess is that you're missing the default storage repository in your XCP-ng (something you setup during installation).

Apparently yes .. thank you pointing out about the SR .. got it up and running already!

**Comment by ronivay** [comment]
Great! I'll close this then :)
