### ISSUE TITLE
Make it compatible with XCP-NG 8.2.0

### ISSUE THREAD

**Issue by flamme-demon** [ronivay/XenOrchestraInstallerUpdater#87]
Hello,

Thank you for your work.
Would it be possible for you to make your script compatible with the XCP-NG 8.2.0 iso available on the official website?

![image](https://user-images.githubusercontent.com/14869283/124517725-fead8a00-dde4-11eb-85d4-a6c5da190d10.png)

**Comment by flamme-demon** [comment]
I'm sorry, here are some elements

Here is the error when I run the script
![image](https://user-images.githubusercontent.com/14869283/124518252-408b0000-dde6-11eb-8289-6d4bd882d3c2.png)

If I execute the different elements to check OSNAME in the CheckOS function returns an error.
![image](https://user-images.githubusercontent.com/14869283/124518349-7334f880-dde6-11eb-9f95-4f3e42944027.png)

I hope I was more precise.

**Comment by ronivay** [comment]
Ah okay, makes sense. One of my recent changes moved the xcp-ng/xenserver host check further so you hit the OS check before that. I’ll fix that. You should see an error that you shouldn’t install xen orchestra directly to your host. Please use xo-appliance.sh script instead to import a VM or install a fresh VM with one of the supported OS’s an continue to use xo-install.sh on that VM.

**Comment by flamme-demon** [comment]
I had modified your script to see the next error. And I understood my initial error.

![image](https://user-images.githubusercontent.com/14869283/124518984-4b469480-dde8-11eb-97b5-6b17f3049ea6.png)

Thank you for your work.

**Comment by ronivay** [comment]
Cheers. Let me know if you bump into any other issues, i’ll close this for now.
