### ISSUE TITLE
Pulled image

### ISSUE THREAD

**Issue by shortNviolent** [ronivay/XenOrchestraInstallerUpdater#88]
Hey I followed the guide for delpoying the prebuilt image but it wont get a DHCP address. Any ideas where to look?

**Comment by ronivay** [comment]
Hi,

Without knowing more about your setup, hard to say. XCP-ng/XenServer doesn't have any DHCP functionality built-in, so you need to have a separate DHCP server hooked up to the network which you assigned your VM to. Assuming you knew this and have one set up, double check the connectivity between the DHCP server and host physical interface and that the physical interface is assigned to correct network configured on the host.

**Comment by shortNviolent** [comment]
My router, is doing DHCP. Other VMS that I bring up work with out an issue. it is connected to the pool wide Eth0 network. 

When I ran the code: sudo bash -c "$(curl -s https://raw.githubusercontent.com/ronivay/XenOrchestraInstallerUpdater/master/xo-appliance.sh)"

It promted for IP address: I just left it blank, should I have put DHCP there.

**Comment by ronivay** [comment]
Okay. Sounds like it should work then. Leaving IP-address as blank with the script is correct. 

Can you access the VM's console with xcp-ng center or xencenter (whichever you're using)? You should be able to login with credentials mentioned in README. What i'm mostly interested is what does the `/etc/network/interfaces` config look like, is the eth0 interface up as it's supposed to?

Did the script also say in the end that IP-address of the VM couldn't be fetched?

**Comment by shortNviolent** [comment]
There is no folder /etc/network/interfaces that was what was confusing me. There is interfaces.d but that is blank.

![image](https://user-images.githubusercontent.com/48063626/125322726-12d51800-e30c-11eb-98c4-df9540bfa6b8.png)

![image](https://user-images.githubusercontent.com/48063626/125322855-31d3aa00-e30c-11eb-895f-789d8827976b.png)

**Comment by ronivay** [comment]
Thank you. I found a bug which i introduced by accident in the latest image. I'll fix that and let you know when new image is available.

**Comment by ronivay** [comment]
you should actually be able to fix this by just running systemctl start xo-appliance-setup. Can you test?

**Comment by shortNviolent** [comment]
That worked, It has an IP now :D

**Comment by ronivay** [comment]
Great. Reason is that the service that does initial configuration was renamed and because of that didn’t start on first boot anymore. Thanks for the report, will be fixed for good in a moment :)

**Comment by shortNviolent** [comment]
One more Q any reason the updates are disconnected. I assume because its from source and so have to manage it manually?

**Comment by shortNviolent** [comment]
So do I need to redeploy? or will this be ok now?

**Comment by ronivay** [comment]
Yeah built-in update feature is for the official Xen Orchestra appliance only and not supported when built from sources.

You can use `/opt/XenOrchestraInstallerUpdater/xo-install.sh` to update that.

No need to re-deploy the whole appliance as only issue was that one service not starting automatically and running it by hand does the same.

**Comment by shortNviolent** [comment]
Ok cool. Thanks for helping out so quickly

**Comment by ronivay** [comment]
Thanks. I'll close this for now as the fixed image is almost there. Let me know if there's anything more i can help with.
