### ISSUE TITLE
Deal with required nodejs upgrades on --upgrade

### ISSUE THREAD

**Issue by APz** [ronivay/XenOrchestraInstallerUpdater#89]
I've run a Debian virtual in my homelab for some time where XO was installed with this script. At some point the dependencies seem to have changed and now the --upgrade option bombs with following errors in the build log:

`error xo-server@5.80.0: The engine "node" is incompatible with this module. Expected version ">=14.17". Got "14.15.1"
error Found incompatible module.`

Version 14.15 was installed when it the script was first used and it only seems to check for the major version 14.

**Comment by ronivay** [comment]
Hi,

Script will update minor version during update when major version is already correct. This assumes node.js is installed by the script originally as it just updates the nodejs package from repository. If you've installed node.js by any other means manually, then it's unsupported and you need to deal with minor updates by yourself.

Please attach the logfile here (as a separate file) for further debug if it's unclear what is happening.

**Comment by ronivay** [comment]
Anyway that fix is now in place: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/45830168e05169e074e8bd78b087a46685da677c

Get the latest version of script and run update again. If node is still not updated, grab some logs for further debug, thanks.

**Comment by APz** [comment]
I tried the new version and it built correctly now. Thanks for you work!

**Comment by ronivay** [comment]
Awesome. Thanks for the report :)
