### ISSUE TITLE
rolling snapshots no more.

### ISSUE THREAD

**Issue by duven87** [ronivay/XenOrchestraInstallerUpdater#92]
Hi, I updated XOA today and when I go to jobs I see that all the ones related to rolling snapshots don't work anymore.
I have seen that the option in jobs does not appear anymore.
Is it deprecated? Is there any solution to this?
I don't know how to configure a daily snapshot with 5 days retention without this option. 

The snapshot option is there but I don't want to accumulate too many snapshots by creating a daily schedule.

**Comment by ronivay** [comment]
Hi,

Rolling snapshots haven't gone anywhere. Look under backup section, not jobs. From backups -> overview you should see the status of configured backups and little more information when you click the status. Look from logs what might be wrong with your snapshots. One thing that comes to mind immediately is full SR which prevents snapshots being taken.

**Comment by ronivay** [comment]
I assume this thread was opened by you on the xcp-ng forum as it’s about the same symptoms: https://xcp-ng.org/forum/topic/4829/rolling-snapshot-no-appears-more-on-xen-orchestra/7

As the same conclusion was figured out there to use rolling snapshots from backup, i’ll close this. I wasn’t aware that there was a specific xapi action for that in the past which indeed is now deprecated.
