### ISSUE TITLE
Task host.call_plugin stuck on xcpng 8.2

### ISSUE THREAD

**Issue by kenhcs** [ronivay/XenOrchestraInstallerUpdater#95]
Hi ronivay,

After a smooth install on a fresh debian 10, I ran an issue when adding my hosts.

All of my host are running xcp 8.1, except one running xcp 8.2.
All of the tasks performs on the 8.1 clients are fine but the task host.call.plugin on the 8.2 version seems to be loop performing.
She stays forever in my tasks list with 0% achievement.

Regards,
kenhcs

**Comment by ronivay** [comment]
Hi,

So does this prevent you from doing anything on the 8.2 host or are you just concerned of a running task? It's a normal task that will come and go whenever the XAPI is called. Is your 8.2 host behind a NAT by any change?

**Comment by kenhcs** [comment]
It seems that XOA can't retrieve the missing patchs on this host. On the 8.1 hosts, I can see that i have 18 patches to make on them.

This host is on the same lan as the 8.1 clients. I can add my 8.2 host without any problem.
Maybe the 8.2 client haven't any patches to do, and it's me that I believe there's a problem :)

**Comment by ronivay** [comment]
Could be that there isn't any patches if it's fresh :) i wouldn't worry if you don't see actual functional issues or piling tasks beyond that one.

**Comment by kenhcs** [comment]
Maybe that's the point ! Thx for your help. I close the issue for the moment.
