### ISSUE TITLE
not working. Problem with version 8.2.0?

### ISSUE THREAD

**Issue by gurkburk76** [ronivay/XenOrchestraInstallerUpdater#96]
**OS Version**: 
**Node.js version**: node -v v14.17.0
**Yarn version**: yarn -v (return ERROR: There are no scenarios; must have at least one.) Although -v is verbose and not version ;)
yarn --version returns 0.32+git

**Server specs**
amount of vCPUs and RAM on the machine where you attempt to install
2 cpu cores, 8gig mem

**Issue**
describe the issue and what task you were running (update, install)
trying to run the script but it errors out, see log
It would seem like yarn might be doing something odd? (since it didn't like yarn -v and gave the same error as in log.

**Installation logfile**
Attach complete log as a file. 
[13:31 14] xoa@xoa:XenOrchestraInstallerUpdater (master=)$ more /home/xoa/XenOrchestraInstallerUpdater/logs/xo-install.log-202109141330
+ cd . && git config --get remote.origin.url
https://github.com/ronivay/XenOrchestraInstallerUpdater
+ cd . && git fetch
+ cd . && git rev-parse --short HEAD
f8c97f4
+ cd . && git rev-parse --short FETCH_HEAD
f8c97f4
+ cd . && git diff --name-only @{upstream}| grep xo-install.sh
Running script version f8c97f4 with config:

PORT="80"
INSTALLDIR="/opt/xo"
SELFUPGRADE=true
CONFIGUPDATE=true
REPOSITORY="https://github.com/vatesfr/xen-orchestra"
BRANCH="master"
PLUGINS="all"
AUTOUPDATE="true"
OS_CHECK="true"
ARCH_CHECK="true"
PRESERVE="3"

+ id -u
0
+ uname -m
x86_64
+ command -v xe
+ grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo '[0-9]{1,2}' | head -1
11
+ grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}'
Debian
+ command -v yum
+ command -v apt-get
/usr/bin/apt-get
+ command -v systemctl
/usr/bin/systemctl
+ df -P -k '/opt' | tail -1 | awk '{print $4}'
16129016
+ grep MemTotal /proc/meminfo | awk '{print $2}'
8124504
+ pgrep -f xo-server
+ apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
+ apt-get install -y build-essential redis-server libpng-dev git libvhdi-utils python2-minimal lvm2 nfs-common cifs-utils curl
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9).
cifs-utils is already the newest version (2:6.11-3.1).
curl is already the newest version (7.74.0-1.3+b1).
git is already the newest version (1:2.30.2-1).
libpng-dev is already the newest version (1.6.37-3).
libvhdi-utils is already the newest version (20201204-3).
lvm2 is already the newest version (2.03.11-2.1).
nfs-common is already the newest version (1:1.3.4-6).
python2-minimal is already the newest version (2.7.18-3).
redis-server is already the newest version (5:6.0.15-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ apt-get install -y apt-transport-https ca-certificates
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (2.2.4).
ca-certificates is already the newest version (20210119).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ apt-get install gnupg -y
Reading package lists...
Building dependency tree...
Reading state information...
gnupg is already the newest version (2.2.27-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ command -v setcap
/usr/sbin/setcap
+ command -v node
/usr/local/bin/node
+ command -v npm
/usr/local/bin/npm
+ node -v 2>/dev/null| grep -Eo '[0-9.]+' | cut -d'.' -f1
14
+ command -v yarn
/usr/bin/yarn
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
+ cd "/opt/xo/xo-src/xen-orchestra" && git pull --ff-only
Already up to date.
+ cd .
+ rm -rf "/opt/xo/xo-builds/xen-orchestra-202109141330"
+ cp -r "/opt/xo/xo-src/xen-orchestra" "/opt/xo/xo-builds/xen-orchestra-202109141330"
+ cd /opt/xo/xo-builds/xen-orchestra-202109141330 && git rev-parse HEAD
95f029e0e7a7041742e88aeb9666953696f52bb5
+ cd /opt/xo/xo-builds/xen-orchestra-202109141330 && git rev-parse --short HEAD
95f029e0e
+ cd .
+ pgrep -f xo-server
Installing xen-orchestra from branch: master - commit: 95f029e0e
+ cd /opt/xo/xo-builds/xen-orchestra-202109141330 && yarn && yarn build
ERROR: There are no scenarios; must have at least one.
+ rm -rf /opt/xo/xo-builds/xen-orchestra-202109141330

**Comment by gurkburk76** [comment]
I'll try the xo-vm-import.sh and the prebuild variant, if that dosen't work i'll report back.

**Comment by ronivay** [comment]
Definitely an issue with yarn. Need to look into it if it's something in Debian 11. Was this a fresh OS installation and did you let the script install node/yarn?

**Comment by ronivay** [comment]
Okay looks like your OS installation has package called cmdtest which has a binary called yarn, this isn't obviously what is needed and won't work. Script doesn't have a way to check this currently.

You should remove cmdtest package if you don't need it and then rerun the install option of this script.

**Comment by gurkburk76** [comment]
Just to recap, what i did is installer xcp-ng 8.2.0 on a host and then (quick) deployed the vmto control it, changed them mem to 8gb and git cloned your after ssh'ing into the vm.
I first tried to run ./xo-install.sh --update but that threw a fit complaining that yarn wasen't isntalled. i then proceeded to take a cofee.
After that i had woken up i did a ./xo-install.sh --install and that gave the impression of working better, at least it started to download packages that where missing, like yarn i'm guessing.
But.. for some reason, while downloading packages and installing them, it started lie about "There appears to be trouble with your network connection" (i know it works fine, even the dns was resolving) i'm sorry i don't have these logs, i must have closed that putty window.
By this time i just gave up and chose to run with your image instead, seem to work, might try docker later just for kicks.

"They" seem to have build this vm ontop of debian 11, so i guess something there might be weird, i didn't find a package named  "cmdtest" but it seem like it was trying to use some wrappr comman named "command" .. weird.

**Comment by ronivay** [comment]
Ah so you used the official XOA quick deploy and used the same VM for this install script? That's not tested and most likely doesn't work, you need a plain installation of one of the supported OS's (like Debian 11). That's how it says in the readme :) the xo-vm-import.sh is the correct way if you don't have an easy way to deploy a clean VM otherwise and you already did that so should be good.

The `command` command you see in logs is just the script logging what it's doing and `command -v yarn` is used to check if that yarn binary exists, yarn isn't actually executed at that point.

**Comment by gurkburk76** [comment]
Oh so i needed to install a clean machine and THEN the script would so it's magic, i missunderstood and thought that it would simple add stuff to the deployed machine, my bad :)
Ok cool, i got it working the other ways (your image and docker) i don't think it's a worse way of doing things instead of running the script on a new (clean) machine right ?

**Comment by ronivay** [comment]
Yeah. I added a check now that it will refuse to run on XOA VM :)

The image is basically the same outcome that you would get by installing a debian 10 VM by hand and then run xo-install.sh on it so it’s more than fine to use the image option. Docker is obviously different but will do as well.

I’ll close this for now. If there’s any further questions, feel free to continue here.
